/*
 * This header is generated by weak_classdump 0.2
 * on Saturday, October 18, 2014 at 2:24:38 AM Eastern Daylight Time
 * Operating System: Version 7.1.1 (Build 11D201)
 * weak_classdump is Freeware by Elias Limneos.
 *
 */


@interface _CPTConstraintsRelative : CPTConstraints {
	float offset; 
}
@property (assign,nonatomic) float offset; 
-(BOOL)isEqualToConstraint:(id)arg1;
-(float)positionForLowerBound:(float)arg1 upperBound:(float)arg2;
-(id)initWithRelativeOffset:(float)arg1;
-(id)initWithCoder:(id)arg1;
-(void)encodeWithCoder:(id)arg1;
-(id)copyWithZone:(NSZone*)arg1;
-(Class)classForCoder;
-(void)setOffset:(float)arg1;
@end