/*
 * This header is generated by weak_classdump 0.2
 * on Saturday, October 18, 2014 at 2:24:38 AM Eastern Daylight Time
 * Operating System: Version 7.1.1 (Build 11D201)
 * weak_classdump is Freeware by Elias Limneos.
 *
 */

#import <NSCopying.h>
#import <NSCoding.h>

@interface _CPTFillImage : CPTFill <NSCopying, NSCoding> {
	CPTImage* fillImage; 
}
@property (nonatomic,copy) CPTImage* fillImage; 
-(void)fillPathInContext:(struct CGContext*)arg1;
-(void)dealloc;
-(id)initWithCoder:(id)arg1;
-(void)encodeWithCoder:(id)arg1;
-(id)initWithImage:(id)arg1;
-(id)copyWithZone:(NSZone*)arg1;
-(Class)classForCoder;
-(BOOL)isOpaque;
-(void)fillRect:(CGRect)arg1 inContext:(struct CGContext*)arg2;
-(void)setFillImage:(id)arg1;
@end