/*
 * This header is generated by weak_classdump 0.2
 * on Saturday, October 18, 2014 at 2:24:36 AM Eastern Daylight Time
 * Operating System: Version 7.1.1 (Build 11D201)
 * weak_classdump is Freeware by Elias Limneos.
 *
 */


@interface _CPTSlateTheme : _CPTXYTheme {
}
+(id)name;
+(void)load;
-(void)applyThemeToBackground:(id)arg1;
-(void)applyThemeToPlotArea:(id)arg1;
-(void)applyThemeToAxisSet:(id)arg1;
-(void)applyThemeToAxis:(id)arg1 usingMajorLineStyle:(id)arg2 minorLineStyle:(id)arg3 textStyle:(id)arg4 minorTickTextStyle:(id)arg5;
-(Class)classForCoder;
@end