/*
 * This header is generated by weak_classdump 0.2
 * on Saturday, October 18, 2014 at 2:24:46 AM Eastern Daylight Time
 * Operating System: Version 7.1.1 (Build 11D201)
 * weak_classdump is Freeware by Elias Limneos.
 *
 */


@interface _FoodFilter : NSManagedObject {
}
@property (nonatomic,@dynamic,retain) NSNumber* dairy; 
@property (assign) BOOL dairyValue; 
@property (nonatomic,@dynamic,retain) NSNumber* eggs; 
@property (assign) BOOL eggsValue; 
@property (nonatomic,@dynamic,retain) NSNumber* fish; 
@property (assign) BOOL fishValue; 
@property (nonatomic,@dynamic,retain) NSNumber* glutenFree; 
@property (assign) BOOL glutenFreeValue; 
@property (nonatomic,@dynamic,retain) NSNumber* halal; 
@property (assign) BOOL halalValue; 
@property (nonatomic,@dynamic,retain) NSNumber* kosher; 
@property (assign) BOOL kosherValue; 
@property (nonatomic,@dynamic,retain) NSNumber* localRegional; 
@property (assign) BOOL localRegionalValue; 
@property (nonatomic,@dynamic,retain) NSNumber* peanuts; 
@property (assign) BOOL peanutsValue; 
@property (nonatomic,@dynamic,retain) NSNumber* pork; 
@property (assign) BOOL porkValue; 
@property (nonatomic,@dynamic,retain) NSNumber* rated; 
@property (assign) BOOL ratedValue; 
@property (nonatomic,@dynamic,retain) NSNumber* shellfish; 
@property (assign) BOOL shellfishValue; 
@property (nonatomic,@dynamic,retain) NSNumber* soy; 
@property (assign) BOOL soyValue; 
@property (nonatomic,@dynamic,retain) NSNumber* treeNuts; 
@property (assign) BOOL treeNutsValue; 
@property (nonatomic,@dynamic,retain) NSNumber* vegan; 
@property (assign) BOOL veganValue; 
@property (nonatomic,@dynamic,retain) NSNumber* vegetarian; 
@property (assign) BOOL vegetarianValue; 
@property (nonatomic,@dynamic,retain) NSNumber* wheat; 
@property (assign) BOOL wheatValue; 
+(id)entityInManagedObjectContext:(id)arg1;
+(id)entityName;
+(id)insertInManagedObjectContext:(id)arg1;
+(id)keyPathsForValuesAffectingValueForKey:(id)arg1;
-(void)setRatedValue:(BOOL)arg1;
-(void)setVegetarianValue:(BOOL)arg1;
-(void)setGlutenFreeValue:(BOOL)arg1;
-(void)setLocalRegionalValue:(BOOL)arg1;
-(void)setKosherValue:(BOOL)arg1;
-(void)setHalalValue:(BOOL)arg1;
-(void)setVeganValue:(BOOL)arg1;
-(void)setDairyValue:(BOOL)arg1;
-(void)setEggsValue:(BOOL)arg1;
-(void)setFishValue:(BOOL)arg1;
-(void)setPeanutsValue:(BOOL)arg1;
-(void)setPorkValue:(BOOL)arg1;
-(void)setShellfishValue:(BOOL)arg1;
-(void)setSoyValue:(BOOL)arg1;
-(void)setTreeNutsValue:(BOOL)arg1;
-(void)setWheatValue:(BOOL)arg1;
-(BOOL)primitiveDairyValue;
-(void)setPrimitiveDairyValue:(BOOL)arg1;
-(BOOL)primitiveEggsValue;
-(void)setPrimitiveEggsValue:(BOOL)arg1;
-(BOOL)primitiveFishValue;
-(void)setPrimitiveFishValue:(BOOL)arg1;
-(BOOL)primitiveGlutenFreeValue;
-(void)setPrimitiveGlutenFreeValue:(BOOL)arg1;
-(BOOL)primitiveHalalValue;
-(void)setPrimitiveHalalValue:(BOOL)arg1;
-(BOOL)primitiveKosherValue;
-(void)setPrimitiveKosherValue:(BOOL)arg1;
-(BOOL)primitiveLocalRegionalValue;
-(void)setPrimitiveLocalRegionalValue:(BOOL)arg1;
-(BOOL)primitivePeanutsValue;
-(void)setPrimitivePeanutsValue:(BOOL)arg1;
-(BOOL)primitivePorkValue;
-(void)setPrimitivePorkValue:(BOOL)arg1;
-(BOOL)primitiveShellfishValue;
-(void)setPrimitiveShellfishValue:(BOOL)arg1;
-(BOOL)primitiveSoyValue;
-(void)setPrimitiveSoyValue:(BOOL)arg1;
-(BOOL)primitiveTreeNutsValue;
-(void)setPrimitiveTreeNutsValue:(BOOL)arg1;
-(BOOL)primitiveVeganValue;
-(void)setPrimitiveVeganValue:(BOOL)arg1;
-(BOOL)primitiveVegetarianValue;
-(void)setPrimitiveVegetarianValue:(BOOL)arg1;
-(BOOL)primitiveWheatValue;
-(void)setPrimitiveWheatValue:(BOOL)arg1;
-(BOOL)primitiveRatedValue;
-(void)setPrimitiveRatedValue:(BOOL)arg1;
-(id)objectID;
@end