/*
 * This header is generated by weak_classdump 0.2
 * on Saturday, October 18, 2014 at 2:24:54 AM Eastern Daylight Time
 * Operating System: Version 7.1.1 (Build 11D201)
 * weak_classdump is Freeware by Elias Limneos.
 *
 */


@interface _Hours : TempData {
}
@property (nonatomic,@dynamic,retain) NSString* day; 
@property (nonatomic,@dynamic,retain) NSDate* endTime; 
@property (nonatomic,@dynamic,retain) NSDate* startTime; 
@property (nonatomic,@dynamic,retain) Location* location; 
+(id)entityInManagedObjectContext:(id)arg1;
+(id)entityName;
+(id)insertInManagedObjectContext:(id)arg1;
+(id)keyPathsForValuesAffectingValueForKey:(id)arg1;
-(id)objectID;
@end