/*
 * This header is generated by weak_classdump 0.2
 * on Saturday, October 18, 2014 at 2:24:41 AM Eastern Daylight Time
 * Operating System: Version 7.1.1 (Build 11D201)
 * weak_classdump is Freeware by Elias Limneos.
 *
 */


@interface _Location : TempData {
}
@property (nonatomic,@dynamic,retain) NSString* hoursString; 
@property (nonatomic,@dynamic,retain) NSString* locationID; 
@property (nonatomic,@dynamic,retain) NSString* name; 
@property (nonatomic,@dynamic,retain) NSString* shortName; 
@property (nonatomic,@dynamic,retain) NSSet* hours; 
@property (nonatomic,@dynamic,retain) NSSet* meals; 
+(id)entityInManagedObjectContext:(id)arg1;
+(id)entityName;
+(id)insertInManagedObjectContext:(id)arg1;
+(id)keyPathsForValuesAffectingValueForKey:(id)arg1;
-(id)mealsSet;
-(id)hoursSet;
-(id)objectID;
@end