/*
 * This header is generated by weak_classdump 0.2
 * on Saturday, October 18, 2014 at 2:25:00 AM Eastern Daylight Time
 * Operating System: Version 7.1.1 (Build 11D201)
 * weak_classdump is Freeware by Elias Limneos.
 *
 */


@interface _Meal : TempData {
}
@property (nonatomic,@dynamic,retain) NSString* mealID; 
@property (nonatomic,@dynamic,retain) NSString* mealTime; 
@property (nonatomic,@dynamic,retain) NSString* name; 
@property (nonatomic,@dynamic,retain) NSNumber* order; 
@property (assign) short orderValue; 
@property (nonatomic,@dynamic,retain) NSString* shortName; 
@property (nonatomic,@dynamic,retain) NSSet* food; 
@property (nonatomic,@dynamic,retain) Location* location; 
+(id)entityInManagedObjectContext:(id)arg1;
+(id)entityName;
+(id)insertInManagedObjectContext:(id)arg1;
+(id)keyPathsForValuesAffectingValueForKey:(id)arg1;
-(void)setOrderValue:(short)arg1;
-(short)primitiveOrderValue;
-(void)setPrimitiveOrderValue:(short)arg1;
-(id)foodSet;
-(id)objectID;
@end