/*
 * This header is generated by weak_classdump 0.2
 * on Saturday, October 18, 2014 at 2:27:59 AM Eastern Daylight Time
 * Operating System: Version 7.1.1 (Build 11D201)
 * weak_classdump is Freeware by Elias Limneos.
 *
 */

#import <NSCoding.h>
#import <NSCopying.h>

@interface AFHTTPClient : NSObject <NSCoding, NSCopying> {
	BOOL _allowsInvalidSSLCertificate; 
	NSURL* _baseURL; 
	unsigned _stringEncoding; 
	int _parameterEncoding; 
	NSMutableArray* _registeredHTTPOperationClassNames; 
	NSMutableDictionary* _defaultHeaders; 
	NSURLCredential* _defaultCredential; 
	NSOperationQueue* _operationQueue; 
	struct __SCNetworkReachability* _networkReachability; 
	int _networkReachabilityStatus; 
	id _networkReachabilityStatusBlock; 
	int _defaultSSLPinningMode; 
}
@property (nonatomic,retain) NSURL* baseURL; 				//@synthesize baseURL=_baseURL - In the implementation block
@property (assign,nonatomic) unsigned stringEncoding; 				//@synthesize stringEncoding=_stringEncoding - In the implementation block
@property (assign,nonatomic) int parameterEncoding; 				//@synthesize parameterEncoding=_parameterEncoding - In the implementation block
@property (nonatomic,retain) NSOperationQueue* operationQueue; 				//@synthesize operationQueue=_operationQueue - In the implementation block
@property (assign,nonatomic) int networkReachabilityStatus; 				//@synthesize networkReachabilityStatus=_networkReachabilityStatus - In the implementation block
@property (assign,nonatomic) int defaultSSLPinningMode; 				//@synthesize defaultSSLPinningMode=_defaultSSLPinningMode - In the implementation block
@property (assign,nonatomic) BOOL allowsInvalidSSLCertificate; 				//@synthesize allowsInvalidSSLCertificate=_allowsInvalidSSLCertificate - In the implementation block
@property (nonatomic,retain) NSMutableArray* registeredHTTPOperationClassNames; 				//@synthesize registeredHTTPOperationClassNames=_registeredHTTPOperationClassNames - In the implementation block
@property (nonatomic,retain) NSMutableDictionary* defaultHeaders; 				//@synthesize defaultHeaders=_defaultHeaders - In the implementation block
@property (nonatomic,retain) NSURLCredential* defaultCredential; 				//@synthesize defaultCredential=_defaultCredential - In the implementation block
@property (assign,nonatomic) struct __SCNetworkReachability* networkReachability; 				//@synthesize networkReachability=_networkReachability - In the implementation block
@property (nonatomic,copy) id networkReachabilityStatusBlock; 				//@synthesize networkReachabilityStatusBlock=_networkReachabilityStatusBlock - In the implementation block
+(id)clientWithBaseURL:(id)arg1;
-(BOOL)registerHTTPOperationClass:(Class)arg1;
-(void)setDefaultHeader:(id)arg1 value:(id)arg2;
-(void)getPath:(id)arg1 parameters:(id)arg2 success:(id)arg3 failure:(id)arg4;
-(void)setParameterEncoding:(int)arg1;
-(void)setStringEncoding:(unsigned)arg1;
-(void)setRegisteredHTTPOperationClassNames:(id)arg1;
-(void)setDefaultHeaders:(id)arg1;
-(id)requestWithMethod:(id)arg1 path:(id)arg2 parameters:(id)arg3;
-(id)HTTPRequestOperationWithRequest:(id)arg1 success:(id)arg2 failure:(id)arg3;
-(void)enqueueBatchOfHTTPRequestOperations:(id)arg1 progressBlock:(id)arg2 completionBlock:(id)arg3;
-(void)enqueueHTTPRequestOperation:(id)arg1;
-(void)unregisterHTTPOperationClass:(Class)arg1;
-(id)defaultValueForHeader:(id)arg1;
-(void)setAuthorizationHeaderWithUsername:(id)arg1 password:(id)arg2;
-(void)setAuthorizationHeaderWithToken:(id)arg1;
-(void)clearAuthorizationHeader;
-(id)multipartFormRequestWithMethod:(id)arg1 path:(id)arg2 parameters:(id)arg3 constructingBodyWithBlock:(id)arg4;
-(void)cancelAllHTTPOperationsWithMethod:(id)arg1 path:(id)arg2;
-(void)enqueueBatchOfHTTPRequestOperationsWithRequests:(id)arg1 progressBlock:(id)arg2 completionBlock:(id)arg3;
-(void)postPath:(id)arg1 parameters:(id)arg2 success:(id)arg3 failure:(id)arg4;
-(void)putPath:(id)arg1 parameters:(id)arg2 success:(id)arg3 failure:(id)arg4;
-(void)deletePath:(id)arg1 parameters:(id)arg2 success:(id)arg3 failure:(id)arg4;
-(void)patchPath:(id)arg1 parameters:(id)arg2 success:(id)arg3 failure:(id)arg4;
-(void)setNetworkReachabilityStatus:(int)arg1;
-(void)startMonitoringNetworkReachability;
-(void)stopMonitoringNetworkReachability;
-(void)setNetworkReachability:(struct __SCNetworkReachability*)arg1;
-(void)setNetworkReachabilityStatusBlock:(id)arg1;
-(void)setAllowsInvalidSSLCertificate:(BOOL)arg1;
-(void)setReachabilityStatusChangeBlock:(id)arg1;
-(void)setDefaultCredential:(id)arg1;
-(void)setDefaultSSLPinningMode:(int)arg1;
-(void)setOperationQueue:(id)arg1;
-(void)dealloc;
-(id)initWithCoder:(id)arg1;
-(void)encodeWithCoder:(id)arg1;
-(id)init;
-(id)description;
-(id)copyWithZone:(NSZone*)arg1;
-(void).cxx_destruct;
-(void)setBaseURL:(id)arg1;
-(id)initWithBaseURL:(id)arg1;
@end