/*
 * This header is generated by weak_classdump 0.2
 * on Saturday, October 18, 2014 at 2:27:57 AM Eastern Daylight Time
 * Operating System: Version 7.1.1 (Build 11D201)
 * weak_classdump is Freeware by Elias Limneos.
 *
 */


@interface AFImageRequestOperation : AFHTTPRequestOperation {
	BOOL _automaticallyInflatesResponseImage; 
	UIImage* _responseImage; 
	float _imageScale; 
}
@property (nonatomic,retain) UIImage* responseImage; 				//@synthesize responseImage=_responseImage - In the implementation block
@property (assign,nonatomic) float imageScale; 				//@synthesize imageScale=_imageScale - In the implementation block
@property (assign,nonatomic) BOOL automaticallyInflatesResponseImage; 				//@synthesize automaticallyInflatesResponseImage=_automaticallyInflatesResponseImage - In the implementation block
+(BOOL)canProcessRequest:(id)arg1;
+(id)acceptableContentTypes;
+(id)imageRequestOperationWithRequest:(id)arg1 imageProcessingBlock:(id)arg2 success:(id)arg3 failure:(id)arg4;
+(id)imageRequestOperationWithRequest:(id)arg1 success:(id)arg2;
-(void)setCompletionBlockWithSuccess:(id)arg1 failure:(id)arg2;
-(void)setAutomaticallyInflatesResponseImage:(BOOL)arg1;
-(void)setResponseImage:(id)arg1;
-(id)initWithRequest:(id)arg1;
-(void).cxx_destruct;
-(void)setImageScale:(float)arg1;
@end