/*
 * This header is generated by weak_classdump 0.2
 * on Saturday, October 18, 2014 at 2:28:00 AM Eastern Daylight Time
 * Operating System: Version 7.1.1 (Build 11D201)
 * weak_classdump is Freeware by Elias Limneos.
 *
 */


@protocol AFMultipartFormData
@required
-(void)appendPartWithHeaders(id):arg1 body(id):arg2 ;
-(void)appendPartWithFormData(id):arg1 name(id):arg2 ;
-(void)appendPartWithFileData(id):arg1 name(id):arg2 fileName(id):arg3 mimeType(id):arg4 ;
-(BOOL)appendPartWithFileURL(id):arg1 name(id):arg2 error(*):arg3 ;
-(BOOL)appendPartWithFileURL(id):arg1 name(id):arg2 fileName(id):arg3 mimeType(id):arg4 error(*):arg5 ;
-(void)appendPartWithInputStream(id):arg1 name(id):arg2 fileName(id):arg3 length(unsigned long long):arg4 mimeType(id):arg5 ;
-(void)throttleBandwidthWithPacketSize(unsigned):arg1 delay(double):arg2 ;
-(void)appendPartWithHeaders(id):arg1 body(id):arg2 ;
-(void)appendPartWithFormData(id):arg1 name(id):arg2 ;
-(void)appendPartWithFileData(id):arg1 name(id):arg2 fileName(id):arg3 mimeType(id):arg4 ;
-(BOOL)appendPartWithFileURL(id):arg1 name(id):arg2 error(*):arg3 ;
-(BOOL)appendPartWithFileURL(id):arg1 name(id):arg2 fileName(id):arg3 mimeType(id):arg4 error(*):arg5 ;
-(void)appendPartWithInputStream(id):arg1 name(id):arg2 fileName(id):arg3 length(unsigned long long):arg4 mimeType(id):arg5 ;
-(void)throttleBandwidthWithPacketSize(unsigned):arg1 delay(double):arg2 ;
@end
