/*
 * This header is generated by weak_classdump 0.2
 * on Saturday, October 18, 2014 at 2:27:57 AM Eastern Daylight Time
 * Operating System: Version 7.1.1 (Build 11D201)
 * weak_classdump is Freeware by Elias Limneos.
 *
 */


@interface AFNetworkActivityIndicatorManager : NSObject {
	BOOL _enabled; 
	int _activityCount; 
	NSTimer* _activityIndicatorVisibilityTimer; 
}
@property (assign,getter=isEnabled,nonatomic) BOOL enabled; 				//@synthesize enabled=_enabled - In the implementation block
@property (nonatomic,copy) BOOL isNetworkActivityIndicatorVisible; 
@property (assign,nonatomic) int activityCount; 				//@synthesize activityCount=_activityCount - In the implementation block
@property (nonatomic,retain) NSTimer* activityIndicatorVisibilityTimer; 				//@synthesize activityIndicatorVisibilityTimer=_activityIndicatorVisibilityTimer - In the implementation block
@property (getter=isNetworkActivityIndicatorVisible,nonatomic,@dynamic,copy) BOOL networkActivityIndicatorVisible; 
+(id)keyPathsForValuesAffectingIsNetworkActivityIndicatorVisible;
+(id)sharedManager;
-(void)incrementActivityCount;
-(void)decrementActivityCount;
-(void)updateNetworkActivityIndicatorVisibility;
-(void)setActivityIndicatorVisibilityTimer:(id)arg1;
-(void)updateNetworkActivityIndicatorVisibilityDelayed;
-(void)setActivityCount:(int)arg1;
-(void)networkingOperationDidStart:(id)arg1;
-(void)networkingOperationDidFinish:(id)arg1;
-(void)dealloc;
-(id)init;
-(void)setEnabled:(BOOL)arg1;
-(void).cxx_destruct;
@end