/*
 * This header is generated by weak_classdump 0.2
 * on Saturday, October 18, 2014 at 2:27:56 AM Eastern Daylight Time
 * Operating System: Version 7.1.1 (Build 11D201)
 * weak_classdump is Freeware by Elias Limneos.
 *
 */


@interface AFPropertyListRequestOperation : AFHTTPRequestOperation {
	id _responsePropertyList; 
	unsigned _propertyListReadOptions; 
	unsigned _propertyListFormat; 
	NSError* _propertyListError; 
}
@property (nonatomic,retain) id responsePropertyList; 				//@synthesize responsePropertyList=_responsePropertyList - In the implementation block
@property (assign,nonatomic) unsigned propertyListReadOptions; 				//@synthesize propertyListReadOptions=_propertyListReadOptions - In the implementation block
@property (assign,nonatomic) unsigned propertyListFormat; 				//@synthesize propertyListFormat=_propertyListFormat - In the implementation block
@property (nonatomic,retain) NSError* propertyListError; 				//@synthesize propertyListError=_propertyListError - In the implementation block
+(BOOL)canProcessRequest:(id)arg1;
+(id)acceptableContentTypes;
+(id)propertyListRequestOperationWithRequest:(id)arg1 success:(id)arg2 failure:(id)arg3;
-(void)setCompletionBlockWithSuccess:(id)arg1 failure:(id)arg2;
-(void)setPropertyListReadOptions:(unsigned)arg1;
-(void)setResponsePropertyList:(id)arg1;
-(void)setPropertyListFormat:(unsigned)arg1;
-(void)setPropertyListError:(id)arg1;
-(id)initWithRequest:(id)arg1;
-(void).cxx_destruct;
-(id)error;
@end