/*
 * This header is generated by weak_classdump 0.2
 * on Saturday, October 18, 2014 at 2:28:01 AM Eastern Daylight Time
 * Operating System: Version 7.1.1 (Build 11D201)
 * weak_classdump is Freeware by Elias Limneos.
 *
 */


@interface AFQueryStringPair : NSObject {
	id _field; 
	id _value; 
}
@property (nonatomic,retain) id field; 				//@synthesize field=_field - In the implementation block
@property (nonatomic,retain) id value; 				//@synthesize value=_value - In the implementation block
-(id)URLEncodedStringValueWithEncoding:(unsigned)arg1;
-(id)initWithField:(id)arg1 value:(id)arg2;
-(void)setValue:(id)arg1;
-(void).cxx_destruct;
-(void)setField:(id)arg1;
@end