/*
 * This header is generated by weak_classdump 0.2
 * on Saturday, October 18, 2014 at 2:28:00 AM Eastern Daylight Time
 * Operating System: Version 7.1.1 (Build 11D201)
 * weak_classdump is Freeware by Elias Limneos.
 *
 */

#import <AFMultipartFormData.h>

@interface AFStreamingMultipartFormData : NSObject <AFMultipartFormData> {
	NSMutableURLRequest* _request; 
	AFMultipartBodyStream* _bodyStream; 
	unsigned _stringEncoding; 
}
@property (nonatomic,copy) NSMutableURLRequest* request; 				//@synthesize request=_request - In the implementation block
@property (nonatomic,retain) AFMultipartBodyStream* bodyStream; 				//@synthesize bodyStream=_bodyStream - In the implementation block
@property (assign,nonatomic) unsigned stringEncoding; 				//@synthesize stringEncoding=_stringEncoding - In the implementation block
-(void)appendPartWithHeaders:(id)arg1 body:(id)arg2;
-(void)setStringEncoding:(unsigned)arg1;
-(id)initWithURLRequest:(id)arg1 stringEncoding:(unsigned)arg2;
-(void)appendPartWithFormData:(id)arg1 name:(id)arg2;
-(id)requestByFinalizingMultipartFormData;
-(void)appendPartWithFileData:(id)arg1 name:(id)arg2 fileName:(id)arg3 mimeType:(id)arg4;
-(BOOL)appendPartWithFileURL:(id)arg1 name:(id)arg2 error:(id*)arg3;
-(void)setBodyStream:(id)arg1;
-(BOOL)appendPartWithFileURL:(id)arg1 name:(id)arg2 fileName:(id)arg3 mimeType:(id)arg4 error:(id*)arg5;
-(void)appendPartWithInputStream:(id)arg1 name:(id)arg2 fileName:(id)arg3 length:(unsigned long long)arg4 mimeType:(id)arg5;
-(void)throttleBandwidthWithPacketSize:(unsigned)arg1 delay:(double)arg2;
-(void)setRequest:(id)arg1;
-(void).cxx_destruct;
@end