/*
 * This header is generated by weak_classdump 0.2
 * on Saturday, October 18, 2014 at 2:27:56 AM Eastern Daylight Time
 * Operating System: Version 7.1.1 (Build 11D201)
 * weak_classdump is Freeware by Elias Limneos.
 *
 */


@interface AFXMLRequestOperation : AFHTTPRequestOperation {
	NSXMLParser* _responseXMLParser; 
	NSError* _XMLError; 
}
@property (nonatomic,retain) NSXMLParser* responseXMLParser; 				//@synthesize responseXMLParser=_responseXMLParser - In the implementation block
@property (nonatomic,retain) NSError* XMLError; 				//@synthesize XMLError=_XMLError - In the implementation block
+(BOOL)canProcessRequest:(id)arg1;
+(id)acceptableContentTypes;
+(id)XMLParserRequestOperationWithRequest:(id)arg1 success:(id)arg2 failure:(id)arg3;
-(void)setCompletionBlockWithSuccess:(id)arg1 failure:(id)arg2;
-(void)setResponseXMLParser:(id)arg1;
-(void)setXMLError:(id)arg1;
-(void)cancel;
-(void).cxx_destruct;
-(id)error;
@end