/*
 * This header is generated by weak_classdump 0.2
 * on Saturday, October 18, 2014 at 2:27:41 AM Eastern Daylight Time
 * Operating System: Version 7.1.1 (Build 11D201)
 * weak_classdump is Freeware by Elias Limneos.
 *
 */


@interface BalanceInfo : _BalanceInfo {
}
+(id)fetchAllSortedBy:(id)arg1 ascending:(BOOL)arg2 withPredicate:(id)arg3 groupBy:(id)arg4 delegate:(id)arg5;
@end