/*
 * This header is generated by weak_classdump 0.2
 * on Saturday, October 18, 2014 at 2:27:54 AM Eastern Daylight Time
 * Operating System: Version 7.1.1 (Build 11D201)
 * weak_classdump is Freeware by Elias Limneos.
 *
 */


@interface BButton : UIButton {
	BOOL shouldShowDisabled; 
	UIColor* color; 
	struct CGGradient* gradient; 
}
@property (nonatomic,retain) UIColor* color; 
@property (assign,nonatomic) BOOL shouldShowDisabled; 
@property (assign,nonatomic) struct CGGradient* gradient; 
+(id)colorForButtonType:(int)arg1;
+(id)awesomeButtonWithOnlyIcon:(int)arg1 color:(id)arg2;
+(id)awesomeButtonWithOnlyIcon:(int)arg1 type:(int)arg2;
-(void)setShouldShowDisabled:(BOOL)arg1;
-(id)initWithFrame:(CGRect)arg1 color:(id)arg2;
-(id)initWithFrame:(CGRect)arg1 color:(id)arg2 icon:(int)arg3 fontSize:(float)arg4;
-(void)setGradientEnabled:(BOOL)arg1;
-(id)initWithFrame:(CGRect)arg1 type:(int)arg2 icon:(int)arg3 fontSize:(float)arg4;
-(void)addAwesomeIcon:(int)arg1 beforeTitle:(BOOL)arg2;
-(id)initWithFrame:(CGRect)arg1;
-(void)drawRect:(CGRect)arg1;
-(id)initWithCoder:(id)arg1;
-(id)init;
-(void)setType:(int)arg1;
-(void)setEnabled:(BOOL)arg1;
-(void)setHighlighted:(BOOL)arg1;
-(void)setColor:(id)arg1;
-(void)setGradient:(struct CGGradient*)arg1;
-(void).cxx_destruct;
-(void)setup;
-(id)initWithFrame:(CGRect)arg1 type:(int)arg2;
@end