/*
 * This header is generated by weak_classdump 0.2
 * on Saturday, October 18, 2014 at 2:28:16 AM Eastern Daylight Time
 * Operating System: Version 7.1.1 (Build 11D201)
 * weak_classdump is Freeware by Elias Limneos.
 *
 */


@protocol BITAuthenticationViewControllerDelegate
@required
-(void)authenticationViewControllerDidTapWebButton(id):arg1 ;
-(void)authenticationViewController(id):arg1 handleAuthenticationWithEmail(id):arg2 password(id):arg3 completion(id):arg4 ;
-(void)authenticationViewControllerDidTapWebButton(id):arg1 ;
-(void)authenticationViewController(id):arg1 handleAuthenticationWithEmail(id):arg2 password(id):arg3 completion(id):arg4 ;
@end
