/*
 * This header is generated by weak_classdump 0.2
 * on Saturday, October 18, 2014 at 2:28:18 AM Eastern Daylight Time
 * Operating System: Version 7.1.1 (Build 11D201)
 * weak_classdump is Freeware by Elias Limneos.
 *
 */

#import <UITextFieldDelegate.h>

@interface BITAuthenticationViewController : UITableViewController <UITextFieldDelegate> {
	int _statusBarStyle; 
	UITextField* _emailField; 
	BOOL _showsLoginViaWebButton; 
	BOOL _requirePassword; 
	NSString* _tableViewTitle; 
	id<BITAuthenticationViewControllerDelegate> _delegate; 
	NSString* _email; 
	NSString* _password; 
}
@property (assign,nonatomic) BOOL showsLoginViaWebButton; 				//@synthesize showsLoginViaWebButton=_showsLoginViaWebButton - In the implementation block
@property (nonatomic,copy) NSString* tableViewTitle; 				//@synthesize tableViewTitle=_tableViewTitle - In the implementation block
@property (assign,nonatomic) BOOL requirePassword; 				//@synthesize requirePassword=_requirePassword - In the implementation block
@property (assign,nonatomic,__weak) id<BITAuthenticationViewControllerDelegate> delegate; 				//@synthesize delegate=_delegate - In the implementation block
@property (nonatomic,copy) NSString* email; 				//@synthesize email=_email - In the implementation block
@property (nonatomic,copy) NSString* password; 				//@synthesize password=_password - In the implementation block
-(void)updateWebLoginButton;
-(void)updateBarButtons;
-(void)handleWebLoginButton:(id)arg1;
-(void)userPasswordEntered:(id)arg1;
-(void)setLoginUIEnabled:(BOOL)arg1;
-(void)setRequirePassword:(BOOL)arg1;
-(void)setTableViewTitle:(id)arg1;
-(void)setShowsLoginViaWebButton:(BOOL)arg1;
-(void)saveAction:(id)arg1;
-(BOOL)allRequiredFieldsEntered;
-(void)userEmailEntered:(id)arg1;
-(void)setPassword:(id)arg1;
-(void)setDelegate:(id)arg1;
-(int)tableView:(id)arg1 numberOfRowsInSection:(int)arg2;
-(id)tableView:(id)arg1 cellForRowAtIndexPath:(id)arg2;
-(int)numberOfSectionsInTableView:(id)arg1;
-(id)tableView:(id)arg1 titleForFooterInSection:(int)arg2;
-(BOOL)textFieldShouldReturn:(id)arg1;
-(BOOL)shouldAutorotateToInterfaceOrientation:(int)arg1;
-(void)viewWillAppear:(BOOL)arg1;
-(void)viewDidLoad;
-(void)viewWillDisappear:(BOOL)arg1;
-(void).cxx_destruct;
-(void)setEmail:(id)arg1;
-(id)initWithDelegate:(id)arg1;
@end