/*
 * This header is generated by weak_classdump 0.2
 * on Saturday, October 18, 2014 at 2:28:15 AM Eastern Daylight Time
 * Operating System: Version 7.1.1 (Build 11D201)
 * weak_classdump is Freeware by Elias Limneos.
 *
 */


@interface BITCrashReportTextFormatter : NSObject {
}
+(id)bit_formatStackFrame:(id)arg1 frameIndex:(unsigned)arg2 report:(id)arg3 lp64:(BOOL)arg4;
+(id)bit_archNameFromImageInfo:(id)arg1;
+(id)stringValueForCrashReport:(id)arg1 crashReporterKey:(id)arg2;
+(id)arrayOfAppUUIDsForCrashReport:(id)arg1;
@end