/*
 * This header is generated by weak_classdump 0.2
 * on Saturday, October 18, 2014 at 2:28:14 AM Eastern Daylight Time
 * Operating System: Version 7.1.1 (Build 11D201)
 * weak_classdump is Freeware by Elias Limneos.
 *
 */

#import <BITFeedbackUserDataDelegate.h>
#import <UITextViewDelegate.h>

@interface BITFeedbackComposeViewController : UIViewController <BITFeedbackUserDataDelegate, UITextViewDelegate> {
	int _statusBarStyle; 
	BOOL _blockUserDataScreen; 
	id<BITFeedbackComposeViewControllerDelegate> _delegate; 
	BITFeedbackManager* _manager; 
	UITextView* _textView; 
	NSString* _text; 
}
@property (assign,nonatomic,__weak) id<BITFeedbackComposeViewControllerDelegate> delegate; 				//@synthesize delegate=_delegate - In the implementation block
@property (assign,nonatomic,__weak) BITFeedbackManager* manager; 				//@synthesize manager=_manager - In the implementation block
@property (nonatomic,retain) UITextView* textView; 				//@synthesize textView=_textView - In the implementation block
@property (nonatomic,retain) NSString* text; 				//@synthesize text=_text - In the implementation block
-(void)prepareWithItems:(id)arg1;
-(void)sendAction:(id)arg1;
-(void)setUserDataAction;
-(void)dismissWithResult:(unsigned)arg1;
-(void)dismissAction:(id)arg1;
-(void)userDataUpdateCancelled;
-(void)userDataUpdateFinished;
-(void)keyboardWasShown:(id)arg1;
-(void)keyboardWillBeHidden:(id)arg1;
-(void)setDelegate:(id)arg1;
-(id)init;
-(void)setText:(id)arg1;
-(void)setTextView:(id)arg1;
-(BOOL)shouldAutorotateToInterfaceOrientation:(int)arg1;
-(void)viewWillAppear:(BOOL)arg1;
-(void)viewDidLoad;
-(void)viewDidAppear:(BOOL)arg1;
-(void)viewWillDisappear:(BOOL)arg1;
-(void)viewDidDisappear:(BOOL)arg1;
-(void)textViewDidChange:(id)arg1;
-(void).cxx_destruct;
-(void)setManager:(id)arg1;
@end