/*
 * This header is generated by weak_classdump 0.2
 * on Saturday, October 18, 2014 at 2:28:12 AM Eastern Daylight Time
 * Operating System: Version 7.1.1 (Build 11D201)
 * weak_classdump is Freeware by Elias Limneos.
 *
 */


@interface BITFeedbackListViewCell : UITableViewCell {
	BITFeedbackMessage* _message; 
	unsigned _style; 
	unsigned _backgroundStyle; 
	BITAttributedLabel* _labelText; 
	NSDateFormatter* _dateFormatter; 
	NSDateFormatter* _timeFormatter; 
	UILabel* _labelTitle; 
}
@property (nonatomic,retain) BITFeedbackMessage* message; 				//@synthesize message=_message - In the implementation block
@property (assign,nonatomic) unsigned style; 				//@synthesize style=_style - In the implementation block
@property (assign,nonatomic) unsigned backgroundStyle; 				//@synthesize backgroundStyle=_backgroundStyle - In the implementation block
@property (nonatomic,retain) BITAttributedLabel* labelText; 				//@synthesize labelText=_labelText - In the implementation block
@property (nonatomic,retain) NSDateFormatter* dateFormatter; 				//@synthesize dateFormatter=_dateFormatter - In the implementation block
@property (nonatomic,retain) NSDateFormatter* timeFormatter; 				//@synthesize timeFormatter=_timeFormatter - In the implementation block
@property (nonatomic,retain) UILabel* labelTitle; 				//@synthesize labelTitle=_labelTitle - In the implementation block
+(float)heightForRowWithMessage:(id)arg1 tableViewWidth:(float)arg2;
-(void)setDateFormatter:(id)arg1;
-(void)setTimeFormatter:(id)arg1;
-(void)setLabelTitle:(id)arg1;
-(BOOL)isSameDayWithDate1:(id)arg1 date2:(id)arg2;
-(id)backgroundColor;
-(void)layoutSubviews;
-(id)initWithStyle:(int)arg1 reuseIdentifier:(id)arg2;
-(void)setStyle:(unsigned)arg1;
-(void)setMessage:(id)arg1;
-(void).cxx_destruct;
-(void)setBackgroundStyle:(unsigned)arg1;
-(void)setLabelText:(id)arg1;
@end