/*
 * This header is generated by weak_classdump 0.2
 * on Saturday, October 18, 2014 at 2:28:14 AM Eastern Daylight Time
 * Operating System: Version 7.1.1 (Build 11D201)
 * weak_classdump is Freeware by Elias Limneos.
 *
 */


@protocol BITFeedbackUserDataDelegate
@required
-(void)userDataUpdateCancelled;
-(void)userDataUpdateFinished;
-(void)userDataUpdateCancelled;
-(void)userDataUpdateFinished;
@end
