/*
 * This header is generated by weak_classdump 0.2
 * on Saturday, October 18, 2014 at 2:28:09 AM Eastern Daylight Time
 * Operating System: Version 7.1.1 (Build 11D201)
 * weak_classdump is Freeware by Elias Limneos.
 *
 */

#import <UITextFieldDelegate.h>

@interface BITFeedbackUserDataViewController : UITableViewController <UITextFieldDelegate> {
	int _statusBarStyle; 
	id<BITFeedbackUserDataDelegate> _delegate; 
	BITFeedbackManager* _manager; 
	NSString* _name; 
	NSString* _email; 
}
@property (assign,nonatomic,__weak) id<BITFeedbackUserDataDelegate> delegate; 				//@synthesize delegate=_delegate - In the implementation block
@property (assign,nonatomic,__weak) BITFeedbackManager* manager; 				//@synthesize manager=_manager - In the implementation block
@property (nonatomic,copy) NSString* name; 				//@synthesize name=_name - In the implementation block
@property (nonatomic,copy) NSString* email; 				//@synthesize email=_email - In the implementation block
-(void)dismissAction:(id)arg1;
-(void)saveAction:(id)arg1;
-(BOOL)allRequiredFieldsEntered;
-(void)userNameEntered:(id)arg1;
-(void)userEmailEntered:(id)arg1;
-(void)setDelegate:(id)arg1;
-(int)tableView:(id)arg1 numberOfRowsInSection:(int)arg2;
-(id)tableView:(id)arg1 cellForRowAtIndexPath:(id)arg2;
-(int)numberOfSectionsInTableView:(id)arg1;
-(id)tableView:(id)arg1 titleForFooterInSection:(int)arg2;
-(void)setName:(id)arg1;
-(BOOL)textFieldShouldReturn:(id)arg1;
-(id)initWithStyle:(int)arg1;
-(BOOL)shouldAutorotateToInterfaceOrientation:(int)arg1;
-(void)viewWillAppear:(BOOL)arg1;
-(void)viewDidLoad;
-(void)viewWillDisappear:(BOOL)arg1;
-(void).cxx_destruct;
-(void)setEmail:(id)arg1;
-(void)setManager:(id)arg1;
@end