/*
 * This header is generated by weak_classdump 0.2
 * on Saturday, October 18, 2014 at 2:28:08 AM Eastern Daylight Time
 * Operating System: Version 7.1.1 (Build 11D201)
 * weak_classdump is Freeware by Elias Limneos.
 *
 */

#import <NSURLConnectionDelegate.h>

@interface BITHTTPOperation : NSOperation <NSURLConnectionDelegate> {
	NSURLRequest* _URLRequest; 
	NSURLConnection* _connection; 
	NSMutableData* _data; 
	BOOL _isExecuting; 
	BOOL _isFinished; 
	NSHTTPURLResponse* _response; 
	NSError* _error; 
}
@property (nonatomic,copy) NSURLRequest* URLRequest; 				//@synthesize URLRequest=_URLRequest - In the implementation block
@property (nonatomic,copy) NSHTTPURLResponse* response; 				//@synthesize response=_response - In the implementation block
@property (nonatomic,copy) NSData* data; 
@property (nonatomic,copy) NSError* error; 				//@synthesize error=_error - In the implementation block
+(id)operationWithRequest:(id)arg1;
-(BOOL)isConcurrent;
-(void)setCompletion:(id)arg1;
-(void)cancel;
-(void)start;
-(void)connection:(id)arg1 didFailWithError:(id)arg2;
-(void)connection:(id)arg1 didReceiveData:(id)arg2;
-(void)connectionDidFinishLoading:(id)arg1;
-(void)connection:(id)arg1 didReceiveResponse:(id)arg2;
-(void).cxx_destruct;
-(BOOL)isFinished;
-(BOOL)isExecuting;
-(void)finish;
@end