/*
 * This header is generated by weak_classdump 0.2
 * on Saturday, October 18, 2014 at 2:28:08 AM Eastern Daylight Time
 * Operating System: Version 7.1.1 (Build 11D201)
 * weak_classdump is Freeware by Elias Limneos.
 *
 */


@interface BITHockeyBaseManager : NSObject {
	UINavigationController* _navController; 
	NSDateFormatter* _rfc3339Formatter; 
	BOOL _isAppStoreEnvironment; 
	NSString* _serverURL; 
	int _barStyle; 
	UIColor* _navigationBarTintColor; 
	int _modalPresentationStyle; 
	NSString* _appIdentifier; 
}
@property (nonatomic,copy) NSString* serverURL; 				//@synthesize serverURL=_serverURL - In the implementation block
@property (assign,nonatomic) int barStyle; 				//@synthesize barStyle=_barStyle - In the implementation block
@property (nonatomic,retain) UIColor* navigationBarTintColor; 				//@synthesize navigationBarTintColor=_navigationBarTintColor - In the implementation block
@property (assign,nonatomic) int modalPresentationStyle; 				//@synthesize modalPresentationStyle=_modalPresentationStyle - In the implementation block
@property (nonatomic,retain) NSString* appIdentifier; 				//@synthesize appIdentifier=_appIdentifier - In the implementation block
-(BOOL)isPreiOS7Environment;
-(BOOL)isAppStoreEnvironment;
-(id)findVisibleWindow;
-(void)showView:(id)arg1;
-(id)customNavigationControllerWithRootViewController:(id)arg1 presentationStyle:(int)arg2;
-(id)initWithAppIdentifier:(id)arg1 isAppStoreEnvironment:(BOOL)arg2;
-(id)encodedAppIdentifier;
-(id)getDevicePlatform;
-(id)executableUUID;
-(BOOL)addStringValueToKeychain:(id)arg1 forKey:(id)arg2;
-(BOOL)addStringValueToKeychainForThisDeviceOnly:(id)arg1 forKey:(id)arg2;
-(id)stringValueFromKeychainForKey:(id)arg1;
-(BOOL)removeKeyFromKeychain:(id)arg1;
-(id)parseRFC3339Date:(id)arg1;
-(id)init;
-(void)setBarStyle:(int)arg1;
-(void)setNavigationBarTintColor:(id)arg1;
-(void)setModalPresentationStyle:(int)arg1;
-(void).cxx_destruct;
-(void)setServerURL:(id)arg1;
-(void)startManager;
-(void)setAppIdentifier:(id)arg1;
-(void)reportError:(id)arg1;
@end