/*
 * This header is generated by weak_classdump 0.2
 * on Saturday, October 18, 2014 at 2:28:06 AM Eastern Daylight Time
 * Operating System: Version 7.1.1 (Build 11D201)
 * weak_classdump is Freeware by Elias Limneos.
 *
 */


@interface BITHockeyBaseViewController : UITableViewController {
	BOOL _modal; 
	int _statusBarStyle; 
	BOOL _modalAnimated; 
}
@property (assign,nonatomic) BOOL modalAnimated; 				//@synthesize modalAnimated=_modalAnimated - In the implementation block
-(void)setModalAnimated:(BOOL)arg1;
-(void)onDismissModal:(id)arg1;
-(id)initWithStyle:(int)arg1 modal:(BOOL)arg2;
-(id)initWithModalStyle:(BOOL)arg1;
-(id)initWithStyle:(int)arg1;
-(BOOL)shouldAutorotateToInterfaceOrientation:(int)arg1;
-(void)viewWillAppear:(BOOL)arg1;
-(void)viewWillDisappear:(BOOL)arg1;
@end