/*
 * This header is generated by weak_classdump 0.2
 * on Saturday, October 18, 2014 at 2:28:07 AM Eastern Daylight Time
 * Operating System: Version 7.1.1 (Build 11D201)
 * weak_classdump is Freeware by Elias Limneos.
 *
 */


@interface BITHockeyManager : NSObject {
	NSString* _appIdentifier; 
	NSString* _liveIdentifier; 
	BOOL _validAppIdentifier; 
	BOOL _startManagerIsInvoked; 
	BOOL _startUpdateManagerIsInvoked; 
	BITHockeyAppClient* _hockeyAppClient; 
	BOOL _disableCrashManager; 
	BOOL _disableUpdateManager; 
	BOOL _enableStoreUpdateManager; 
	BOOL _disableFeedbackManager; 
	BOOL _appStoreEnvironment; 
	BOOL _debugLogEnabled; 
	id<BITHockeyManagerDelegate> _delegate; 
	NSString* _serverURL; 
	BITCrashManager* _crashManager; 
	BITUpdateManager* _updateManager; 
	BITStoreUpdateManager* _storeUpdateManager; 
	BITFeedbackManager* _feedbackManager; 
	BITAuthenticator* _authenticator; 
	NSString* _installString; 
}
@property (assign,nonatomic,__weak) id<BITHockeyManagerDelegate> delegate; 				//@synthesize delegate=_delegate - In the implementation block
@property (nonatomic,retain) NSString* serverURL; 				//@synthesize serverURL=_serverURL - In the implementation block
@property (nonatomic,copy) BITCrashManager* crashManager; 				//@synthesize crashManager=_crashManager - In the implementation block
@property (assign,getter=isCrashManagerDisabled,nonatomic) BOOL disableCrashManager; 				//@synthesize disableCrashManager=_disableCrashManager - In the implementation block
@property (nonatomic,copy) BITUpdateManager* updateManager; 				//@synthesize updateManager=_updateManager - In the implementation block
@property (assign,getter=isUpdateManagerDisabled,nonatomic) BOOL disableUpdateManager; 				//@synthesize disableUpdateManager=_disableUpdateManager - In the implementation block
@property (nonatomic,copy) BITStoreUpdateManager* storeUpdateManager; 				//@synthesize storeUpdateManager=_storeUpdateManager - In the implementation block
@property (assign,getter=isStoreUpdateManagerEnabled,nonatomic) BOOL enableStoreUpdateManager; 				//@synthesize enableStoreUpdateManager=_enableStoreUpdateManager - In the implementation block
@property (nonatomic,copy) BITFeedbackManager* feedbackManager; 				//@synthesize feedbackManager=_feedbackManager - In the implementation block
@property (assign,getter=isFeedbackManagerDisabled,nonatomic) BOOL disableFeedbackManager; 				//@synthesize disableFeedbackManager=_disableFeedbackManager - In the implementation block
@property (nonatomic,copy) BITAuthenticator* authenticator; 				//@synthesize authenticator=_authenticator - In the implementation block
@property (getter=isAppStoreEnvironment,nonatomic,copy) BOOL appStoreEnvironment; 				//@synthesize appStoreEnvironment=_appStoreEnvironment - In the implementation block
@property (nonatomic,copy) NSString* installString; 				//@synthesize installString=_installString - In the implementation block
@property (assign,getter=isDebugLogEnabled,nonatomic) BOOL debugLogEnabled; 				//@synthesize debugLogEnabled=_debugLogEnabled - In the implementation block
+(id)sharedHockeyManager;
-(void)configureWithBetaIdentifier:(id)arg1 liveIdentifier:(id)arg2 delegate:(id)arg3;
-(void)setDisableFeedbackManager:(BOOL)arg1;
-(void)validateStartManagerIsInvoked;
-(void)initializeModules;
-(BOOL)checkValidityOfAppIdentifier:(id)arg1;
-(void)logInvalidIdentifier:(id)arg1;
-(BOOL)shouldUseLiveIdentifier;
-(BOOL)isSetUpOnMainThread;
-(void)invokeStartUpdateManager;
-(void)setEnableStoreUpdateManager:(BOOL)arg1;
-(void)pingServerForIntegrationStartWorkflowWithTimeString:(id)arg1 appIdentifier:(id)arg2;
-(id)hockeyAppClient;
-(id)integrationFlowTimeString;
-(BOOL)integrationFlowStartedWithTimeString:(id)arg1;
-(void)configureWithIdentifier:(id)arg1;
-(void)configureWithIdentifier:(id)arg1 delegate:(id)arg2;
-(void)testIdentifier;
-(void)setDisableCrashManager:(BOOL)arg1;
-(void)setDebugLogEnabled:(BOOL)arg1;
-(void)setDisableUpdateManager:(BOOL)arg1;
-(void)setDelegate:(id)arg1;
-(id)init;
-(void)observeValueForKeyPath:(id)arg1 ofObject:(id)arg2 change:(id)arg3 context:(void*)arg4;
-(id)version;
-(void).cxx_destruct;
-(void)setServerURL:(id)arg1;
-(void)startManager;
-(id)build;
@end