/*
 * This header is generated by weak_classdump 0.2
 * on Saturday, October 18, 2014 at 2:24:39 AM Eastern Daylight Time
 * Operating System: Version 7.1.1 (Build 11D201)
 * weak_classdump is Freeware by Elias Limneos.
 *
 */


@interface BITPLCrashReportApplicationInfo : NSObject {
	NSString* _applicationIdentifier; 
	NSString* _applicationVersion; 
}
@property (nonatomic,copy) NSString* applicationIdentifier; 				//@synthesize applicationIdentifier=_applicationIdentifier - In the implementation block
@property (nonatomic,copy) NSString* applicationVersion; 				//@synthesize applicationVersion=_applicationVersion - In the implementation block
-(id)initWithApplicationIdentifier:(id)arg1 applicationVersion:(id)arg2;
-(void)dealloc;
@end