/*
 * This header is generated by weak_classdump 0.2
 * on Saturday, October 18, 2014 at 2:24:35 AM Eastern Daylight Time
 * Operating System: Version 7.1.1 (Build 11D201)
 * weak_classdump is Freeware by Elias Limneos.
 *
 */


@interface BITPLCrashHostInfo : NSObject {
	struct PLCrashHostInfoVersion _darwinVersion; 
}
@property (nonatomic,copy) struct PLCrashHostInfoVersion darwinVersion; 				//@synthesize darwinVersion=_darwinVersion - In the implementation block
+(id)currentHostInfo;
-(id)init;
@end