/*
 * This header is generated by weak_classdump 0.2
 * on Saturday, October 18, 2014 at 2:24:36 AM Eastern Daylight Time
 * Operating System: Version 7.1.1 (Build 11D201)
 * weak_classdump is Freeware by Elias Limneos.
 *
 */


@interface BITPLCrashReportMachineInfo : NSObject {
	NSString* _modelName; 
	BITPLCrashReportProcessorInfo* _processorInfo; 
	unsigned _processorCount; 
	unsigned _logicalProcessorCount; 
}
@property (nonatomic,copy) NSString* modelName; 				//@synthesize modelName=_modelName - In the implementation block
@property (nonatomic,copy) BITPLCrashReportProcessorInfo* processorInfo; 				//@synthesize processorInfo=_processorInfo - In the implementation block
@property (nonatomic,copy) unsigned processorCount; 				//@synthesize processorCount=_processorCount - In the implementation block
@property (nonatomic,copy) unsigned logicalProcessorCount; 				//@synthesize logicalProcessorCount=_logicalProcessorCount - In the implementation block
-(id)initWithModelName:(id)arg1 processorInfo:(id)arg2 processorCount:(unsigned)arg3 logicalProcessorCount:(unsigned)arg4;
-(void)dealloc;
@end