/*
 * This header is generated by weak_classdump 0.2
 * on Saturday, October 18, 2014 at 2:24:37 AM Eastern Daylight Time
 * Operating System: Version 7.1.1 (Build 11D201)
 * weak_classdump is Freeware by Elias Limneos.
 *
 */


@interface BITPLCrashReportProcessorInfo : NSObject {
	int _typeEncoding; 
	unsigned long long _type; 
	unsigned long long _subtype; 
}
@property (nonatomic,copy) int typeEncoding; 				//@synthesize typeEncoding=_typeEncoding - In the implementation block
@property (nonatomic,copy) unsigned long long type; 				//@synthesize type=_type - In the implementation block
@property (nonatomic,copy) unsigned long long subtype; 				//@synthesize subtype=_subtype - In the implementation block
-(id)initWithTypeEncoding:(int)arg1 type:(unsigned long long)arg2 subtype:(unsigned long long)arg3;
@end