/*
 * This header is generated by weak_classdump 0.2
 * on Saturday, October 18, 2014 at 2:24:38 AM Eastern Daylight Time
 * Operating System: Version 7.1.1 (Build 11D201)
 * weak_classdump is Freeware by Elias Limneos.
 *
 */


@interface BITPLCrashReportSignalInfo : NSObject {
	NSString* _name; 
	NSString* _code; 
	unsigned long long _address; 
}
@property (nonatomic,copy) NSString* name; 				//@synthesize name=_name - In the implementation block
@property (nonatomic,copy) NSString* code; 				//@synthesize code=_code - In the implementation block
@property (nonatomic,copy) unsigned long long address; 				//@synthesize address=_address - In the implementation block
-(id)initWithSignalName:(id)arg1 code:(id)arg2 address:(unsigned long long)arg3;
-(void)dealloc;
@end