/*
 * This header is generated by weak_classdump 0.2
 * on Saturday, October 18, 2014 at 2:24:41 AM Eastern Daylight Time
 * Operating System: Version 7.1.1 (Build 11D201)
 * weak_classdump is Freeware by Elias Limneos.
 *
 */


@interface BITPLCrashSignalHandler : NSObject {
	struct __darwin_sigaltstack _sigstk; 
}
+(id)sharedHandler;
+(void)resetHandlers;
+(void)initialize;
-(BOOL)registerHandlerWithSignal:(int)arg1 error:(id*)arg2;
-(BOOL)registerHandlerForSignal:(int)arg1 callback:(?*)arg2 context:(void*)arg3 error:(id*)arg4;
-(id)init;
-(id).cxx_construct;
@end