/*
 * This header is generated by weak_classdump 0.2
 * on Saturday, October 18, 2014 at 2:24:34 AM Eastern Daylight Time
 * Operating System: Version 7.1.1 (Build 11D201)
 * weak_classdump is Freeware by Elias Limneos.
 *
 */


@interface BITPLCrashMachExceptionPort : NSObject {
	unsigned _mask; 
	unsigned _port; 
	int _behavior; 
	int _flavor; 
}
@property (nonatomic,copy) unsigned server_port; 				//@synthesize port=_port - In the implementation block
@property (nonatomic,copy) unsigned mask; 				//@synthesize mask=_mask - In the implementation block
@property (nonatomic,copy) int behavior; 				//@synthesize behavior=_behavior - In the implementation block
@property (nonatomic,copy) int flavor; 				//@synthesize flavor=_flavor - In the implementation block
+(id)exceptionPortsForTask:(unsigned)arg1 mask:(unsigned)arg2 error:(id*)arg3;
+(id)exceptionPortsForThread:(unsigned)arg1 mask:(unsigned)arg2 error:(id*)arg3;
-(BOOL)registerForTask:(unsigned)arg1 previousPortSet:(id*)arg2 error:(id*)arg3;
-(id)initWithServerPort:(unsigned)arg1 mask:(unsigned)arg2 behavior:(int)arg3 flavor:(int)arg4;
-(BOOL)registerForThread:(unsigned)arg1 previousPortSet:(id*)arg2 error:(id*)arg3;
-(void)dealloc;
@end