/*
 * This header is generated by weak_classdump 0.2
 * on Saturday, October 18, 2014 at 2:24:36 AM Eastern Daylight Time
 * Operating System: Version 7.1.1 (Build 11D201)
 * weak_classdump is Freeware by Elias Limneos.
 *
 */


@interface BITPLCrashMachExceptionServer : NSObject {
	struct plcrash_exception_server_context* _serverContext; 
}
@property (nonatomic,copy) unsigned serverThread; 
-(id)initWithCallBack:(?*)arg1 context:(void*)arg2 error:(id*)arg3;
-(id)exceptionPortWithMask:(unsigned)arg1 error:(id*)arg2;
-(unsigned)copySendRightForServerAndReturningError:(id*)arg1;
-(void)dealloc;
@end