/*
 * This header is generated by weak_classdump 0.2
 * on Saturday, October 18, 2014 at 2:24:38 AM Eastern Daylight Time
 * Operating System: Version 7.1.1 (Build 11D201)
 * weak_classdump is Freeware by Elias Limneos.
 *
 */


@interface BITPLCrashReportBinaryImageInfo : NSObject {
	BITPLCrashReportProcessorInfo* _processorInfo; 
	unsigned long long _baseAddress; 
	unsigned long long _imageSize; 
	NSString* _imageName; 
	BOOL _hasImageUUID; 
	NSString* _imageUUID; 
}
@property (nonatomic,copy) BITPLCrashReportProcessorInfo* codeType; 				//@synthesize processorInfo=_processorInfo - In the implementation block
@property (nonatomic,copy) unsigned long long imageBaseAddress; 				//@synthesize baseAddress=_baseAddress - In the implementation block
@property (nonatomic,copy) unsigned long long imageSize; 				//@synthesize imageSize=_imageSize - In the implementation block
@property (nonatomic,copy) NSString* imageName; 				//@synthesize imageName=_imageName - In the implementation block
@property (nonatomic,copy) BOOL hasImageUUID; 				//@synthesize hasImageUUID=_hasImageUUID - In the implementation block
@property (nonatomic,copy) NSString* imageUUID; 				//@synthesize imageUUID=_imageUUID - In the implementation block
-(id)initWithCodeType:(id)arg1 baseAddress:(unsigned long long)arg2 size:(unsigned long long)arg3 name:(id)arg4 uuid:(id)arg5;
-(void)dealloc;
@end