/*
 * This header is generated by weak_classdump 0.2
 * on Saturday, October 18, 2014 at 2:24:36 AM Eastern Daylight Time
 * Operating System: Version 7.1.1 (Build 11D201)
 * weak_classdump is Freeware by Elias Limneos.
 *
 */


@interface BITPLCrashReportRegisterInfo : NSObject {
	NSString* _registerName; 
	unsigned long long _registerValue; 
}
@property (nonatomic,copy) NSString* registerName; 				//@synthesize registerName=_registerName - In the implementation block
@property (nonatomic,copy) unsigned long long registerValue; 				//@synthesize registerValue=_registerValue - In the implementation block
-(id)initWithRegisterName:(id)arg1 registerValue:(unsigned long long)arg2;
-(void)dealloc;
@end