/*
 * This header is generated by weak_classdump 0.2
 * on Saturday, October 18, 2014 at 2:24:39 AM Eastern Daylight Time
 * Operating System: Version 7.1.1 (Build 11D201)
 * weak_classdump is Freeware by Elias Limneos.
 *
 */


@interface BITPLCrashReportExceptionInfo : NSObject {
	NSString* _name; 
	NSString* _reason; 
	NSArray* _stackFrames; 
}
@property (nonatomic,copy) NSString* exceptionName; 				//@synthesize name=_name - In the implementation block
@property (nonatomic,copy) NSString* exceptionReason; 				//@synthesize reason=_reason - In the implementation block
@property (nonatomic,copy) NSArray* stackFrames; 				//@synthesize stackFrames=_stackFrames - In the implementation block
-(id)initWithExceptionName:(id)arg1 reason:(id)arg2;
-(id)initWithExceptionName:(id)arg1 reason:(id)arg2 stackFrames:(id)arg3;
-(void)dealloc;
@end