/*
 * This header is generated by weak_classdump 0.2
 * on Saturday, October 18, 2014 at 2:28:05 AM Eastern Daylight Time
 * Operating System: Version 7.1.1 (Build 11D201)
 * weak_classdump is Freeware by Elias Limneos.
 *
 */


@interface BITStoreButton : UIButton {
	CALayer* _defaultBorderLayer; 
	CALayer* _inActiveBorderLayer; 
	id<BITStoreButtonDelegate> _buttonDelegate; 
	BITStoreButtonData* _buttonData; 
	unsigned _style; 
	CGPoint _customPadding; 
}
@property (assign,nonatomic,__weak) id<BITStoreButtonDelegate> buttonDelegate; 				//@synthesize buttonDelegate=_buttonDelegate - In the implementation block
@property (nonatomic,retain) BITStoreButtonData* buttonData; 				//@synthesize buttonData=_buttonData - In the implementation block
@property (assign,nonatomic) CGPoint customPadding; 				//@synthesize customPadding=_customPadding - In the implementation block
@property (assign,nonatomic) unsigned style; 				//@synthesize style=_style - In the implementation block
-(void)updateButtonAnimated:(BOOL)arg1;
-(void)setCustomPadding:(CGPoint)arg1;
-(id)initWithPadding:(CGPoint)arg1 style:(unsigned)arg2;
-(void)setButtonDelegate:(id)arg1;
-(void)setButtonData:(id)arg1;
-(void)alignToSuperview;
-(void)setButtonData:(id)arg1 animated:(BOOL)arg2;
-(id)initWithFrame:(CGRect)arg1;
-(void)setFrame:(CGRect)arg1;
-(CGSize)sizeThatFits:(CGSize)arg1;
-(void)setStyle:(unsigned)arg1;
-(void)animationDidStop:(id)arg1 finished:(id)arg2 context:(void*)arg3;
-(void)buttonPressed:(id)arg1;
-(void).cxx_destruct;
@end