/*
 * This header is generated by weak_classdump 0.2
 * on Saturday, October 18, 2014 at 2:28:05 AM Eastern Daylight Time
 * Operating System: Version 7.1.1 (Build 11D201)
 * weak_classdump is Freeware by Elias Limneos.
 *
 */


@interface BITStoreButtonData : NSObject {
	BOOL _enabled; 
	NSString* _label; 
}
@property (nonatomic,copy) NSString* label; 				//@synthesize label=_label - In the implementation block
@property (assign,getter=isEnabled,nonatomic) BOOL enabled; 				//@synthesize enabled=_enabled - In the implementation block
+(id)dataWithLabel:(id)arg1 enabled:(BOOL)arg2;
-(id)initWithLabel:(id)arg1 enabled:(BOOL)arg2;
-(void)setEnabled:(BOOL)arg1;
-(void)setLabel:(id)arg1;
-(void).cxx_destruct;
@end