/*
 * This header is generated by weak_classdump 0.2
 * on Saturday, October 18, 2014 at 2:28:02 AM Eastern Daylight Time
 * Operating System: Version 7.1.1 (Build 11D201)
 * weak_classdump is Freeware by Elias Limneos.
 *
 */

#import <BITStoreButtonDelegate.h>

@interface BITUpdateViewController : BITHockeyBaseViewController <BITStoreButtonDelegate> {
	BOOL _kvoRegistered; 
	BOOL _showAllVersions; 
	BITAppStoreHeader* _appStoreHeader; 
	BITStoreButton* _appStoreButton; 
	id _popOverController; 
	NSMutableArray* _cells; 
	BOOL _isAppStoreEnvironment; 
	BOOL _mandatoryUpdate; 
	BITUpdateManager* _updateManager; 
	unsigned _appStoreButtonState; 
}
@property (assign,nonatomic,__weak) BITUpdateManager* updateManager; 				//@synthesize updateManager=_updateManager - In the implementation block
@property (assign,nonatomic) BOOL mandatoryUpdate; 				//@synthesize mandatoryUpdate=_mandatoryUpdate - In the implementation block
@property (assign,nonatomic) unsigned appStoreButtonState; 				//@synthesize appStoreButtonState=_appStoreButtonState - In the implementation block
-(void)setAppStoreButtonState:(unsigned)arg1 animated:(BOOL)arg2;
-(void)restoreStoreButtonStateAnimated:(BOOL)arg1;
-(void)showPreviousVersionAction;
-(void)realignPreviousVersionButton;
-(void)appDidBecomeActive;
-(void)updateAppStoreHeader;
-(id)addGlossToImage:(id)arg1;
-(void)setAppStoreButtonState:(unsigned)arg1;
-(void)redrawTableView;
-(void)configureWebCell:(id)arg1 forAppVersion:(id)arg2;
-(void)showHidePreviousVersionsButton;
-(void)storeButtonFired:(id)arg1;
-(void)changePreviousVersionButtonBackground:(id)arg1;
-(void)changePreviousVersionButtonBackgroundHighlighted:(id)arg1;
-(void)setUpdateManager:(id)arg1;
-(void)setMandatoryUpdate:(BOOL)arg1;
-(void)dealloc;
-(id)backgroundColor;
-(float)tableView:(id)arg1 heightForRowAtIndexPath:(id)arg2;
-(int)tableView:(id)arg1 numberOfRowsInSection:(int)arg2;
-(id)tableView:(id)arg1 cellForRowAtIndexPath:(id)arg2;
-(int)numberOfSectionsInTableView:(id)arg1;
-(id)initWithStyle:(int)arg1;
-(void)viewWillAppear:(BOOL)arg1;
-(void)viewDidLoad;
-(void)viewWillDisappear:(BOOL)arg1;
-(void)willAnimateRotationToInterfaceOrientation:(int)arg1 duration:(double)arg2;
-(void)observeValueForKeyPath:(id)arg1 ofObject:(id)arg2 change:(id)arg3 context:(void*)arg4;
-(void).cxx_destruct;
@end