/*
 * This header is generated by weak_classdump 0.2
 * on Saturday, October 18, 2014 at 2:27:50 AM Eastern Daylight Time
 * Operating System: Version 7.1.1 (Build 11D201)
 * weak_classdump is Freeware by Elias Limneos.
 *
 */


@interface CPTAnimationPeriod : NSObject {
	NSValue* startValue; 
	NSValue* endValue; 
	float duration; 
	float delay; 
	float startOffset; 
}
@property (nonatomic,copy) NSValue* startValue; 
@property (nonatomic,copy) NSValue* endValue; 
@property (assign,nonatomic) float duration; 
@property (assign,nonatomic) float delay; 
@property (assign,nonatomic) float startOffset; 
+(id)periodWithStartValue:(id)arg1 endValue:(id)arg2 duration:(float)arg3 withDelay:(float)arg4;
+(id)periodWithStart:(float)arg1 end:(float)arg2 duration:(float)arg3 withDelay:(float)arg4;
+(id)periodWithStartPoint:(CGPoint)arg1 endPoint:(CGPoint)arg2 duration:(float)arg3 withDelay:(float)arg4;
+(id)periodWithStartSize:(CGSize)arg1 endSize:(CGSize)arg2 duration:(float)arg3 withDelay:(float)arg4;
+(id)periodWithStartRect:(CGRect)arg1 endRect:(CGRect)arg2 duration:(float)arg3 withDelay:(float)arg4;
+(id)periodWithStartDecimal:(=bbbbbS[=8411188])arg1 endDecimal:(=bbbbbS[=8411188])arg2 duration:(float)arg3 withDelay:(float)arg4;
+(id)periodWithStartPlotRange:(id)arg1 endPlotRange:(id)arg2 duration:(float)arg3 withDelay:(float)arg4;
-(id)tweenedValueForProgress:(float)arg1;
-(id)initWithStartValue:(id)arg1 endValue:(id)arg2 duration:(float)arg3 withDelay:(float)arg4;
-(id)initWithStart:(float)arg1 end:(float)arg2 duration:(float)arg3 withDelay:(float)arg4;
-(id)initWithStartPoint:(CGPoint)arg1 endPoint:(CGPoint)arg2 duration:(float)arg3 withDelay:(float)arg4;
-(id)initWithStartSize:(CGSize)arg1 endSize:(CGSize)arg2 duration:(float)arg3 withDelay:(float)arg4;
-(id)initWithStartRect:(CGRect)arg1 endRect:(CGRect)arg2 duration:(float)arg3 withDelay:(float)arg4;
-(id)initWithStartDecimal:(=bbbbbS[=8411188])arg1 endDecimal:(=bbbbbS[=8411188])arg2 duration:(float)arg3 withDelay:(float)arg4;
-(id)initWithStartPlotRange:(id)arg1 endPlotRange:(id)arg2 duration:(float)arg3 withDelay:(float)arg4;
-(void)dealloc;
-(id)init;
-(id)description;
-(void)setDuration:(float)arg1;
-(void)setDelay:(float)arg1;
-(void)setStartValue:(id)arg1;
-(void)setEndValue:(id)arg1;
-(void)setStartOffset:(float)arg1;
@end