/*
 * This header is generated by weak_classdump 0.2
 * on Saturday, October 18, 2014 at 2:27:45 AM Eastern Daylight Time
 * Operating System: Version 7.1.1 (Build 11D201)
 * weak_classdump is Freeware by Elias Limneos.
 *
 */


@interface CPTAxisSet : CPTLayer {
	NSArray* axes; 
	CPTLineStyle* borderLineStyle; 
}
@property (nonatomic,retain) NSArray* axes; 
@property (nonatomic,copy) CPTLineStyle* borderLineStyle; 
-(void)setBorderLineStyle:(id)arg1;
-(void)relabelAxes;
-(id)axisForCoordinate:(int)arg1 atIndex:(unsigned)arg2;
-(void)setAxes:(id)arg1;
-(BOOL)pointingDeviceDownEvent:(struct UIEvent*)arg1 atPoint:(CGPoint)arg2;
-(id)initWithFrame:(CGRect)arg1;
-(void)dealloc;
-(id)initWithCoder:(id)arg1;
-(void)encodeWithCoder:(id)arg1;
-(id)initWithLayer:(id)arg1;
@end