/*
 * This header is generated by weak_classdump 0.2
 * on Saturday, October 18, 2014 at 2:27:50 AM Eastern Daylight Time
 * Operating System: Version 7.1.1 (Build 11D201)
 * weak_classdump is Freeware by Elias Limneos.
 *
 */


@interface CPTAnnotationHostLayer : CPTLayer {
	NSMutableArray* mutableAnnotations; 
}
@property (nonatomic,@dynamic,retain,copy) NSArray* annotations; 
@property (nonatomic,retain) NSMutableArray* mutableAnnotations; 
-(void)setMutableAnnotations:(id)arg1;
-(id)sublayersExcludedFromAutomaticLayout;
-(id)initWithFrame:(CGRect)arg1;
-(void)dealloc;
-(id)initWithCoder:(id)arg1;
-(void)encodeWithCoder:(id)arg1;
-(id)initWithLayer:(id)arg1;
-(void)removeAllAnnotations;
-(void)addAnnotation:(id)arg1;
-(void)removeAnnotation:(id)arg1;
-(void)layoutSublayers;
@end