/*
 * This header is generated by weak_classdump 0.2
 * on Saturday, October 18, 2014 at 2:27:51 AM Eastern Daylight Time
 * Operating System: Version 7.1.1 (Build 11D201)
 * weak_classdump is Freeware by Elias Limneos.
 *
 */

#import <NSCoding.h>

@interface CPTAnnotation : NSObject <NSCoding> {
	CPTAnnotationHostLayer* annotationHostLayer; 
	CPTLayer* contentLayer; 
	CGPoint contentAnchorPoint; 
	CGPoint displacement; 
	float rotation; 
}
@property (nonatomic,retain) CPTLayer* contentLayer; 
@property (assign,nonatomic,__weak) CPTAnnotationHostLayer* annotationHostLayer; 
@property (assign,nonatomic) CGPoint contentAnchorPoint; 
@property (assign,nonatomic) CGPoint displacement; 
@property (assign,nonatomic) float rotation; 
-(void)setAnnotationHostLayer:(id)arg1;
-(void)setContentLayer:(id)arg1;
-(void)setDisplacement:(CGPoint)arg1;
-(void)setContentAnchorPoint:(CGPoint)arg1;
-(void)positionContentLayer;
-(void)dealloc;
-(id)initWithCoder:(id)arg1;
-(void)encodeWithCoder:(id)arg1;
-(id)init;
-(id)description;
-(void)setRotation:(float)arg1;
@end