/*
 * This header is generated by weak_classdump 0.2
 * on Saturday, October 18, 2014 at 2:27:51 AM Eastern Daylight Time
 * Operating System: Version 7.1.1 (Build 11D201)
 * weak_classdump is Freeware by Elias Limneos.
 *
 */


@interface CPTAnimationOperation : NSObject {
	CPTAnimationPeriod* period; 
	int animationCurve; 
	id boundObject; 
	SEL boundGetter; 
	SEL boundSetter; 
	NSObject<CPTAnimationDelegate>* delegate; 
}
@property (nonatomic,retain) CPTAnimationPeriod* period; 
@property (assign,nonatomic) int animationCurve; 
@property (nonatomic,retain) id boundObject; 
@property (assign,nonatomic) SEL boundGetter; 
@property (assign,nonatomic) SEL boundSetter; 
@property (assign,nonatomic,__weak) NSObject<CPTAnimationDelegate>* delegate; 
-(void)setBoundObject:(id)arg1;
-(void)setBoundGetter:(SEL)arg1;
-(void)setBoundSetter:(SEL)arg1;
-(void)dealloc;
-(void)setDelegate:(id)arg1;
-(id)init;
-(id)description;
-(void)setAnimationCurve:(int)arg1;
-(void)setPeriod:(id)arg1;
@end