/*
 * This header is generated by weak_classdump 0.2
 * on Saturday, October 18, 2014 at 2:27:44 AM Eastern Daylight Time
 * Operating System: Version 7.1.1 (Build 11D201)
 * weak_classdump is Freeware by Elias Limneos.
 *
 */


@interface CPTBorderedLayer : CPTAnnotationHostLayer {
	CPTLineStyle* borderLineStyle; 
	CPTFill* fill; 
	BOOL inLayout; 
}
@property (nonatomic,copy) CPTLineStyle* borderLineStyle; 
@property (nonatomic,copy) CPTFill* fill; 
@property (assign,nonatomic) BOOL inLayout; 
@property (nonatomic,@dynamic,retain,copy) CPTLayer* borderLayer; 
-(void)setBorderLineStyle:(id)arg1;
-(void)setMasksToBorder:(BOOL)arg1;
-(void)renderAsVectorInContext:(struct CGContext*)arg1;
-(void)renderBorderedLayerAsVectorInContext:(struct CGContext*)arg1;
-(void)sublayerMarginLeft:(float*)arg1 top:(float*)arg2 right:(float*)arg3 bottom:(float*)arg4;
-(void)updateOpacity;
-(void)setInLayout:(BOOL)arg1;
-(struct CGPath*)maskingPath;
-(struct CGPath*)sublayerMaskingPath;
-(id)initWithFrame:(CGRect)arg1;
-(void)dealloc;
-(id)initWithCoder:(id)arg1;
-(void)encodeWithCoder:(id)arg1;
-(void)setHidden:(BOOL)arg1;
-(void)setBounds:(CGRect)arg1;
-(void)setPosition:(CGPoint)arg1;
-(void)setTransform:(struct CATransform3D)arg1;
-(void)setCornerRadius:(float)arg1;
-(void)removeFromSuperlayer;
-(void)setAnchorPoint:(CGPoint)arg1;
-(id)initWithLayer:(id)arg1;
-(void)setShadow:(id)arg1;
-(void)setFill:(id)arg1;
-(void)layoutSublayers;
@end