/*
 * This header is generated by weak_classdump 0.2
 * on Saturday, October 18, 2014 at 2:25:01 AM Eastern Daylight Time
 * Operating System: Version 7.1.1 (Build 11D201)
 * weak_classdump is Freeware by Elias Limneos.
 *
 */


@protocol CPTBarPlotDataSource
@optional
-(id)barFillsForBarPlot(id):arg1 recordIndexRange({):arg2 ;
-(id)barFillForBarPlot(id):arg1 recordIndex(unsigned):arg2 ;
-(id)barLineStylesForBarPlot(id):arg1 recordIndexRange({):arg2 ;
-(id)barLineStyleForBarPlot(id):arg1 recordIndex(unsigned):arg2 ;
-(id)legendTitleForBarPlot(id):arg1 recordIndex(unsigned):arg2 ;
-(id)attributedLegendTitleForBarPlot(id):arg1 recordIndex(unsigned):arg2 ;
@end
