/*
 * This header is generated by weak_classdump 0.2
 * on Saturday, October 18, 2014 at 2:24:39 AM Eastern Daylight Time
 * Operating System: Version 7.1.1 (Build 11D201)
 * weak_classdump is Freeware by Elias Limneos.
 *
 */


@interface CPTBorderLayer : CPTLayer {
	CPTBorderedLayer* maskedLayer; 
}
@property (nonatomic,retain) CPTBorderedLayer* maskedLayer; 
-(void)renderAsVectorInContext:(struct CGContext*)arg1;
-(void)setMaskedLayer:(id)arg1;
-(id)sublayersExcludedFromAutomaticLayout;
-(id)initWithFrame:(CGRect)arg1;
-(void)dealloc;
-(id)initWithCoder:(id)arg1;
-(void)encodeWithCoder:(id)arg1;
-(void)setBounds:(CGRect)arg1;
-(id)initWithLayer:(id)arg1;
-(void)layoutSublayers;
@end