/*
 * This header is generated by weak_classdump 0.2
 * on Saturday, October 18, 2014 at 2:27:41 AM Eastern Daylight Time
 * Operating System: Version 7.1.1 (Build 11D201)
 * weak_classdump is Freeware by Elias Limneos.
 *
 */

#import <NSCoding.h>

@interface CPTColorSpace : NSObject <NSCoding> {
	struct CGColorSpace* cgColorSpace; 
}
@property (assign,nonatomic) struct CGColorSpace* cgColorSpace; 
+(id)genericRGBSpace;
-(id)initWithCGColorSpace:(struct CGColorSpace*)arg1;
-(void)setCGColorSpace:(struct CGColorSpace*)arg1;
-(void)setCgColorSpace:(struct CGColorSpace*)arg1;
-(void)dealloc;
-(id)initWithCoder:(id)arg1;
-(void)encodeWithCoder:(id)arg1;
-(void)finalize;
@end