/*
 * This header is generated by weak_classdump 0.2
 * on Saturday, October 18, 2014 at 2:25:10 AM Eastern Daylight Time
 * Operating System: Version 7.1.1 (Build 11D201)
 * weak_classdump is Freeware by Elias Limneos.
 *
 */

#import <CPTPlotDataSource.h>

@interface CPTFunctionDataSource : NSObject <CPTPlotDataSource> {
	CPTPlot* dataPlot; 
	?* dataSourceFunction; 
	float resolution; 
	double cachedStep; 
	unsigned dataCount; 
	unsigned cachedCount; 
	CPTMutablePlotRange* cachedPlotRange; 
	CPTPlotRange* dataRange; 
}
@property (nonatomic,copy) ?* dataSourceFunction; 
@property (nonatomic,copy) CPTPlot* dataPlot; 
@property (assign,nonatomic) float resolution; 
@property (nonatomic,retain) CPTPlotRange* dataRange; 
@property (assign,nonatomic) double cachedStep; 
@property (assign,nonatomic) unsigned dataCount; 
@property (assign,nonatomic) unsigned cachedCount; 
@property (nonatomic,retain) CPTMutablePlotRange* cachedPlotRange; 
+(id)dataSourceForPlot:(id)arg1 withFunction:(?*)arg2;
-(unsigned)numberOfRecordsForPlot:(id)arg1;
-(id)dataForPlot:(id)arg1 recordIndexRange:(struct _NSRange)arg2;
-(id)initForPlot:(id)arg1 withFunction:(?*)arg2;
-(void)plotBoundsChanged;
-(void)setCachedPlotRange:(id)arg1;
-(void)setDataCount:(unsigned)arg1;
-(void)setCachedStep:(double)arg1;
-(void)plotSpaceChanged;
-(void)setDataRange:(id)arg1;
-(void)dealloc;
-(id)init;
-(void)observeValueForKeyPath:(id)arg1 ofObject:(id)arg2 change:(id)arg3 context:(void*)arg4;
-(void)setCachedCount:(unsigned)arg1;
-(void)setResolution:(float)arg1;
@end