/*
 * This header is generated by weak_classdump 0.2
 * on Saturday, October 18, 2014 at 2:25:17 AM Eastern Daylight Time
 * Operating System: Version 7.1.1 (Build 11D201)
 * weak_classdump is Freeware by Elias Limneos.
 *
 */

#import <NSCopying.h>
#import <NSCoding.h>

@interface CPTFill : NSObject <NSCopying, NSCoding> {
}
@property (getter=isOpaque,nonatomic,@dynamic,copy) BOOL opaque; 
+(id)fillWithGradient:(id)arg1;
+(id)fillWithColor:(id)arg1;
+(id)fillWithImage:(id)arg1;
-(void)fillPathInContext:(struct CGContext*)arg1;
-(id)initWithCoder:(id)arg1;
-(void)encodeWithCoder:(id)arg1;
-(id)initWithImage:(id)arg1;
-(id)copyWithZone:(NSZone*)arg1;
-(void)fillRect:(CGRect)arg1 inContext:(struct CGContext*)arg2;
-(id)initWithColor:(id)arg1;
-(id)initWithGradient:(id)arg1;
@end