/*
 * This header is generated by weak_classdump 0.2
 * on Saturday, October 18, 2014 at 2:25:08 AM Eastern Daylight Time
 * Operating System: Version 7.1.1 (Build 11D201)
 * weak_classdump is Freeware by Elias Limneos.
 *
 */


@interface CPTGraphHostingView : UIView {
	CPTGraph* hostedGraph; 
	BOOL collapsesLayers; 
	BOOL allowPinchScaling; 
	UIPinchGestureRecognizer* pinchGestureRecognizer; 
}
@property (nonatomic,retain) CPTGraph* hostedGraph; 
@property (assign,nonatomic) BOOL collapsesLayers; 
@property (assign,nonatomic) BOOL allowPinchScaling; 
@property (assign,nonatomic,__weak) UIPinchGestureRecognizer* pinchGestureRecognizer; 
+(Class)layerClass;
-(void)setHostedGraph:(id)arg1;
-(void)setAllowPinchScaling:(BOOL)arg1;
-(void)handlePinchGesture:(id)arg1;
-(void)graphNeedsRedraw:(id)arg1;
-(void)updateNotifications;
-(void)setCollapsesLayers:(BOOL)arg1;
-(void)setPinchGestureRecognizer:(id)arg1;
-(id)initWithFrame:(CGRect)arg1;
-(void)dealloc;
-(void)drawRect:(CGRect)arg1;
-(id)initWithCoder:(id)arg1;
-(void)encodeWithCoder:(id)arg1;
-(void)setFrame:(CGRect)arg1;
-(void)setBounds:(CGRect)arg1;
-(void)touchesCancelled:(id)arg1 withEvent:(id)arg2;
-(void)touchesBegan:(id)arg1 withEvent:(id)arg2;
-(void)touchesMoved:(id)arg1 withEvent:(id)arg2;
-(void)touchesEnded:(id)arg1 withEvent:(id)arg2;
-(void)commonInit;
@end