/*
 * This header is generated by weak_classdump 0.2
 * on Saturday, October 18, 2014 at 2:25:08 AM Eastern Daylight Time
 * Operating System: Version 7.1.1 (Build 11D201)
 * weak_classdump is Freeware by Elias Limneos.
 *
 */


@interface CPTGridLineGroup : CPTLayer {
	CPTPlotArea* plotArea; 
	BOOL major; 
}
@property (assign,nonatomic,__weak) CPTPlotArea* plotArea; 
@property (assign,nonatomic) BOOL major; 
-(void)renderAsVectorInContext:(struct CGContext*)arg1;
-(id)initWithFrame:(CGRect)arg1;
-(id)initWithCoder:(id)arg1;
-(void)encodeWithCoder:(id)arg1;
-(id)initWithLayer:(id)arg1;
-(void)setPlotArea:(id)arg1;
-(void)setMajor:(BOOL)arg1;
@end