/*
 * This header is generated by weak_classdump 0.2
 * on Saturday, October 18, 2014 at 2:25:02 AM Eastern Daylight Time
 * Operating System: Version 7.1.1 (Build 11D201)
 * weak_classdump is Freeware by Elias Limneos.
 *
 */

#import <NSCoding.h>
#import <NSCopying.h>

@interface CPTLimitBand : NSObject <NSCoding, NSCopying> {
	CPTPlotRange* range; 
	CPTFill* fill; 
}
@property (nonatomic,retain) CPTPlotRange* range; 
@property (nonatomic,retain) CPTFill* fill; 
+(id)limitBandWithRange:(id)arg1 fill:(id)arg2;
-(id)initWithRange:(id)arg1 fill:(id)arg2;
-(void)dealloc;
-(id)initWithCoder:(id)arg1;
-(void)encodeWithCoder:(id)arg1;
-(id)description;
-(id)copyWithZone:(NSZone*)arg1;
-(void)setRange:(id)arg1;
-(void)setFill:(id)arg1;
@end