/*
 * This header is generated by weak_classdump 0.2
 * on Saturday, October 18, 2014 at 2:25:04 AM Eastern Daylight Time
 * Operating System: Version 7.1.1 (Build 11D201)
 * weak_classdump is Freeware by Elias Limneos.
 *
 */


@interface CPTLayerAnnotation : CPTAnnotation {
	CPTLayer* anchorLayer; 
	CPTConstraints* xConstraints; 
	CPTConstraints* yConstraints; 
	int rectAnchor; 
}
@property (nonatomic,copy) CPTLayer* anchorLayer; 
@property (assign,nonatomic) int rectAnchor; 
@property (nonatomic,retain) CPTConstraints* xConstraints; 
@property (nonatomic,retain) CPTConstraints* yConstraints; 
-(id)initWithAnchorLayer:(id)arg1;
-(void)setRectAnchor:(int)arg1;
-(void)setConstraints;
-(void)setXConstraints:(id)arg1;
-(void)setYConstraints:(id)arg1;
-(void)positionContentLayer;
-(void)dealloc;
-(id)initWithCoder:(id)arg1;
-(void)encodeWithCoder:(id)arg1;
-(id)init;
@end