/*
 * This header is generated by weak_classdump 0.2
 * on Saturday, October 18, 2014 at 2:25:00 AM Eastern Daylight Time
 * Operating System: Version 7.1.1 (Build 11D201)
 * weak_classdump is Freeware by Elias Limneos.
 *
 */


@interface CPTMutableTextStyle : CPTTextStyle {
}
@property (nonatomic,@dynamic,copy) NSString* fontName; 
@property (assign,nonatomic,@dynamic) float fontSize; 
@property (nonatomic,@dynamic,copy) CPTColor* color; 
@property (assign,nonatomic,@dynamic) int textAlignment; 
@property (assign,nonatomic,@dynamic) int lineBreakMode; 
+(id)textStyleWithAttributes:(id)arg1;
@end