/*
 * This header is generated by weak_classdump 0.2
 * on Saturday, October 18, 2014 at 2:25:01 AM Eastern Daylight Time
 * Operating System: Version 7.1.1 (Build 11D201)
 * weak_classdump is Freeware by Elias Limneos.
 *
 */


@interface CPTMutableLineStyle : CPTLineStyle {
}
@property (assign,nonatomic,@dynamic) int lineCap; 
@property (assign,nonatomic,@dynamic) int lineJoin; 
@property (assign,nonatomic,@dynamic) float miterLimit; 
@property (assign,nonatomic,@dynamic) float lineWidth; 
@property (nonatomic,@dynamic,retain) NSArray* dashPattern; 
@property (assign,nonatomic,@dynamic) float patternPhase; 
@property (nonatomic,@dynamic,retain) CPTColor* lineColor; 
@property (nonatomic,@dynamic,retain) CPTFill* lineFill; 
@property (nonatomic,@dynamic,retain) CPTGradient* lineGradient; 
@end