/*
 * This header is generated by weak_classdump 0.2
 * on Saturday, October 18, 2014 at 2:24:57 AM Eastern Daylight Time
 * Operating System: Version 7.1.1 (Build 11D201)
 * weak_classdump is Freeware by Elias Limneos.
 *
 */

#import <NSCopying.h>
#import <NSMutableCopying.h>
#import <NSCoding.h>

@interface CPTNumericData : NSObject <NSCopying, NSMutableCopying, NSCoding> {
	NSData* data; 
	struct _CPTNumericDataType dataType; 
	NSArray* shape; 
	int dataOrder; 
}
@property (copy,copy) NSData* data; 
@property (@dynamic,copy) const void** bytes; 
@property (@dynamic,copy) unsigned length; 
@property (copy) struct _CPTNumericDataType dataType; 
@property (@dynamic,copy) int dataTypeFormat; 
@property (@dynamic,copy) unsigned long sampleBytes; 
@property (@dynamic,copy) long byteOrder; 
@property (copy,copy) NSArray* shape; 
@property (@dynamic,copy) unsigned numberOfDimensions; 
@property (@dynamic,copy) unsigned numberOfSamples; 
@property (copy) int dataOrder; 
+(id)numericDataWithData:(id)arg1 dataType:(struct _CPTNumericDataType)arg2 shape:(id)arg3 dataOrder:(int)arg4;
+(id)numericDataWithData:(id)arg1 dataTypeString:(id)arg2 shape:(id)arg3;
+(id)numericDataWithArray:(id)arg1 dataType:(struct _CPTNumericDataType)arg2 shape:(id)arg3;
+(id)numericDataWithArray:(id)arg1 dataTypeString:(id)arg2 shape:(id)arg3;
+(id)numericDataWithData:(id)arg1 dataTypeString:(id)arg2 shape:(id)arg3 dataOrder:(int)arg4;
+(id)numericDataWithArray:(id)arg1 dataType:(struct _CPTNumericDataType)arg2 shape:(id)arg3 dataOrder:(int)arg4;
+(id)numericDataWithArray:(id)arg1 dataTypeString:(id)arg2 shape:(id)arg3 dataOrder:(int)arg4;
+(id)numericDataWithData:(id)arg1 dataType:(struct _CPTNumericDataType)arg2 shape:(id)arg3;
-(id)initWithData:(id)arg1 dataType:(struct _CPTNumericDataType)arg2 shape:(id)arg3;
-(id)sampleArray;
-(void)convertData:(id)arg1 dataType:(struct _CPTNumericDataType*)arg2 toData:(id)arg3 dataType:(struct _CPTNumericDataType*)arg4;
-(id)dataByConvertingToDataType:(struct _CPTNumericDataType)arg1;
-(id)dataByConvertingToType:(int)arg1 sampleBytes:(unsigned long)arg2 byteOrder:(long)arg3;
-(id)initWithData:(id)arg1 dataType:(struct _CPTNumericDataType)arg2 shape:(id)arg3 dataOrder:(int)arg4;
-(id)initWithArray:(id)arg1 dataType:(struct _CPTNumericDataType)arg2 shape:(id)arg3 dataOrder:(int)arg4;
-(void)commonInitWithData:(id)arg1 dataType:(struct _CPTNumericDataType)arg2 shape:(id)arg3 dataOrder:(int)arg4;
-(id)dataFromArray:(id)arg1 dataType:(struct _CPTNumericDataType)arg2;
-(unsigned)sampleIndex:(unsigned)arg1 indexList:(void*)arg2;
-(void)swapByteOrderForData:(id)arg1 sampleSize:(unsigned long)arg2;
-(id)initWithData:(id)arg1 dataTypeString:(id)arg2 shape:(id)arg3;
-(id)initWithArray:(id)arg1 dataTypeString:(id)arg2 shape:(id)arg3;
-(id)initWithData:(id)arg1 dataTypeString:(id)arg2 shape:(id)arg3 dataOrder:(int)arg4;
-(id)initWithArray:(id)arg1 dataTypeString:(id)arg2 shape:(id)arg3 dataOrder:(int)arg4;
-(unsigned)sampleIndex:(unsigned)arg1;
-(id)sampleValueAtIndex:(unsigned)arg1;
-(void*)samplePointer:(unsigned)arg1;
-(void*)samplePointerAtIndex:(unsigned)arg1;
-(id)initWithArray:(id)arg1 dataType:(struct _CPTNumericDataType)arg2 shape:(id)arg3;
-(id)sampleValue:(unsigned)arg1;
-(void)dealloc;
-(id)initWithCoder:(id)arg1;
-(void)encodeWithCoder:(id)arg1;
-(id)description;
-(id)copyWithZone:(NSZone*)arg1;
-(id)mutableCopyWithZone:(NSZone*)arg1;
@end