/*
 * This header is generated by weak_classdump 0.2
 * on Saturday, October 18, 2014 at 2:24:55 AM Eastern Daylight Time
 * Operating System: Version 7.1.1 (Build 11D201)
 * weak_classdump is Freeware by Elias Limneos.
 *
 */


@interface CPTPlotAreaFrame : CPTBorderedLayer {
	CPTPlotArea* plotArea; 
}
@property (nonatomic,retain) CPTPlotArea* plotArea; 
@property (nonatomic,@dynamic,retain) CPTAxisSet* axisSet; 
@property (nonatomic,@dynamic,retain) CPTPlotGroup* plotGroup; 
-(void)setAxisSet:(id)arg1;
-(void)setPlotGroup:(id)arg1;
-(id)initWithFrame:(CGRect)arg1;
-(void)dealloc;
-(id)initWithCoder:(id)arg1;
-(void)encodeWithCoder:(id)arg1;
-(id)initWithLayer:(id)arg1;
-(void)setPlotArea:(id)arg1;
-(void)setGraph:(id)arg1;
@end