/*
 * This header is generated by weak_classdump 0.2
 * on Saturday, October 18, 2014 at 2:24:51 AM Eastern Daylight Time
 * Operating System: Version 7.1.1 (Build 11D201)
 * weak_classdump is Freeware by Elias Limneos.
 *
 */


@interface CPTPlotSpaceAnnotation : CPTAnnotation {
	NSArray* anchorPlotPoint; 
	CPTPlotSpace* plotSpace; 
}
@property (nonatomic,copy) NSArray* anchorPlotPoint; 
@property (nonatomic,retain,copy) CPTPlotSpace* plotSpace; 
-(void)setAnchorPlotPoint:(id)arg1;
-(void)setContentNeedsLayout;
-(id)initWithPlotSpace:(id)arg1 anchorPlotPoint:(id)arg2;
-(void)positionContentLayer;
-(void)dealloc;
-(id)initWithCoder:(id)arg1;
-(void)encodeWithCoder:(id)arg1;
-(id)init;
@end