/*
 * This header is generated by weak_classdump 0.2
 * on Saturday, October 18, 2014 at 2:25:10 AM Eastern Daylight Time
 * Operating System: Version 7.1.1 (Build 11D201)
 * weak_classdump is Freeware by Elias Limneos.
 *
 */


@protocol CPTPlotDataSource
@optional
-(id)numbersForPlot(id):arg1 field(unsigned):arg2 recordIndexRange({):arg3 ;
-(id)numberForPlot(id):arg1 field(unsigned):arg2 recordIndex(unsigned):arg3 ;
-(*)doublesForPlot(double):arg1 field(id):arg2 recordIndexRange(unsigned):arg3 ;
-(double)doubleForPlot(id):arg1 field(unsigned):arg2 recordIndex(unsigned):arg3 ;
-(id)dataForPlot(id):arg1 field(unsigned):arg2 recordIndexRange({):arg3 ;
-(id)dataForPlot(id):arg1 recordIndexRange({):arg2 ;
-(id)dataLabelsForPlot(id):arg1 recordIndexRange({):arg2 ;
-(id)dataLabelForPlot(id):arg1 recordIndex(unsigned):arg2 ;
@required
-(unsigned)numberOfRecordsForPlot(id):arg1 ;
-(unsigned)numberOfRecordsForPlot(id):arg1 ;
@end
