/*
 * This header is generated by weak_classdump 0.2
 * on Saturday, October 18, 2014 at 2:24:54 AM Eastern Daylight Time
 * Operating System: Version 7.1.1 (Build 11D201)
 * weak_classdump is Freeware by Elias Limneos.
 *
 */


@interface CPTPlotGroup : CPTLayer {
}
-(void)addPlot:(id)arg1;
-(void)renderAsVectorInContext:(struct CGContext*)arg1;
-(void)removePlot:(id)arg1;
-(void)insertPlot:(id)arg1 atIndex:(unsigned)arg2;
-(id)initWithCoder:(id)arg1;
@end