/*
 * This header is generated by weak_classdump 0.2
 * on Saturday, October 18, 2014 at 2:24:58 AM Eastern Daylight Time
 * Operating System: Version 7.1.1 (Build 11D201)
 * weak_classdump is Freeware by Elias Limneos.
 *
 */


@protocol CPTPieChartDataSource
@optional
-(id)sliceFillsForPieChart(id):arg1 recordIndexRange({):arg2 ;
-(id)sliceFillForPieChart(id):arg1 recordIndex(unsigned):arg2 ;
-(id)radialOffsetsForPieChart(id):arg1 recordIndexRange({):arg2 ;
-(float)radialOffsetForPieChart(id):arg1 recordIndex(unsigned):arg2 ;
-(id)legendTitleForPieChart(id):arg1 recordIndex(unsigned):arg2 ;
-(id)attributedLegendTitleForPieChart(id):arg1 recordIndex(unsigned):arg2 ;
@end
