/*
 * This header is generated by weak_classdump 0.2
 * on Saturday, October 18, 2014 at 2:24:59 AM Eastern Daylight Time
 * Operating System: Version 7.1.1 (Build 11D201)
 * weak_classdump is Freeware by Elias Limneos.
 *
 */


@interface CPTPieChart : CPTPlot {
	float pieRadius; 
	float pieInnerRadius; 
	float startAngle; 
	float endAngle; 
	int sliceDirection; 
	CGPoint centerAnchor; 
	CPTLineStyle* borderLineStyle; 
	CPTFill* overlayFill; 
	BOOL labelRotationRelativeToRadius; 
}
@property (assign,nonatomic) float pieRadius; 
@property (assign,nonatomic) float pieInnerRadius; 
@property (assign,nonatomic) float startAngle; 
@property (assign,nonatomic) float endAngle; 
@property (assign,nonatomic) int sliceDirection; 
@property (assign,nonatomic) CGPoint centerAnchor; 
@property (nonatomic,copy) CPTLineStyle* borderLineStyle; 
@property (nonatomic,copy) CPTFill* overlayFill; 
@property (assign,nonatomic) BOOL labelRotationRelativeToRadius; 
@property (nonatomic,@dynamic,copy) NSArray* sliceWidths; 
@property (nonatomic,@dynamic,copy) NSArray* sliceFills; 
@property (nonatomic,@dynamic,copy) NSArray* sliceRadialOffsets; 
+(id)defaultPieSliceColorForIndex:(unsigned)arg1;
+(BOOL)needsDisplayForKey:(id)arg1;
-(void)setLabelRotation:(float)arg1;
-(void)setBorderLineStyle:(id)arg1;
-(void)setSliceDirection:(int)arg1;
-(void)setCenterAnchor:(CGPoint)arg1;
-(void)renderAsVectorInContext:(struct CGContext*)arg1;
-(void)reloadDataInIndexRange:(struct _NSRange)arg1;
-(void)drawSwatchForLegend:(id)arg1 atIndex:(unsigned)arg2 inRect:(CGRect)arg3 inContext:(struct CGContext*)arg4;
-(id)titleForLegendEntryAtIndex:(unsigned)arg1;
-(id)attributedTitleForLegendEntryAtIndex:(unsigned)arg1;
-(unsigned)dataIndexFromInteractionPoint:(CGPoint)arg1;
-(BOOL)pointingDeviceDownEvent:(struct UIEvent*)arg1 atPoint:(CGPoint)arg2;
-(void)positionLabelAnnotation:(id)arg1 forIndex:(unsigned)arg2;
-(unsigned)numberOfLegendEntries;
-(unsigned)numberOfFields;
-(id)fieldIdentifiers;
-(id)fieldIdentifiersForCoordinate:(int)arg1;
-(void)insertDataAtIndex:(unsigned)arg1 numberOfRecords:(unsigned)arg2;
-(void)updateNormalizedData;
-(void)deleteDataInIndexRange:(struct _NSRange)arg1;
-(float)radiansForPieSliceValue:(float)arg1;
-(void)addSliceToPath:(struct CGPath*)arg1 centerPoint:(CGPoint)arg2 startingAngle:(float)arg3 finishingAngle:(float)arg4;
-(id)sliceFillForIndex:(unsigned)arg1;
-(float)normalizedPosition:(float)arg1;
-(BOOL)angle:(float)arg1 betweenStartAngle:(float)arg2 endAngle:(float)arg3;
-(unsigned)pieSliceIndexAtAngle:(float)arg1;
-(float)medianAngleForPieSliceIndex:(unsigned)arg1;
-(void)setSliceWidths:(id)arg1;
-(void)setSliceFills:(id)arg1;
-(void)setSliceRadialOffsets:(id)arg1;
-(void)setPieInnerRadius:(float)arg1;
-(void)setLabelRotationRelativeToRadius:(BOOL)arg1;
-(void)setOverlayFill:(id)arg1;
-(void)setEndAngle:(float)arg1;
-(id)initWithFrame:(CGRect)arg1;
-(void)dealloc;
-(id)initWithCoder:(id)arg1;
-(void)encodeWithCoder:(id)arg1;
-(void)reloadData;
-(id)initWithLayer:(id)arg1;
-(void)setStartAngle:(float)arg1;
-(void)setPieRadius:(float)arg1;
@end