/*
 * This header is generated by weak_classdump 0.2
 * on Saturday, October 18, 2014 at 2:25:05 AM Eastern Daylight Time
 * Operating System: Version 7.1.1 (Build 11D201)
 * weak_classdump is Freeware by Elias Limneos.
 *
 */


@protocol CPTResponder
@required
-(BOOL)pointingDeviceDownEvent(*):arg1 atPoint({):arg2 ;
-(BOOL)pointingDeviceDraggedEvent(*):arg1 atPoint({):arg2 ;
-(BOOL)pointingDeviceUpEvent(*):arg1 atPoint({):arg2 ;
-(BOOL)pointingDeviceCancelledEvent(*):arg1 ;
-(BOOL)pointingDeviceDownEvent(*):arg1 atPoint({):arg2 ;
-(BOOL)pointingDeviceDraggedEvent(*):arg1 atPoint({):arg2 ;
-(BOOL)pointingDeviceUpEvent(*):arg1 atPoint({):arg2 ;
-(BOOL)pointingDeviceCancelledEvent(*):arg1 ;
@end
