/*
 * This header is generated by weak_classdump 0.2
 * on Saturday, October 18, 2014 at 2:24:51 AM Eastern Daylight Time
 * Operating System: Version 7.1.1 (Build 11D201)
 * weak_classdump is Freeware by Elias Limneos.
 *
 */


@interface CPTScatterPlot : CPTPlot {
	int interpolation; 
	CPTLineStyle* dataLineStyle; 
	CPTPlotSymbol* plotSymbol; 
	CPTFill* areaFill; 
	CPTFill* areaFill2; 
	=exponentblengthbisNegativebisCompactbreservedbmantissaS[=8411188] areaBaseValue; 
	=exponentblengthbisNegativebisCompactbreservedbmantissaS[=8411188] areaBaseValue2; 
	float plotSymbolMarginForHitDetection; 
}
@property (assign,nonatomic) =bbbbbS[=8411188] areaBaseValue; 
@property (assign,nonatomic) =bbbbbS[=8411188] areaBaseValue2; 
@property (assign,nonatomic) int interpolation; 
@property (nonatomic,copy) CPTLineStyle* dataLineStyle; 
@property (nonatomic,copy) CPTPlotSymbol* plotSymbol; 
@property (nonatomic,copy) CPTFill* areaFill; 
@property (nonatomic,copy) CPTFill* areaFill2; 
@property (assign,nonatomic) float plotSymbolMarginForHitDetection; 
@property (nonatomic,@dynamic,copy) NSArray* xValues; 
@property (nonatomic,@dynamic,copy) NSArray* yValues; 
@property (nonatomic,@dynamic,retain) NSArray* plotSymbols; 
+(BOOL)needsDisplayForKey:(id)arg1;
-(void)renderAsVectorInContext:(struct CGContext*)arg1;
-(void)reloadDataInIndexRange:(struct _NSRange)arg1;
-(void)drawSwatchForLegend:(id)arg1 atIndex:(unsigned)arg2 inRect:(CGRect)arg3 inContext:(struct CGContext*)arg4;
-(unsigned)dataIndexFromInteractionPoint:(CGPoint)arg1;
-(BOOL)pointingDeviceDownEvent:(struct UIEvent*)arg1 atPoint:(CGPoint)arg2;
-(void)positionLabelAnnotation:(id)arg1 forIndex:(unsigned)arg2;
-(unsigned)numberOfFields;
-(id)fieldIdentifiers;
-(id)fieldIdentifiersForCoordinate:(int)arg1;
-(unsigned)indexOfVisiblePointClosestToPlotAreaPoint:(CGPoint)arg1;
-(void)calculatePointsToDraw:(BOOL*)arg1 forPlotSpace:(id)arg2 includeVisiblePointsOnly:(BOOL)arg3 numberOfPoints:(unsigned)arg4;
-(void)calculateViewPoints:(CGPoint*)arg1 withDrawPointFlags:(BOOL*)arg2 numberOfPoints:(unsigned)arg3;
-(int)extremeDrawnPointIndexForFlags:(BOOL*)arg1 numberOfPoints:(unsigned)arg2 extremeNumIsLowerBound:(BOOL)arg3;
-(void)alignViewPointsToUserSpace:(CGPoint*)arg1 withContent:(struct CGContext*)arg2 drawPointFlags:(BOOL*)arg3 numberOfPoints:(unsigned)arg4;
-(struct CGPath*)newDataLinePathForViewPoints:(CGPoint*)arg1 indexRange:(struct _NSRange)arg2 baselineYValue:(float)arg3;
-(id)plotSymbolForRecordIndex:(unsigned)arg1;
-(CGPoint)plotAreaPointOfVisiblePointAtIndex:(unsigned)arg1;
-(void)setPlotSymbol:(id)arg1;
-(void)setDataLineStyle:(id)arg1;
-(void)setAreaFill:(id)arg1;
-(void)setAreaFill2:(id)arg1;
-(void)setAreaBaseValue:(=bbbbbS[=8411188])arg1;
-(void)setAreaBaseValue2:(=bbbbbS[=8411188])arg1;
-(void)setYValues:(id)arg1;
-(void)setPlotSymbols:(id)arg1;
-(void)setPlotSymbolMarginForHitDetection:(float)arg1;
-(void)setXValues:(id)arg1;
-(id)initWithFrame:(CGRect)arg1;
-(void)dealloc;
-(id)initWithCoder:(id)arg1;
-(void)encodeWithCoder:(id)arg1;
-(void)setInterpolation:(int)arg1;
-(id)initWithLayer:(id)arg1;
@end