/*
 * This header is generated by weak_classdump 0.2
 * on Saturday, October 18, 2014 at 2:24:48 AM Eastern Daylight Time
 * Operating System: Version 7.1.1 (Build 11D201)
 * weak_classdump is Freeware by Elias Limneos.
 *
 */

#import <NSCoding.h>
#import <NSCopying.h>
#import <NSMutableCopying.h>

@interface CPTTextStyle : NSObject <NSCoding, NSCopying, NSMutableCopying> {
	NSString* fontName; 
	float fontSize; 
	CPTColor* color; 
	int textAlignment; 
	int lineBreakMode; 
}
@property (nonatomic,@dynamic,copy,copy) NSDictionary* attributes; 
@property (nonatomic,copy) NSString* fontName; 
@property (assign,nonatomic) float fontSize; 
@property (nonatomic,copy) CPTColor* color; 
@property (assign,nonatomic) int textAlignment; 
@property (assign,nonatomic) int lineBreakMode; 
+(id)textStyleWithAttributes:(id)arg1;
+(id)textStyle;
-(void)dealloc;
-(id)initWithCoder:(id)arg1;
-(void)encodeWithCoder:(id)arg1;
-(id)init;
-(id)copyWithZone:(NSZone*)arg1;
-(void)setTextAlignment:(int)arg1;
-(void)setLineBreakMode:(int)arg1;
-(void)setColor:(id)arg1;
-(void)setFontSize:(float)arg1;
-(void)setFontName:(id)arg1;
-(id)mutableCopyWithZone:(NSZone*)arg1;
@end