/*
 * This header is generated by weak_classdump 0.2
 * on Saturday, October 18, 2014 at 2:24:44 AM Eastern Daylight Time
 * Operating System: Version 7.1.1 (Build 11D201)
 * weak_classdump is Freeware by Elias Limneos.
 *
 */


@interface CPTTimeFormatter : NSNumberFormatter {
	NSDateFormatter* dateFormatter; 
	NSDate* referenceDate; 
}
@property (nonatomic,retain) NSDateFormatter* dateFormatter; 
@property (nonatomic,copy) NSDate* referenceDate; 
-(id)initWithDateFormatter:(id)arg1;
-(void)setDateFormatter:(id)arg1;
-(void)setReferenceDate:(id)arg1;
-(void)dealloc;
-(id)initWithCoder:(id)arg1;
-(void)encodeWithCoder:(id)arg1;
-(id)init;
-(id)copyWithZone:(NSZone*)arg1;
-(id)stringForObjectValue:(id)arg1;
@end