/*
 * This header is generated by weak_classdump 0.2
 * on Saturday, October 18, 2014 at 2:24:47 AM Eastern Daylight Time
 * Operating System: Version 7.1.1 (Build 11D201)
 * weak_classdump is Freeware by Elias Limneos.
 *
 */


@interface CPTTextLayer : CPTBorderedLayer {
	NSString* text; 
	CPTTextStyle* textStyle; 
	NSAttributedString* attributedText; 
	CGSize maximumSize; 
}
@property (nonatomic,copy) NSString* text; 
@property (nonatomic,retain) CPTTextStyle* textStyle; 
@property (nonatomic,copy) NSAttributedString* attributedText; 
@property (assign,nonatomic) CGSize maximumSize; 
-(id)initWithText:(id)arg1 style:(id)arg2;
-(void)renderAsVectorInContext:(struct CGContext*)arg1;
-(CGSize)sizeThatFits;
-(id)initWithFrame:(CGRect)arg1;
-(void)dealloc;
-(id)initWithCoder:(id)arg1;
-(void)encodeWithCoder:(id)arg1;
-(id)description;
-(void)setText:(id)arg1;
-(void)sizeToFit;
-(void)setAttributedText:(id)arg1;
-(void)setPaddingTop:(float)arg1;
-(void)setPaddingLeft:(float)arg1;
-(id)initWithLayer:(id)arg1;
-(void)setPaddingBottom:(float)arg1;
-(void)setPaddingRight:(float)arg1;
-(id)initWithText:(id)arg1;
-(id)initWithAttributedText:(id)arg1;
-(void)setShadow:(id)arg1;
-(void)setTextStyle:(id)arg1;
-(void)setMaximumSize:(CGSize)arg1;
@end