/*
 * This header is generated by weak_classdump 0.2
 * on Saturday, October 18, 2014 at 2:24:42 AM Eastern Daylight Time
 * Operating System: Version 7.1.1 (Build 11D201)
 * weak_classdump is Freeware by Elias Limneos.
 *
 */

typedef struct{
	unsigned int : value1;
	8 value2;
	unsigned int : value3;
	4 value4;
	unsigned int : value5;
	1 value6;
	unsigned int : value7;
	1 value8;
	unsigned int : value9;
	1 value10;
	8 value11;
	[ value12;
	8 value13;
	unsigned short value14;
	[] value15;
} WCStruct_b8b4b1b1b18[8S];


@interface CPTXYPlotSpace : CPTPlotSpace {
	CPTPlotRange* xRange; 
	CPTPlotRange* yRange; 
	CPTPlotRange* globalXRange; 
	CPTPlotRange* globalYRange; 
	int xScaleType; 
	int yScaleType; 
	CGPoint lastDragPoint; 
	CGPoint lastDisplacement; 
	double lastDragTime; 
	double lastDeltaTime; 
	BOOL isDragging; 
	BOOL allowsMomentum; 
	BOOL elasticGlobalXRange; 
	BOOL elasticGlobalYRange; 
	NSMutableArray* animations; 
}
@property (nonatomic,copy) CPTPlotRange* xRange; 
@property (nonatomic,copy) CPTPlotRange* yRange; 
@property (nonatomic,copy) CPTPlotRange* globalXRange; 
@property (nonatomic,copy) CPTPlotRange* globalYRange; 
@property (assign,nonatomic) int xScaleType; 
@property (assign,nonatomic) int yScaleType; 
@property (assign,nonatomic) BOOL allowsMomentum; 
@property (assign,nonatomic) BOOL elasticGlobalXRange; 
@property (assign,nonatomic) BOOL elasticGlobalYRange; 
@property (assign,nonatomic) BOOL isDragging; 
@property (assign,nonatomic) CGPoint lastDragPoint; 
@property (assign,nonatomic) CGPoint lastDisplacement; 
@property (assign,nonatomic) double lastDragTime; 
@property (assign,nonatomic) double lastDeltaTime; 
@property (nonatomic,retain) NSMutableArray* animations; 
-(void)setYRange:(id)arg1;
-(CGPoint)plotAreaViewPointForPlotPoint:(WCStruct_b8b4b1b1b18[8S]*)arg1 numberOfCoordinates:(unsigned)arg2;
-(void)doublePrecisionPlotPoint:(double*)arg1 numberOfCoordinates:(unsigned)arg2 forPlotAreaViewPoint:(CGPoint)arg3;
-(void)plotPoint:(WCStruct_b8b4b1b1b18[8S]*)arg1 numberOfCoordinates:(unsigned)arg2 forPlotAreaViewPoint:(CGPoint)arg3;
-(id)plotRangeForCoordinate:(int)arg1;
-(CGPoint)plotAreaViewPointForDoublePrecisionPlotPoint:(double*)arg1 numberOfCoordinates:(unsigned)arg2;
-(BOOL)pointingDeviceDownEvent:(struct UIEvent*)arg1 atPoint:(CGPoint)arg2;
-(BOOL)pointingDeviceDraggedEvent:(struct UIEvent*)arg1 atPoint:(CGPoint)arg2;
-(BOOL)pointingDeviceUpEvent:(struct UIEvent*)arg1 atPoint:(CGPoint)arg2;
-(void)scaleBy:(float)arg1 aboutPoint:(CGPoint)arg2;
-(void)setXScaleType:(int)arg1;
-(void)setYScaleType:(int)arg1;
-(id)constrainRange:(id)arg1 toGlobalRange:(id)arg2;
-(float)viewCoordinateForViewLength:(float)arg1 linearPlotRange:(id)arg2 plotCoordinateValue:(=bbbbbS[=8411188])arg3;
-(float)viewCoordinateForViewLength:(float)arg1 logPlotRange:(id)arg2 doublePrecisionPlotCoordinateValue:(double)arg3;
-(float)viewCoordinateForViewLength:(float)arg1 linearPlotRange:(id)arg2 doublePrecisionPlotCoordinateValue:(double)arg3;
-(=bbbbbS[=8411188])plotCoordinateForViewLength:(float)arg1 linearPlotRange:(id)arg2 boundsLength:(float)arg3;
-(double)doublePrecisionPlotCoordinateForViewLength:(float)arg1 logPlotRange:(id)arg2 boundsLength:(float)arg3;
-(double)doublePrecisionPlotCoordinateForViewLength:(float)arg1 linearPlotRange:(id)arg2 boundsLength:(float)arg3;
-(CGPoint)plotAreaViewPointForEvent:(struct UIEvent*)arg1;
-(void)setElasticGlobalXRange:(BOOL)arg1;
-(void)setElasticGlobalYRange:(BOOL)arg1;
-(void)setIsDragging:(BOOL)arg1;
-(void)setLastDragPoint:(CGPoint)arg1;
-(void)setLastDisplacement:(CGPoint)arg1;
-(void)setLastDragTime:(double)arg1;
-(void)setLastDeltaTime:(double)arg1;
-(void)animateRange:(id)arg1 property:(id)arg2 globalRange:(id)arg3 shift:(=bbbbbS[=8411188])arg4;
-(id)shiftRange:(id)arg1 by:(=bbbbbS[=8411188])arg2 inGlobalRange:(id)arg3 elastic:(BOOL)arg4 withDisplacement:(float*)arg5;
-(void)setPlotRange:(id)arg1 forCoordinate:(int)arg2;
-(void)setScaleType:(int)arg1 forCoordinate:(int)arg2;
-(int)scaleTypeForCoordinate:(int)arg1;
-(void)setGlobalXRange:(id)arg1;
-(void)setGlobalYRange:(id)arg1;
-(void)scaleToFitPlots:(id)arg1;
-(unsigned)numberOfCoordinates;
-(void)plotPoint:(WCStruct_b8b4b1b1b18[8S]*)arg1 numberOfCoordinates:(unsigned)arg2 forEvent:(struct UIEvent*)arg3;
-(void)doublePrecisionPlotPoint:(double*)arg1 numberOfCoordinates:(unsigned)arg2 forEvent:(struct UIEvent*)arg3;
-(void)setAllowsMomentum:(BOOL)arg1;
-(void)dealloc;
-(id)initWithCoder:(id)arg1;
-(void)encodeWithCoder:(id)arg1;
-(id)init;
-(void)setAnimations:(id)arg1;
-(void)setXRange:(id)arg1;
@end