/*
 * This header is generated by weak_classdump 0.2
 * on Saturday, October 18, 2014 at 2:24:43 AM Eastern Daylight Time
 * Operating System: Version 7.1.1 (Build 11D201)
 * weak_classdump is Freeware by Elias Limneos.
 *
 */


@interface CPTXYGraph : CPTGraph {
	int xScaleType; 
	int yScaleType; 
}
@property (assign,nonatomic) int xScaleType; 
@property (assign,nonatomic) int yScaleType; 
-(id)newPlotSpace;
-(id)newAxisSet;
-(id)initWithFrame:(CGRect)arg1 xScaleType:(int)arg2 yScaleType:(int)arg3;
-(void)setXScaleType:(int)arg1;
-(void)setYScaleType:(int)arg1;
-(id)initWithFrame:(CGRect)arg1;
-(id)initWithCoder:(id)arg1;
-(void)encodeWithCoder:(id)arg1;
-(id)initWithLayer:(id)arg1;
@end