/*
 * This header is generated by weak_classdump 0.2
 * on Saturday, October 18, 2014 at 2:24:44 AM Eastern Daylight Time
 * Operating System: Version 7.1.1 (Build 11D201)
 * weak_classdump is Freeware by Elias Limneos.
 *
 */


@interface CPTXYAxisSet : CPTAxisSet {
}
@property (nonatomic,@dynamic,retain,copy) CPTXYAxis* xAxis; 
@property (nonatomic,@dynamic,retain,copy) CPTXYAxis* yAxis; 
-(void)renderAsVectorInContext:(struct CGContext*)arg1;
-(id)initWithFrame:(CGRect)arg1;
@end