/*
 * This header is generated by weak_classdump 0.2
 * on Saturday, October 18, 2014 at 2:29:13 AM Eastern Daylight Time
 * Operating System: Version 7.1.1 (Build 11D201)
 * weak_classdump is Freeware by Elias Limneos.
 *
 */


@interface FBAppEvents : NSObject {
	BOOL _haveOutstandingPersistedData; 
	BOOL _appSupportsImplicitLogging; 
	BOOL _haveFetchedAppSettings; 
	int _flushBehavior; 
	FBSession* _lastSessionLoggedTo; 
	NSTimer* _flushTimer; 
	NSTimer* _attributionIDRecheckTimer; 
	int _appSupportsAttributionStatus; 
	NSRegularExpression* _eventNameRegex; 
	NSMutableSet* _validatedIdentifiers; 
	NSMutableDictionary* _appAuthSessions; 
	NSMutableDictionary* _anonymousSessions; 
}
@property (assign) int flushBehavior; 				//@synthesize flushBehavior=_flushBehavior - In the implementation block
@property (assign) BOOL haveOutstandingPersistedData; 				//@synthesize haveOutstandingPersistedData=_haveOutstandingPersistedData - In the implementation block
@property (retain) FBSession* lastSessionLoggedTo; 				//@synthesize lastSessionLoggedTo=_lastSessionLoggedTo - In the implementation block
@property (retain) NSTimer* flushTimer; 				//@synthesize flushTimer=_flushTimer - In the implementation block
@property (retain) NSTimer* attributionIDRecheckTimer; 				//@synthesize attributionIDRecheckTimer=_attributionIDRecheckTimer - In the implementation block
@property (assign) int appSupportsAttributionStatus; 				//@synthesize appSupportsAttributionStatus=_appSupportsAttributionStatus - In the implementation block
@property (assign) BOOL appSupportsImplicitLogging; 				//@synthesize appSupportsImplicitLogging=_appSupportsImplicitLogging - In the implementation block
@property (assign) BOOL haveFetchedAppSettings; 				//@synthesize haveFetchedAppSettings=_haveFetchedAppSettings - In the implementation block
@property (retain) NSRegularExpression* eventNameRegex; 				//@synthesize eventNameRegex=_eventNameRegex - In the implementation block
@property (retain) NSMutableSet* validatedIdentifiers; 				//@synthesize validatedIdentifiers=_validatedIdentifiers - In the implementation block
@property (retain) NSMutableDictionary* appAuthSessions; 				//@synthesize appAuthSessions=_appAuthSessions - In the implementation block
@property (retain) NSMutableDictionary* anonymousSessions; 				//@synthesize anonymousSessions=_anonymousSessions - In the implementation block
+(void)logEvent:(id)arg1 parameters:(id)arg2;
+(void)logEvent:(id)arg1 valueToSum:(double)arg2 parameters:(id)arg3;
+(void)logEvent:(id)arg1 valueToSum:(id)arg2 parameters:(id)arg3 session:(id)arg4;
+(id)singleton;
+(void)logAndNotify:(id)arg1;
+(void)logEvent:(id)arg1;
+(long)unixTimeNow;
+(void)ensureOnMainThread;
+(id)flushReasonToString:(int)arg1;
+(id)unaffinitizedSessionFromToken:(id)arg1 appID:(id)arg2;
+(void)logAndNotify:(id)arg1 allowLogAsDeveloperError:(BOOL*)arg2;
+(id)retrievePersistedAppEventData;
+(void)clearPersistedAppEventData;
+(void)persistAppEventsData:(id)arg1;
+(id)persistenceFilePath;
+(void)logEvent:(id)arg1 valueToSum:(double)arg2;
+(BOOL)limitEventUsage;
+(void)setLimitEventUsage:(BOOL)arg1;
+(void)activateApp;
+(id)customAudienceThirdPartyIDRequest:(id)arg1;
+(void)logImplicitEvent:(id)arg1 valueToSum:(id)arg2 parameters:(id)arg3 session:(id)arg4;
+(void)logPurchase:(double)arg1 currency:(id)arg2 parameters:(id)arg3;
+(void)logPurchase:(double)arg1 currency:(id)arg2 parameters:(id)arg3 session:(id)arg4;
+(void)logConversionPixel:(id)arg1 valueOfPixel:(double)arg2 session:(id)arg3;
+(void)setFlushBehavior:(int)arg1;
+(void)logPurchase:(double)arg1 currency:(id)arg2;
-(void)instanceLogEvent:(id)arg1 valueToSum:(id)arg2 parameters:(id)arg3 isImplicitlyLogged:(BOOL)arg4 session:(id)arg5;
-(void)instanceFlush:(int)arg1;
-(void)setHaveOutstandingPersistedData:(BOOL)arg1;
-(void)setAppSupportsAttributionStatus:(int)arg1;
-(void)setAppAuthSessions:(id)arg1;
-(void)flushTimerFired:(id)arg1;
-(void)setFlushTimer:(id)arg1;
-(void)attributionIDRecheckTimerFired:(id)arg1;
-(void)setAttributionIDRecheckTimer:(id)arg1;
-(void)applicationMovingFromActiveState;
-(void)applicationTerminating;
-(BOOL)regexValidateIdentifier:(id)arg1;
-(void)setEventNameRegex:(id)arg1;
-(void)setValidatedIdentifiers:(id)arg1;
-(BOOL)validateIdentifier:(id)arg1;
-(id)sessionToSendRequestTo:(id)arg1;
-(void)setLastSessionLoggedTo:(id)arg1;
-(void)flush:(int)arg1 session:(id)arg2;
-(BOOL)updateAppEventsStateWithPersistedData:(id)arg1;
-(void)flushOnMainQueue:(int)arg1 session:(id)arg2;
-(void)setAppSupportsImplicitLogging:(BOOL)arg1;
-(void)setHaveFetchedAppSettings:(BOOL)arg1;
-(void)appendAttributionAndAdvertiserIDs:(id)arg1 session:(id)arg2;
-(void)handleActivitiesPostCompletion:(id)arg1 loggingEntry:(id)arg2 session:(id)arg3;
-(void)persistDataIfNotInFlight;
-(id)instanceCustomAudienceThirdPartyIDRequest:(id)arg1;
-(BOOL)doesSessionHaveUserToken:(id)arg1;
-(void)setAnonymousSessions:(id)arg1;
-(void)setFlushBehavior:(int)arg1;
-(id)init;
-(void)applicationDidBecomeActive;
@end