/*
 * This header is generated by weak_classdump 0.2
 * on Saturday, October 18, 2014 at 2:24:34 AM Eastern Daylight Time
 * Operating System: Version 7.1.1 (Build 11D201)
 * weak_classdump is Freeware by Elias Limneos.
 *
 */


@interface FBAppBridgeTypeToJSONConverter : NSObject {
	NSMutableArray* _createdPasteboardNames; 
}
@property (nonatomic,retain) NSMutableArray* createdPasteboardNames; 				//@synthesize createdPasteboardNames=_createdPasteboardNames - In the implementation block
+(id)appBridgeTypeFromJSON:(id)arg1;
-(id)jsonDictionaryFromDictionaryWithAppBridgeTypes:(id)arg1;
-(id)dictionaryWithAppBridgeTypesFromJSONDictionary:(id)arg1;
-(void)setCreatedPasteboardNames:(id)arg1;
-(id)convertedDictionaryFromDictionary:(id)arg1 convertingToJSON:(BOOL)arg2;
-(id)convertedArrayFromArray:(id)arg1 convertingToJSON:(BOOL)arg2;
-(id)jsonFromData:(id)arg1 tag:(id)arg2;
-(id)convertedObjectFromObject:(id)arg1 convertingToJSON:(BOOL)arg2;
-(void)dealloc;
@end