/*
 * This header is generated by weak_classdump 0.2
 * on Saturday, October 18, 2014 at 2:29:12 AM Eastern Daylight Time
 * Operating System: Version 7.1.1 (Build 11D201)
 * weak_classdump is Freeware by Elias Limneos.
 *
 */


@interface FBAppLinkData : NSObject {
	NSURL* _targetURL; 
	NSArray* _actionTypes; 
	NSArray* _actionIDs; 
	NSString* _ref; 
	NSString* _userAgent; 
	NSDictionary* _refererData; 
	NSDictionary* _originalQueryParameters; 
	NSURL* _originalURL; 
	NSDictionary* _arguments; 
}
@property (retain) NSURL* targetURL; 				//@synthesize targetURL=_targetURL - In the implementation block
@property (copy) NSArray* actionTypes; 				//@synthesize actionTypes=_actionTypes - In the implementation block
@property (copy) NSArray* actionIDs; 				//@synthesize actionIDs=_actionIDs - In the implementation block
@property (copy) NSString* ref; 				//@synthesize ref=_ref - In the implementation block
@property (copy) NSString* userAgent; 				//@synthesize userAgent=_userAgent - In the implementation block
@property (copy) NSDictionary* refererData; 				//@synthesize refererData=_refererData - In the implementation block
@property (copy) NSDictionary* originalQueryParameters; 				//@synthesize originalQueryParameters=_originalQueryParameters - In the implementation block
@property (retain) NSURL* originalURL; 				//@synthesize originalURL=_originalURL - In the implementation block
@property (copy) NSDictionary* arguments; 				//@synthesize arguments=_arguments - In the implementation block
+(id)createFromURL:(id)arg1;
-(id)initWithURL:(id)arg1 targetURL:(id)arg2 originalParams:(id)arg3 arguments:(id)arg4;
-(void)setActionIDs:(id)arg1;
-(void)setActionTypes:(id)arg1;
-(void)setOriginalURL:(id)arg1;
-(void)setRefererData:(id)arg1;
-(void)setOriginalQueryParameters:(id)arg1;
-(id)initWithURL:(id)arg1 targetURL:(id)arg2 ref:(id)arg3 userAgent:(id)arg4 refererData:(id)arg5 originalParams:(id)arg6;
-(void)setArguments:(id)arg1;
-(void)dealloc;
-(id)description;
-(BOOL)isValid;
-(id)initWithURL:(id)arg1;
-(void)setUserAgent:(id)arg1;
-(void)setRef:(id)arg1;
-(void)setTargetURL:(id)arg1;
@end