/*
 * This header is generated by weak_classdump 0.2
 * on Saturday, October 18, 2014 at 2:29:06 AM Eastern Daylight Time
 * Operating System: Version 7.1.1 (Build 11D201)
 * weak_classdump is Freeware by Elias Limneos.
 *
 */


@protocol FBCacheIndexFileDelegate
@required
-(void)cacheIndex(id):arg1 writeFileWithName(id):arg2 data(id):arg3 ;
-(void)cacheIndex(id):arg1 deleteFileWithName(id):arg2 ;
-(void)cacheIndex(id):arg1 writeFileWithName(id):arg2 data(id):arg3 ;
-(void)cacheIndex(id):arg1 deleteFileWithName(id):arg2 ;
@end
