/*
 * This header is generated by weak_classdump 0.2
 * on Saturday, October 18, 2014 at 2:29:06 AM Eastern Daylight Time
 * Operating System: Version 7.1.1 (Build 11D201)
 * weak_classdump is Freeware by Elias Limneos.
 *
 */

#import <FBCacheIndexFileDelegate.h>

@interface FBDataDiskCache : NSObject <FBCacheIndexFileDelegate> {
	NSCache* _inMemoryCache; 
	FBCacheIndex* _cacheIndex; 
	NSString* _dataCachePath; 
	NSObject<OS_dispatch_queue>* _fileQueue; 
}
@property (assign,nonatomic) unsigned cacheSizeMemory; 
@property (nonatomic,copy) NSObject<OS_dispatch_queue>* fileQueue; 				//@synthesize fileQueue=_fileQueue - In the implementation block
@property (nonatomic,copy) NSString* dataCachePath; 				//@synthesize dataCachePath=_dataCachePath - In the implementation block
+(id)sharedCache;
-(void)cacheIndex:(id)arg1 writeFileWithName:(id)arg2 data:(id)arg3;
-(void)cacheIndex:(id)arg1 deleteFileWithName:(id)arg2;
-(BOOL)_doesFileExist:(id)arg1;
-(void)setCacheSizeMemory:(unsigned)arg1;
-(void)removeDataForUrl:(id)arg1;
-(void)setDataCachePath:(id)arg1;
-(id)dataForURL:(id)arg1;
-(void)setData:(id)arg1 forURL:(id)arg2;
-(void)removeDataForSession:(id)arg1;
-(void)dealloc;
-(id)init;
@end