/*
 * This header is generated by weak_classdump 0.2
 * on Saturday, October 18, 2014 at 2:29:02 AM Eastern Daylight Time
 * Operating System: Version 7.1.1 (Build 11D201)
 * weak_classdump is Freeware by Elias Limneos.
 *
 */


@interface FBDialogsData : NSObject {
	NSString* _method; 
	NSDictionary* _arguments; 
	NSDictionary* _clientState; 
	NSDictionary* _results; 
}
@property (nonatomic,copy) NSString* method; 				//@synthesize method=_method - In the implementation block
@property (nonatomic,copy) NSDictionary* arguments; 				//@synthesize arguments=_arguments - In the implementation block
@property (nonatomic,copy) NSDictionary* clientState; 				//@synthesize clientState=_clientState - In the implementation block
@property (nonatomic,copy) NSDictionary* results; 				//@synthesize results=_results - In the implementation block
-(id)initWithMethod:(id)arg1 arguments:(id)arg2;
-(void)setArguments:(id)arg1;
-(void)dealloc;
-(id)description;
-(BOOL)isValid;
-(void)setResults:(id)arg1;
-(void)setClientState:(id)arg1;
-(void)setMethod:(id)arg1;
@end