/*
 * This header is generated by weak_classdump 0.2
 * on Saturday, October 18, 2014 at 2:28:22 AM Eastern Daylight Time
 * Operating System: Version 7.1.1 (Build 11D201)
 * weak_classdump is Freeware by Elias Limneos.
 *
 */


@protocol FBDialogDelegate
@optional
-(void)dialogDidComplete(id):arg1 ;
-(void)dialogCompleteWithUrl(id):arg1 ;
-(void)dialogDidNotCompleteWithUrl(id):arg1 ;
-(void)dialogDidNotComplete(id):arg1 ;
-(void)dialog(id):arg1 didFailWithError(id):arg2 ;
-(BOOL)dialog(id):arg1 shouldOpenURLInExternalBrowser(id):arg2 ;
@end
