/*
 * This header is generated by weak_classdump 0.2
 * on Saturday, October 18, 2014 at 2:29:02 AM Eastern Daylight Time
 * Operating System: Version 7.1.1 (Build 11D201)
 * weak_classdump is Freeware by Elias Limneos.
 *
 */


@interface FBDynamicFrameworkLoader : NSObject {
}
+(struct __SecRandom*)loadkSecRandomDefault;
+(Class)loadClass:(id)arg1 withFramework:(id)arg2;
+(id)loadStringConstant:(id)arg1 withFramework:(id)arg2;
+(void*)loadSymbol:(id)arg1 withFramework:(id)arg2;
+(id)frameworkPathTemplate;
+(void)setFrameworkPathTemplate:(id)arg1;
+(id)sqlitePath;
+(void)setSqlitePath:(id)arg1;
@end