/*
 * This header is generated by weak_classdump 0.2
 * on Saturday, October 18, 2014 at 2:29:01 AM Eastern Daylight Time
 * Operating System: Version 7.1.1 (Build 11D201)
 * weak_classdump is Freeware by Elias Limneos.
 *
 */

#import <FBFrictionlessDialogSupportDelegate.h>
#import <FBWebDialogsDelegate.h>

@interface FBFrictionlessRecipientCache : FBCacheDescriptor <FBFrictionlessDialogSupportDelegate, FBWebDialogsDelegate> {
	BOOL _frictionlessShouldMakeViewInvisible; 
	FBFrictionlessRequestSettings* _frictionlessSettings; 
}
@property (nonatomic,copy) NSArray* recipientIDs; 
@property (assign,nonatomic) BOOL frictionlessShouldMakeViewInvisible; 				//@synthesize frictionlessShouldMakeViewInvisible=_frictionlessShouldMakeViewInvisible - In the implementation block
@property (nonatomic,retain) FBFrictionlessRequestSettings* frictionlessSettings; 				//@synthesize frictionlessSettings=_frictionlessSettings - In the implementation block
-(void)setFrictionlessSettings:(id)arg1;
-(BOOL)isFrictionlessRecipient:(id)arg1;
-(void)prefetchAndCacheForSession:(id)arg1 completionHandler:(id)arg2;
-(void)setFrictionlessShouldMakeViewInvisible:(BOOL)arg1;
-(void)webDialogsWillPresentDialog:(id)arg1 parameters:(id)arg2 session:(id)arg3;
-(void)setRecipientIDs:(id)arg1;
-(BOOL)areFrictionlessRecipients:(id)arg1;
-(void)prefetchAndCacheForSession:(id)arg1;
-(void)dealloc;
-(id)init;
@end