/*
 * This header is generated by weak_classdump 0.2
 * on Saturday, October 18, 2014 at 2:28:59 AM Eastern Daylight Time
 * Operating System: Version 7.1.1 (Build 11D201)
 * weak_classdump is Freeware by Elias Limneos.
 *
 */


@protocol FBGraphObjectPagingLoaderDelegate
@optional
-(void)pagingLoader(id):arg1 willLoadURL(id):arg2 ;
-(void)pagingLoader(id):arg1 didLoadData(id):arg2 ;
-(void)pagingLoaderDidFinishLoading(id):arg1 ;
-(void)pagingLoader(id):arg1 handleError(id):arg2 ;
-(void)pagingLoaderWasCancelled(id):arg1 ;
@end
