/*
 * This header is generated by weak_classdump 0.2
 * on Saturday, October 18, 2014 at 2:28:56 AM Eastern Daylight Time
 * Operating System: Version 7.1.1 (Build 11D201)
 * weak_classdump is Freeware by Elias Limneos.
 *
 */

#import <FBGraphObject.h>

@interface FBGraphObject : NSMutableDictionary <FBGraphObject> {
	NSMutableDictionary* _jsonObject; 
}
@property (assign,nonatomic) BOOL provisionedForPost; 
+(id)graphObject;
+(id)graphObjectWrappingDictionary:(id)arg1;
+(id)graphObjectWrappingObject:(id)arg1;
+(id)openGraphObjectForPostWithType:(id)arg1 title:(id)arg2 image:(id)arg3 url:(id)arg4 description:(id)arg5;
+(int)inferredImplTypeForSelector:(SEL)arg1;
+(BOOL)isProtocolImplementationInferable:(id)arg1 checkFBGraphObjectAdoption:(BOOL)arg2;
+(id)openGraphActionForPost;
+(id)openGraphObjectForPost;
+(BOOL)isGraphObjectID:(id)arg1 sameAs:(id)arg2;
-(void)setProvisionedForPost:(BOOL)arg1;
-(id)graphObjectifyAtKey:(id)arg1;
-(void)graphObjectifyAll;
-(id)initWrappingDictionary:(id)arg1;
-(void)dealloc;
-(BOOL)respondsToSelector:(SEL)arg1;
-(unsigned)count;
-(BOOL)conformsToProtocol:(id)arg1;
-(void)removeObjectForKey:(id)arg1;
-(id)methodSignatureForSelector:(SEL)arg1;
-(void)forwardInvocation:(id)arg1;
-(id)keyEnumerator;
-(id)objectForKey:(id)arg1;
-(void)setObject:(id)arg1 forKey:(id)arg2;
@end