/*
 * This header is generated by weak_classdump 0.2
 * on Saturday, October 18, 2014 at 2:28:52 AM Eastern Daylight Time
 * Operating System: Version 7.1.1 (Build 11D201)
 * weak_classdump is Freeware by Elias Limneos.
 *
 */


@interface FBImageResourceLoader : NSObject {
}
+(id)imageNamed:(id)arg1 fromBytes:(r*)arg2 length:(unsigned)arg3 fromRetinaBytes:(r*)arg4 retinaLength:(unsigned)arg5;
+(id)loadImageFromBytes:(r*)arg1 length:(unsigned)arg2 scale:(float)arg3;
+(id)imageFromBytes:(r*)arg1 length:(unsigned)arg2 fromRetinaBytes:(r*)arg3 retinaLength:(unsigned)arg4;
@end