/*
 * This header is generated by weak_classdump 0.2
 * on Saturday, October 18, 2014 at 2:28:52 AM Eastern Daylight Time
 * Operating System: Version 7.1.1 (Build 11D201)
 * weak_classdump is Freeware by Elias Limneos.
 *
 */


@interface FBInsights : NSObject {
}
+(void)logPurchase:(double)arg1 currency:(id)arg2 parameters:(id)arg3;
+(void)logPurchase:(double)arg1 currency:(id)arg2 parameters:(id)arg3 session:(id)arg4;
+(void)logConversionPixel:(id)arg1 valueOfPixel:(double)arg2 session:(id)arg3;
+(int)flushBehavior;
+(void)setFlushBehavior:(int)arg1;
+(void)logPurchase:(double)arg1 currency:(id)arg2;
+(void)logConversionPixel:(id)arg1 valueOfPixel:(double)arg2;
+(void)flush;
+(id)appVersion;
+(void)setAppVersion:(id)arg1;
@end