/*
 * This header is generated by weak_classdump 0.2
 * on Saturday, October 18, 2014 at 2:28:51 AM Eastern Daylight Time
 * Operating System: Version 7.1.1 (Build 11D201)
 * weak_classdump is Freeware by Elias Limneos.
 *
 */


@interface FBLogger : NSObject {
	BOOL _isActive; 
	NSMutableString* _internalContents; 
	NSString* _loggingBehavior; 
	unsigned _loggerSerialNumber; 
}
@property (nonatomic,copy) NSString* contents; 
@property (nonatomic,copy) unsigned loggerSerialNumber; 				//@synthesize loggerSerialNumber=_loggerSerialNumber - In the implementation block
@property (nonatomic,copy,copy) NSString* loggingBehavior; 				//@synthesize loggingBehavior=_loggingBehavior - In the implementation block
@property (nonatomic,copy) BOOL isActive; 				//@synthesize isActive=_isActive - In the implementation block
@property (nonatomic,retain,copy) NSMutableString* internalContents; 				//@synthesize internalContents=_internalContents - In the implementation block
+(void)singleShotLogEntry:(id)arg1 formatString:(id)arg2;
+(void)registerCurrentTime:(id)arg1 withTag:(id)arg2;
+(void)singleShotLogEntry:(id)arg1 timestampTag:(id)arg2 formatString:(id)arg3;
+(unsigned)newSerialNumber;
+(void)singleShotLogEntry:(id)arg1 logEntry:(id)arg2;
+(void)registerStringToReplace:(id)arg1 replaceWith:(id)arg2;
-(id)initWithLoggingBehavior:(id)arg1;
-(void)emitToNSLog;
-(void)appendKey:(id)arg1 value:(id)arg2;
-(void)dealloc;
-(void)appendFormat:(id)arg1;
-(void)appendString:(id)arg1;
-(void)setContents:(id)arg1;
@end