/*
 * This header is generated by weak_classdump 0.2
 * on Saturday, October 18, 2014 at 2:28:51 AM Eastern Daylight Time
 * Operating System: Version 7.1.1 (Build 11D201)
 * weak_classdump is Freeware by Elias Limneos.
 *
 */


@interface FBLoginDialog : FBDialog {
	id<FBLoginDialogDelegate> _loginDelegate; 
}
-(void)dialogDidSucceed:(id)arg1;
-(id)initWithURL:(id)arg1 loginParams:(id)arg2 delegate:(id)arg3;
-(void)webView:(id)arg1 didFailLoadWithError:(id)arg2;
-(void)dialogDidCancel:(id)arg1;
@end