/*
 * This header is generated by weak_classdump 0.2
 * on Saturday, October 18, 2014 at 2:28:49 AM Eastern Daylight Time
 * Operating System: Version 7.1.1 (Build 11D201)
 * weak_classdump is Freeware by Elias Limneos.
 *
 */

#import <UIActionSheetDelegate.h>

@interface FBLoginView : UIView <UIActionSheetDelegate> {
	NSArray* _permissions; 
	NSArray* _readPermissions; 
	NSArray* _publishPermissions; 
	int _defaultAudience; 
	int _loginBehavior; 
	id<FBLoginViewDelegate> _delegate; 
	UILabel* _label; 
	UIButton* _button; 
	FBSession* _session; 
	FBRequestConnection* _request; 
	id<FBGraphUser> _user; 
	id _sessionStateHandler; 
	id _requestHandler; 
	NSNumber* _lastObservedStateWasOpen; 
}
@property (copy) NSArray* permissions; 				//@synthesize permissions=_permissions - In the implementation block
@property (nonatomic,copy) NSArray* readPermissions; 				//@synthesize readPermissions=_readPermissions - In the implementation block
@property (nonatomic,copy) NSArray* publishPermissions; 				//@synthesize publishPermissions=_publishPermissions - In the implementation block
@property (assign,nonatomic) int defaultAudience; 				//@synthesize defaultAudience=_defaultAudience - In the implementation block
@property (assign,nonatomic) int loginBehavior; 				//@synthesize loginBehavior=_loginBehavior - In the implementation block
@property (assign,nonatomic) id<FBLoginViewDelegate> delegate; 				//@synthesize delegate=_delegate - In the implementation block
@property (nonatomic,retain) UILabel* label; 				//@synthesize label=_label - In the implementation block
@property (nonatomic,retain) UIButton* button; 				//@synthesize button=_button - In the implementation block
@property (nonatomic,retain) FBSession* session; 				//@synthesize session=_session - In the implementation block
@property (nonatomic,retain) FBRequestConnection* request; 				//@synthesize request=_request - In the implementation block
@property (nonatomic,retain) id<FBGraphUser> user; 				//@synthesize user=_user - In the implementation block
@property (nonatomic,copy) id sessionStateHandler; 				//@synthesize sessionStateHandler=_sessionStateHandler - In the implementation block
@property (nonatomic,copy) id requestHandler; 				//@synthesize requestHandler=_requestHandler - In the implementation block
@property (copy) NSNumber* lastObservedStateWasOpen; 				//@synthesize lastObservedStateWasOpen=_lastObservedStateWasOpen - In the implementation block
-(void)setReadPermissions:(id)arg1;
-(void)setPublishPermissions:(id)arg1;
-(void)unwireViewForSession;
-(void)informDelegate:(BOOL)arg1;
-(void)informDelegateOfError:(id)arg1;
-(void)setSessionStateHandler:(id)arg1;
-(void)setRequestHandler:(id)arg1;
-(void)initializeBlocks;
-(void)wireViewForSession:(id)arg1 userInfo:(id)arg2;
-(void)handleActiveSessionSetNotifications:(id)arg1;
-(void)handleActiveSessionUnsetNotifications:(id)arg1;
-(id)logInText;
-(id)logOutText;
-(void)fetchMeInfo;
-(void)configureViewForStateLoggedIn:(BOOL)arg1;
-(void)setLoginBehavior:(int)arg1;
-(void)setLastObservedStateWasOpen:(id)arg1;
-(void)wireViewForSessionWithoutOpening:(id)arg1;
-(id)initWithPermissions:(id)arg1;
-(id)initWithReadPermissions:(id)arg1;
-(id)initWithPublishPermissions:(id)arg1 defaultAudience:(int)arg2;
-(void)setDefaultAudience:(int)arg1;
-(void)setSession:(id)arg1;
-(void)setPermissions:(id)arg1;
-(void)setUser:(id)arg1;
-(void)setButton:(id)arg1;
-(void)setRequest:(id)arg1;
-(id)initWithFrame:(CGRect)arg1;
-(void)dealloc;
-(id)initWithCoder:(id)arg1;
-(void)setDelegate:(id)arg1;
-(id)init;
-(CGSize)sizeThatFits:(CGSize)arg1;
-(void)actionSheet:(id)arg1 didDismissWithButtonIndex:(int)arg2;
-(void)initialize;
-(CGSize)intrinsicContentSize;
-(void)setLabel:(id)arg1;
-(void)observeValueForKeyPath:(id)arg1 ofObject:(id)arg2 change:(id)arg3 context:(void*)arg4;
-(void)buttonPressed:(id)arg1;
@end