/*
 * This header is generated by weak_classdump 0.2
 * on Saturday, October 18, 2014 at 2:28:51 AM Eastern Daylight Time
 * Operating System: Version 7.1.1 (Build 11D201)
 * weak_classdump is Freeware by Elias Limneos.
 *
 */


@interface FBLoginDialogParams : FBDialogsParams {
	BOOL _isRefreshOnly; 
	NSArray* _permissions; 
	int _writePrivacy; 
	FBSession* _session; 
}
@property (nonatomic,copy) NSArray* permissions; 				//@synthesize permissions=_permissions - In the implementation block
@property (assign,nonatomic) int writePrivacy; 				//@synthesize writePrivacy=_writePrivacy - In the implementation block
@property (assign) BOOL isRefreshOnly; 				//@synthesize isRefreshOnly=_isRefreshOnly - In the implementation block
@property (nonatomic,retain) FBSession* session; 				//@synthesize session=_session - In the implementation block
-(id)appBridgeVersion;
-(id)dictionaryMethodArgs;
-(void)setWritePrivacy:(int)arg1;
-(void)setIsRefreshOnly:(BOOL)arg1;
-(void)setSession:(id)arg1;
-(void)setPermissions:(id)arg1;
-(void)dealloc;
@end