/*
 * This header is generated by weak_classdump 0.2
 * on Saturday, October 18, 2014 at 2:28:35 AM Eastern Daylight Time
 * Operating System: Version 7.1.1 (Build 11D201)
 * weak_classdump is Freeware by Elias Limneos.
 *
 */


@protocol FBLoginDialogDelegate
@required
-(void)fbDialogLogin(id):arg1 expirationDate(id):arg2 params(id):arg3 ;
-(void)fbDialogNotLogin(BOOL):arg1 ;
-(void)fbDialogLogin(id):arg1 expirationDate(id):arg2 params(id):arg3 ;
-(void)fbDialogNotLogin(BOOL):arg1 ;
@end
