/*
 * This header is generated by weak_classdump 0.2
 * on Saturday, October 18, 2014 at 2:28:39 AM Eastern Daylight Time
 * Operating System: Version 7.1.1 (Build 11D201)
 * weak_classdump is Freeware by Elias Limneos.
 *
 */


@interface FBRequestConnectionRetryManager : NSObject {
	FBRequestConnection* _requestConnection; 
	int _state; 
	FBSession* _sessionToReconnect; 
	NSString* _alertMessage; 
	NSMutableArray* _requestMetadatas; 
	FBRequestConnectionRetryManagerAlertViewHelper* _alertViewHelper; 
}
@property (assign,nonatomic) FBRequestConnection* requestConnection; 				//@synthesize requestConnection=_requestConnection - In the implementation block
@property (assign,nonatomic) int state; 				//@synthesize state=_state - In the implementation block
@property (nonatomic,retain) FBSession* sessionToReconnect; 				//@synthesize sessionToReconnect=_sessionToReconnect - In the implementation block
@property (nonatomic,copy) NSString* alertMessage; 				//@synthesize alertMessage=_alertMessage - In the implementation block
@property (nonatomic,retain) NSMutableArray* requestMetadatas; 				//@synthesize requestMetadatas=_requestMetadatas - In the implementation block
@property (nonatomic,retain) FBRequestConnectionRetryManagerAlertViewHelper* alertViewHelper; 				//@synthesize alertViewHelper=_alertViewHelper - In the implementation block
-(void)setRequestConnection:(id)arg1;
-(void)setAlertMessage:(id)arg1;
-(void)performRetries;
-(void)repairSuccess;
-(void)repairFailed;
-(id)initWithFBRequestConnection:(id)arg1;
-(void)addRequestMetadata:(id)arg1;
-(void)setSessionToReconnect:(id)arg1;
-(void)setRequestMetadatas:(id)arg1;
-(void)setAlertViewHelper:(id)arg1;
-(void)dealloc;
-(void)setState:(int)arg1;
@end