/*
 * This header is generated by weak_classdump 0.2
 * on Saturday, October 18, 2014 at 2:28:38 AM Eastern Daylight Time
 * Operating System: Version 7.1.1 (Build 11D201)
 * weak_classdump is Freeware by Elias Limneos.
 *
 */


@interface FBRequestHandlerFactory : NSObject {
}
+(id)handlerThatRetries:(id)arg1 forRequest:(id)arg2;
+(id)handlerThatAlertsUser:(id)arg1 forRequest:(id)arg2;
+(id)handlerThatReconnects:(id)arg1 forRequest:(id)arg2;
@end