/*
 * This header is generated by weak_classdump 0.2
 * on Saturday, October 18, 2014 at 2:28:31 AM Eastern Daylight Time
 * Operating System: Version 7.1.1 (Build 11D201)
 * weak_classdump is Freeware by Elias Limneos.
 *
 */


@interface FBSessionManualTokenCachingStrategy : FBSessionTokenCachingStrategy {
	NSString* _accessToken; 
	NSDate* _expirationDate; 
}
@property (copy) NSString* accessToken; 				//@synthesize accessToken=_accessToken - In the implementation block
@property (copy) NSDate* expirationDate; 				//@synthesize expirationDate=_expirationDate - In the implementation block
-(id)fetchTokenInformation;
-(void)clearToken;
-(void)cacheTokenInformation:(id)arg1;
-(void)setAccessToken:(id)arg1;
-(void)dealloc;
-(void)setExpirationDate:(id)arg1;
@end