/*
 * This header is generated by weak_classdump 0.2
 * on Saturday, October 18, 2014 at 2:28:30 AM Eastern Daylight Time
 * Operating System: Version 7.1.1 (Build 11D201)
 * weak_classdump is Freeware by Elias Limneos.
 *
 */


@interface FBSessionTokenCachingStrategy : NSObject {
	NSString* _accessTokenInformationKeyName; 
}
+(BOOL)isValidTokenInformation:(id)arg1;
+(id)nullCacheInstance;
+(id)defaultInstance;
-(id)fetchTokenInformation;
-(void)clearToken;
-(void)cacheTokenInformation:(id)arg1;
-(id)initWithUserDefaultTokenInformationKeyName:(id)arg1;
-(void)cacheFBAccessTokenData:(id)arg1;
-(id)fetchFBAccessTokenData;
-(void)dealloc;
-(id)init;
@end