/*
 * This header is generated by weak_classdump 0.2
 * on Saturday, October 18, 2014 at 2:28:30 AM Eastern Daylight Time
 * Operating System: Version 7.1.1 (Build 11D201)
 * weak_classdump is Freeware by Elias Limneos.
 *
 */

#import <FBSessionLoginStrategy.h>

@interface FBSessionSafariLoginStategy : NSObject <FBSessionLoginStrategy> {
}
@property (copy) NSString* methodName; 
-(BOOL)tryPerformAuthorizeWithParams:(id)arg1 session:(id)arg2 logger:(id)arg3;
@end