/*
 * This header is generated by weak_classdump 0.2
 * on Saturday, October 18, 2014 at 2:28:29 AM Eastern Daylight Time
 * Operating System: Version 7.1.1 (Build 11D201)
 * weak_classdump is Freeware by Elias Limneos.
 *
 */


@interface FBSessionUtility : NSObject {
}
+(id)queryParamsFromLoginURL:(id)arg1 appID:(id)arg2 urlSchemeSuffix:(id)arg3;
+(id)clientStateFromQueryParams:(id)arg1;
+(BOOL)logIfFoundUnexpectedPermissions:(id)arg1 isRead:(BOOL)arg2;
+(BOOL)isOpenSessionResponseURL:(id)arg1;
+(id)sessionStateDescription:(int)arg1;
+(void)addWebLoginStartTimeToParams:(id)arg1;
+(id)expirationDateFromResponseParams:(id)arg1;
+(BOOL)areRequiredPermissions:(id)arg1 aSubsetOfPermissions:(id)arg2;
+(void)validateRequestForPermissions:(id)arg1 defaultAudience:(int)arg2 allowSystemAccount:(BOOL)arg3 isRead:(BOOL)arg4;
@end