/*
 * This header is generated by weak_classdump 0.2
 * on Saturday, October 18, 2014 at 2:28:24 AM Eastern Daylight Time
 * Operating System: Version 7.1.1 (Build 11D201)
 * weak_classdump is Freeware by Elias Limneos.
 *
 */


@interface FBUserSettingsViewController : FBViewController {
	BOOL _attemptingLogin; 
	NSArray* _permissions; 
	NSArray* _readPermissions; 
	NSArray* _publishPermissions; 
	int _defaultAudience; 
	FBProfilePictureView* _profilePicture; 
	UIImageView* _backgroundImageView; 
	UILabel* _connectedStateLabel; 
	id<FBGraphUser> _me; 
	UIButton* _loginLogoutButton; 
	NSBundle* _bundle; 
	id _sessionStateHandler; 
	id _requestHandler; 
}
@property (nonatomic,copy) NSArray* permissions; 				//@synthesize permissions=_permissions - In the implementation block
@property (nonatomic,copy) NSArray* readPermissions; 				//@synthesize readPermissions=_readPermissions - In the implementation block
@property (nonatomic,copy) NSArray* publishPermissions; 				//@synthesize publishPermissions=_publishPermissions - In the implementation block
@property (assign,nonatomic) int defaultAudience; 				//@synthesize defaultAudience=_defaultAudience - In the implementation block
@property (nonatomic,retain) FBProfilePictureView* profilePicture; 				//@synthesize profilePicture=_profilePicture - In the implementation block
@property (nonatomic,retain) UIImageView* backgroundImageView; 				//@synthesize backgroundImageView=_backgroundImageView - In the implementation block
@property (nonatomic,retain) UILabel* connectedStateLabel; 				//@synthesize connectedStateLabel=_connectedStateLabel - In the implementation block
@property (nonatomic,retain) id<FBGraphUser> me; 				//@synthesize me=_me - In the implementation block
@property (nonatomic,retain) UIButton* loginLogoutButton; 				//@synthesize loginLogoutButton=_loginLogoutButton - In the implementation block
@property (assign,nonatomic) BOOL attemptingLogin; 				//@synthesize attemptingLogin=_attemptingLogin - In the implementation block
@property (nonatomic,retain) NSBundle* bundle; 				//@synthesize bundle=_bundle - In the implementation block
@property (nonatomic,copy) id sessionStateHandler; 				//@synthesize sessionStateHandler=_sessionStateHandler - In the implementation block
@property (nonatomic,copy) id requestHandler; 				//@synthesize requestHandler=_requestHandler - In the implementation block
-(void)setReadPermissions:(id)arg1;
-(void)setPublishPermissions:(id)arg1;
-(void)setSessionStateHandler:(id)arg1;
-(void)setRequestHandler:(id)arg1;
-(void)initializeBlocks;
-(void)setDefaultAudience:(int)arg1;
-(void)sessionStateChanged:(id)arg1 state:(int)arg2 error:(id)arg3;
-(void)updateControls;
-(void)setAttemptingLogin:(BOOL)arg1;
-(void)setProfilePicture:(id)arg1;
-(void)setConnectedStateLabel:(id)arg1;
-(void)setLoginLogoutButton:(id)arg1;
-(void)loginLogoutButtonPressed:(id)arg1;
-(void)openSession:(BOOL)arg1;
-(void)handleActiveSessionStateChanged:(id)arg1;
-(void)setPermissions:(id)arg1;
-(void)setBackgroundImageView:(id)arg1;
-(void)dealloc;
-(id)initWithCoder:(id)arg1;
-(id)init;
-(BOOL)shouldAutorotate;
-(unsigned)supportedInterfaceOrientations;
-(void)updateBackgroundImage;
-(id)initWithNibName:(id)arg1 bundle:(id)arg2;
-(void)viewWillAppear:(BOOL)arg1;
-(void)viewDidLoad;
-(void)viewDidUnload;
-(void)willRotateToInterfaceOrientation:(int)arg1 duration:(double)arg2;
-(void)setBundle:(id)arg1;
-(void)setMe:(id)arg1;
@end