/*
 * This header is generated by weak_classdump 0.2
 * on Saturday, October 18, 2014 at 2:28:25 AM Eastern Daylight Time
 * Operating System: Version 7.1.1 (Build 11D201)
 * weak_classdump is Freeware by Elias Limneos.
 *
 */


@interface FBUtility : NSObject {
}
+(id)stringAppBaseUrlFromAppId:(id)arg1 urlSchemeSuffix:(id)arg2;
+(id)queryParamsDictionaryFromFBURL:(id)arg1;
+(id)expirationDateFromExpirationTimeIntervalString:(id)arg1;
+(id)simpleJSONEncode:(id)arg1;
+(BOOL)isFacebookBundleIdentifier:(id)arg1;
+(id)dictionaryByParsingURLQueryPart:(id)arg1;
+(id)simpleJSONDecode:(id)arg1;
+(id)stringBySerializingQueryParameters:(id)arg1;
+(id)simpleJSONEncode:(id)arg1 error:(id*)arg2 writingOptions:(unsigned)arg3;
+(id)attributionID;
+(id)advertiserID;
+(void)updateParametersWithEventUsageLimitsAndBundleInfo:(id)arg1;
+(int)advertisingTrackingStatus;
+(id)stringFBIDFromObject:(id)arg1;
+(BOOL)isRetinaDisplay;
+(void)centerView:(id)arg1 tableView:(id)arg2;
+(id)graphObjectInArray:(id)arg1 withSameIDAs:(id)arg2;
+(unsigned long)currentTimeInMilliseconds;
+(id)localizedStringForKey:(id)arg1 withDefault:(id)arg2;
+(id)buildFacebookUrlWithPre:(id)arg1;
+(id)buildFacebookUrlWithPre:(id)arg1 withPost:(id)arg2;
+(id)stringByURLEncodingString:(id)arg1;
+(id)simpleJSONDecode:(id)arg1 error:(id*)arg2;
+(BOOL)isRegisteredURLScheme:(id)arg1;
+(id)newUUIDString;
+(id)fetchedAppSettings;
+(void)fetchAppSettings:(id)arg1 callback:(id)arg2;
+(BOOL)isSystemAccountStoreAvailable;
+(id)expirationDateFromExpirationUnixTimeString:(id)arg1;
+(BOOL)isPublishPermission:(id)arg1;
+(BOOL)areAllPermissionsReadPermissions:(id)arg1;
+(id)addBasicInfoPermission:(id)arg1;
+(id)localizedStringForKey:(id)arg1 withDefault:(id)arg2 inBundle:(id)arg3;
+(id)stringByURLDecodingString:(id)arg1;
+(id)facebookSDKBundle;
+(BOOL)isFetchedFBAppSettingsStale;
+(void)callTheFetchAppSettingsCallback:(id)arg1;
+(double)randomTimeInterval:(double)arg1 withMaxValue:(double)arg2;
+(id)dialogBaseURL;
+(void)deleteFacebookCookies;
+(BOOL)isMultitaskingSupported;
@end