/*
 * This header is generated by weak_classdump 0.2
 * on Saturday, October 18, 2014 at 2:28:23 AM Eastern Daylight Time
 * Operating System: Version 7.1.1 (Build 11D201)
 * weak_classdump is Freeware by Elias Limneos.
 *
 */


@interface FBWebDialogs : NSObject {
}
+(void)presentDialogModallyWithSession:(id)arg1 dialog:(id)arg2 parameters:(id)arg3 handler:(id)arg4 delegate:(id)arg5;
+(void)presentRequestsDialogModallyWithSession:(id)arg1 message:(id)arg2 title:(id)arg3 parameters:(id)arg4 handler:(id)arg5 friendCache:(id)arg6;
+(void)presentDialogModallyWithSession:(id)arg1 dialog:(id)arg2 parameters:(id)arg3 handler:(id)arg4;
+(void)presentRequestsDialogModallyWithSession:(id)arg1 message:(id)arg2 title:(id)arg3 parameters:(id)arg4 handler:(id)arg5;
+(void)presentFeedDialogModallyWithSession:(id)arg1 parameters:(id)arg2 handler:(id)arg3;
@end