/*
 * This header is generated by weak_classdump 0.2
 * on Saturday, October 18, 2014 at 2:29:01 AM Eastern Daylight Time
 * Operating System: Version 7.1.1 (Build 11D201)
 * weak_classdump is Freeware by Elias Limneos.
 *
 */


@protocol FBFrictionlessDialogSupportDelegate
@required
-(id)frictionlessSettings;
-(BOOL)frictionlessShouldMakeViewInvisible;
-(id)frictionlessSettings;
-(BOOL)frictionlessShouldMakeViewInvisible;
@end

@protocol FBWebDialogsDelegate
@optional
-(void)webDialogsWillPresentDialog(id):arg1 parameters(id):arg2 session(id):arg3 ;
-(BOOL)webDialogsDialog(id):arg1 parameters(id):arg2 session(id):arg3 shouldAutoHandleURL(id):arg4 ;
-(void)webDialogsWillDismissDialog(id):arg1 parameters(id):arg2 session(id):arg3 result(*):arg4 url(int):arg5 error(*):arg6 ;
@end
