/*
 * This header is generated by weak_classdump 0.2
 * on Saturday, October 18, 2014 at 2:25:03 AM Eastern Daylight Time
 * Operating System: Version 7.1.1 (Build 11D201)
 * weak_classdump is Freeware by Elias Limneos.
 *
 */


@interface FilterCell : UITableViewCell {
	BOOL _allergens; 
}
@property (assign,nonatomic) BOOL allergens; 				//@synthesize allergens=_allergens - In the implementation block
-(void)setAllergens:(BOOL)arg1;
-(void)setSelected:(BOOL)arg1 animated:(BOOL)arg2;
@end