/*
 * This header is generated by weak_classdump 0.2
 * on Saturday, October 18, 2014 at 2:24:44 AM Eastern Daylight Time
 * Operating System: Version 7.1.1 (Build 11D201)
 * weak_classdump is Freeware by Elias Limneos.
 *
 */


@interface Hours : _Hours {
}
+(id)createInContext:(id)arg1;
-(BOOL)isOpenToday;
-(id)daysOpen;
-(BOOL)isOpen;
-(int)dayOfWeek:(id)arg1;
@end