/*
 * This header is generated by weak_classdump 0.2
 * on Saturday, October 18, 2014 at 2:25:00 AM Eastern Daylight Time
 * Operating System: Version 7.1.1 (Build 11D201)
 * weak_classdump is Freeware by Elias Limneos.
 *
 */

#import <NSFetchedResultsControllerDelegate.h>

@interface HoursViewController : UITableViewController <NSFetchedResultsControllerDelegate> {
	NSMutableArray* dayHourStrings; 
	NSDateFormatter* timeFormatter; 
	NSArray* hoursData; 
}
@property (nonatomic,retain) NSArray* hoursData; 
-(void)setHoursData:(id)arg1;
-(void)setupHours;
-(void)doneAction:(id)arg1;
-(float)tableView:(id)arg1 heightForRowAtIndexPath:(id)arg2;
-(int)tableView:(id)arg1 numberOfRowsInSection:(int)arg2;
-(id)tableView:(id)arg1 cellForRowAtIndexPath:(id)arg2;
-(int)numberOfSectionsInTableView:(id)arg1;
-(void)viewDidLoad;
-(void).cxx_destruct;
@end