/*
 * This header is generated by weak_classdump 0.2
 * on Saturday, October 18, 2014 at 2:28:22 AM Eastern Daylight Time
 * Operating System: Version 7.1.1 (Build 11D201)
 * weak_classdump is Freeware by Elias Limneos.
 *
 */


@interface Hours_Hours_ : _Hours {
	unsigned[1] _cd_bits_0x14ed1f10; 
}
+(BOOL)automaticallyNotifiesObserversOfLocation;
+(id)_PFPlaceHolderSingleton;
+(id)_PFMOClassFactoryData;
+(Class)superclass;
+(Class)class;
+(BOOL)_isGeneratedClass;
+(void)release;
+(id)retain;
-(id)endTime;
-(id)startTime;
-(void)setEndTime:(id)arg1;
-(void)setStartTime:(id)arg1;
-(void)setDay:(id)arg1;
-(Class)class;
@end