/*
 * This header is generated by weak_classdump 0.2
 * on Saturday, October 18, 2014 at 2:25:18 AM Eastern Daylight Time
 * Operating System: Version 7.1.1 (Build 11D201)
 * weak_classdump is Freeware by Elias Limneos.
 *
 */


@interface IISideController : IIWrapController {
	float _constrainedSize; 
}
@property (assign,nonatomic) float constrainedSize; 				//@synthesize constrainedSize=_constrainedSize - In the implementation block
+(id)autoConstrainedSideControllerWithViewController:(id)arg1;
+(id)sideControllerWithViewController:(id)arg1 constrained:(float)arg2;
-(id)initWithViewController:(id)arg1 constrained:(float)arg2;
-(void)shrinkSide;
-(void)shrinkSideAnimated:(BOOL)arg1;
-(void)setConstrainedSize:(float)arg1 animated:(BOOL)arg2;
-(void)setConstrainedSize:(float)arg1;
-(void)viewWillAppear:(BOOL)arg1;
-(void)viewDidLoad;
-(void)willAnimateRotationToInterfaceOrientation:(int)arg1 duration:(double)arg2;
-(id)initWithViewController:(id)arg1;
@end