/*
 * This header is generated by weak_classdump 0.2
 * on Saturday, October 18, 2014 at 2:25:17 AM Eastern Daylight Time
 * Operating System: Version 7.1.1 (Build 11D201)
 * weak_classdump is Freeware by Elias Limneos.
 *
 */


@interface IIViewDeckView : UIView {
	BOOL _userInteractionEnabled; 
	BOOL _needsOffsetAdjustment; 
	BOOL _allowUserInteractionEnabled; 
}
@property (assign,nonatomic) BOOL allowUserInteractionEnabled; 				//@synthesize allowUserInteractionEnabled=_allowUserInteractionEnabled - In the implementation block
-(void)setNeedsOffsetAdjustment;
-(void)setAllowUserInteractionEnabled:(BOOL)arg1;
-(BOOL)needsOffsetAdjustment;
-(id)initWithFrame:(CGRect)arg1;
-(void)setUserInteractionEnabled:(BOOL)arg1;
-(id)initWithCoder:(id)arg1;
-(id)init;
@end