/*
 * This header is generated by weak_classdump 0.2
 * on Saturday, October 18, 2014 at 2:25:11 AM Eastern Daylight Time
 * Operating System: Version 7.1.1 (Build 11D201)
 * weak_classdump is Freeware by Elias Limneos.
 *
 */


@interface IIWrapController : UIViewController {
	UIViewController* _wrappedController; 
	id _onViewDidLoad; 
	id _onViewWillAppear; 
	id _onViewDidAppear; 
	id _onViewWillDisappear; 
	id _onViewDidDisappear; 
}
@property (nonatomic,retain,copy) UIViewController* wrappedController; 				//@synthesize wrappedController=_wrappedController - In the implementation block
@property (nonatomic,copy) id onViewDidLoad; 				//@synthesize onViewDidLoad=_onViewDidLoad - In the implementation block
@property (nonatomic,copy) id onViewWillAppear; 				//@synthesize onViewWillAppear=_onViewWillAppear - In the implementation block
@property (nonatomic,copy) id onViewDidAppear; 				//@synthesize onViewDidAppear=_onViewDidAppear - In the implementation block
@property (nonatomic,copy) id onViewWillDisappear; 				//@synthesize onViewWillDisappear=_onViewWillDisappear - In the implementation block
@property (nonatomic,copy) id onViewDidDisappear; 				//@synthesize onViewDidDisappear=_onViewDidDisappear - In the implementation block
-(void)setOnViewDidLoad:(id)arg1;
-(void)setOnViewWillAppear:(id)arg1;
-(void)setOnViewDidAppear:(id)arg1;
-(void)setOnViewWillDisappear:(id)arg1;
-(void)setOnViewDidDisappear:(id)arg1;
-(void)dealloc;
-(BOOL)respondsToSelector:(SEL)arg1;
-(void)didReceiveMemoryWarning;
-(BOOL)shouldAutorotate;
-(unsigned)supportedInterfaceOrientations;
-(float)statusBarHeight;
-(void)loadView;
-(id)forwardingTargetForSelector:(SEL)arg1;
-(BOOL)shouldAutorotateToInterfaceOrientation:(int)arg1;
-(void)viewWillAppear:(BOOL)arg1;
-(void)viewDidLoad;
-(void)viewDidUnload;
-(BOOL)shouldAutomaticallyForwardRotationMethods;
-(BOOL)automaticallyForwardAppearanceAndRotationMethodsToChildViewControllers;
-(BOOL)shouldAutomaticallyForwardAppearanceMethods;
-(void)viewDidAppear:(BOOL)arg1;
-(void)viewWillDisappear:(BOOL)arg1;
-(void)viewDidDisappear:(BOOL)arg1;
-(void)willRotateToInterfaceOrientation:(int)arg1 duration:(double)arg2;
-(void)willAnimateRotationToInterfaceOrientation:(int)arg1 duration:(double)arg2;
-(void)willAnimateFirstHalfOfRotationToInterfaceOrientation:(int)arg1 duration:(double)arg2;
-(void)willAnimateSecondHalfOfRotationFromInterfaceOrientation:(int)arg1 duration:(double)arg2;
-(void)didRotateFromInterfaceOrientation:(int)arg1;
-(id)tabBarItem;
-(void)setTabBarItem:(id)arg1;
-(BOOL)hidesBottomBarWhenPushed;
-(void)setHidesBottomBarWhenPushed:(BOOL)arg1;
-(void).cxx_destruct;
-(id)initWithViewController:(id)arg1;
@end