/*
 * This header is generated by weak_classdump 0.2
 * on Saturday, October 18, 2014 at 2:28:00 AM Eastern Daylight Time
 * Operating System: Version 7.1.1 (Build 11D201)
 * weak_classdump is Freeware by Elias Limneos.
 *
 */


@interface KGNoiseLinearGradientView : KGNoiseView {
	UIColor* _alternateBackgroundColor; 
	unsigned _gradientDirection; 
}
@property (nonatomic,retain) UIColor* alternateBackgroundColor; 				//@synthesize alternateBackgroundColor=_alternateBackgroundColor - In the implementation block
@property (assign,nonatomic) unsigned gradientDirection; 				//@synthesize gradientDirection=_gradientDirection - In the implementation block
-(void)setGradientDirection:(unsigned)arg1;
-(void)setAlternateBackgroundColor:(id)arg1;
-(void)drawRect:(CGRect)arg1;
-(void).cxx_destruct;
-(void)setup;
@end