/*
 * This header is generated by weak_classdump 0.2
 * on Saturday, October 18, 2014 at 2:27:58 AM Eastern Daylight Time
 * Operating System: Version 7.1.1 (Build 11D201)
 * weak_classdump is Freeware by Elias Limneos.
 *
 */


@interface KGNoiseRadialGradientView : KGNoiseView {
	UIColor* _alternateBackgroundColor; 
}
@property (nonatomic,retain) UIColor* alternateBackgroundColor; 				//@synthesize alternateBackgroundColor=_alternateBackgroundColor - In the implementation block
-(void)setAlternateBackgroundColor:(id)arg1;
-(void)drawRect:(CGRect)arg1;
-(void).cxx_destruct;
@end