/*
 * This header is generated by weak_classdump 0.2
 * on Saturday, October 18, 2014 at 2:27:59 AM Eastern Daylight Time
 * Operating System: Version 7.1.1 (Build 11D201)
 * weak_classdump is Freeware by Elias Limneos.
 *
 */


@interface KGNoiseView : UIView {
	float _noiseOpacity; 
	int _noiseBlendMode; 
}
@property (assign,nonatomic) float noiseOpacity; 				//@synthesize noiseOpacity=_noiseOpacity - In the implementation block
@property (assign,nonatomic) int noiseBlendMode; 				//@synthesize noiseBlendMode=_noiseBlendMode - In the implementation block
-(void)setNoiseOpacity:(float)arg1;
-(void)setNoiseBlendMode:(int)arg1;
-(id)initWithFrame:(CGRect)arg1;
-(void)drawRect:(CGRect)arg1;
-(id)initWithCoder:(id)arg1;
-(void)setup;
@end