/*
 * This header is generated by weak_classdump 0.2
 * on Saturday, October 18, 2014 at 2:25:07 AM Eastern Daylight Time
 * Operating System: Version 7.1.1 (Build 11D201)
 * weak_classdump is Freeware by Elias Limneos.
 *
 */

#import <NSFetchedResultsControllerDelegate.h>

@interface LeftMenuViewController : UITableViewController <NSFetchedResultsControllerDelegate> {
	NSArray* templateImages; 
	FBProfilePictureView* profileImage; 
	UILabel* profileName; 
	NSDictionary* userData; 
	NSFetchedResultsController* resultController; 
	NSMutableArray* locations; 
	NSMutableSet* usedLocs; 
}
-(void)setupLocations;
-(void)fetchLocations;
-(void)tableView:(id)arg1 didSelectRowAtIndexPath:(id)arg2;
-(int)tableView:(id)arg1 numberOfRowsInSection:(int)arg2;
-(id)tableView:(id)arg1 cellForRowAtIndexPath:(id)arg2;
-(int)numberOfSectionsInTableView:(id)arg1;
-(id)tableView:(id)arg1 titleForHeaderInSection:(int)arg2;
-(void)viewWillAppear:(BOOL)arg1;
-(void)viewDidLoad;
-(void).cxx_destruct;
@end