/*
 * This header is generated by weak_classdump 0.2
 * on Saturday, October 18, 2014 at 2:24:43 AM Eastern Daylight Time
 * Operating System: Version 7.1.1 (Build 11D201)
 * weak_classdump is Freeware by Elias Limneos.
 *
 */


@interface Location_Location_ : _Location {
	unsigned[1] _cd_bits_0x14eba880; 
}
+(BOOL)automaticallyNotifiesObserversOfMeals;
+(BOOL)automaticallyNotifiesObserversOfHours;
+(id)_PFPlaceHolderSingleton;
+(id)_PFMOClassFactoryData;
+(Class)superclass;
+(Class)class;
+(BOOL)_isGeneratedClass;
+(void)release;
+(id)retain;
-(void)setCoreDataUpdated:(id)arg1;
-(void)addMealsObject:(id)arg1;
-(void)setHours:(id)arg1;
-(void)setHoursString:(id)arg1;
-(Class)class;
@end