/*
 * This header is generated by weak_classdump 0.2
 * on Saturday, October 18, 2014 at 2:27:45 AM Eastern Daylight Time
 * Operating System: Version 7.1.1 (Build 11D201)
 * weak_classdump is Freeware by Elias Limneos.
 *
 */


@interface LocationHoursCell : UITableViewCell {
	UILabel* _dayLabel; 
	UILabel* _timeLabel; 
}
@property (nonatomic,retain) UILabel* dayLabel; 				//@synthesize dayLabel=_dayLabel - In the implementation block
@property (nonatomic,retain) UILabel* timeLabel; 				//@synthesize timeLabel=_timeLabel - In the implementation block
-(void)setDayLabel:(id)arg1;
-(void)setTimeLabel:(id)arg1;
-(id)initWithStyle:(int)arg1 reuseIdentifier:(id)arg2;
-(void)setSelected:(BOOL)arg1 animated:(BOOL)arg2;
-(void).cxx_destruct;
@end