/*
 * This header is generated by weak_classdump 0.2
 * on Saturday, October 18, 2014 at 2:25:01 AM Eastern Daylight Time
 * Operating System: Version 7.1.1 (Build 11D201)
 * weak_classdump is Freeware by Elias Limneos.
 *
 */


@interface LoginViewController : UITableViewController {
}
-(void)loginSuccess;
-(void)login:(id)arg1;
-(void)viewDidLoad;
-(void)viewDidAppear:(BOOL)arg1;
@end