/*
 * This header is generated by weak_classdump 0.2
 * on Saturday, October 18, 2014 at 2:25:04 AM Eastern Daylight Time
 * Operating System: Version 7.1.1 (Build 11D201)
 * weak_classdump is Freeware by Elias Limneos.
 *
 */

#import <UITextFieldDelegate.h>

@interface LoginVerifyStudentViewController : UITableViewController <UITextFieldDelegate> {
	UITextField* emailTextField; 
}
-(void)continueAction:(id)arg1;
-(BOOL)textFieldShouldReturn:(id)arg1;
-(void)viewDidLoad;
-(void).cxx_destruct;
@end