/*
 * This header is generated by weak_classdump 0.2
 * on Saturday, October 18, 2014 at 2:27:58 AM Eastern Daylight Time
 * Operating System: Version 7.1.1 (Build 11D201)
 * weak_classdump is Freeware by Elias Limneos.
 *
 */


@interface MagicalRecord : NSObject {
}
+(void)saveWithBlockAndWait:(id)arg1;
+(void)saveWithBlock:(id)arg1 completion:(id)arg2;
+(id)defaultStoreName;
+(void)setupCoreDataStack;
+(void)saveInBackgroundWithBlock:(id)arg1;
+(void)saveWithBlock:(id)arg1;
+(void)saveUsingCurrentThreadContextWithBlock:(id)arg1 completion:(id)arg2;
+(void)saveUsingCurrentThreadContextWithBlockAndWait:(id)arg1;
+(void)saveInBackgroundWithBlock:(id)arg1 completion:(id)arg2;
+(void)saveInBackgroundUsingCurrentContextWithBlock:(id)arg1 completion:(id)arg2 errorHandler:(id)arg3;
+(void)defaultErrorHandler:(id)arg1;
+(void)handleErrors:(id)arg1;
+(id)errorHandlerTarget;
+(SEL)errorHandlerAction;
+(void)setErrorHandlerTarget:(id)arg1 action:(SEL)arg2;
+(BOOL)shouldAutoCreateManagedObjectModel;
+(BOOL)shouldAutoCreateDefaultPersistentStoreCoordinator;
+(BOOL)shouldDeleteStoreOnModelMismatch;
+(void)setupCoreDataStackWithStoreNamed:(id)arg1;
+(void)setupCoreDataStackWithAutoMigratingSqliteStoreNamed:(id)arg1;
+(void)setupAutoMigratingCoreDataStack;
+(void)setupCoreDataStackWithInMemoryStore;
+(BOOL)MR_resolveClassMethod:(SEL)arg1;
+(BOOL)MR_resolveInstanceMethod:(SEL)arg1;
+(void)updateResolveMethodsForClass:(Class)arg1;
+(void)setupCoreDataStackWithiCloudContainer:(id)arg1 contentNameKey:(id)arg2 localStoreNamed:(id)arg3 cloudStorePathComponent:(id)arg4;
+(void)setupCoreDataStackWithiCloudContainer:(id)arg1 contentNameKey:(id)arg2 localStoreNamed:(id)arg3 cloudStorePathComponent:(id)arg4 completion:(id)arg5;
+(BOOL)isICloudEnabled;
+(void)setICloudEnabled:(BOOL)arg1;
+(void)setupCoreDataStackWithiCloudContainer:(id)arg1 localStoreNamed:(id)arg2;
+(void)cleanUpErrorHanding;
+(void)cleanUpStack;
+(void)swizzleShorthandMethods;
+(void)setShouldAutoCreateManagedObjectModel:(BOOL)arg1;
+(void)setShouldAutoCreateDefaultPersistentStoreCoordinator:(BOOL)arg1;
+(void)setShouldDeleteStoreOnModelMismatch:(BOOL)arg1;
+(id)currentStack;
+(void)setDefaultModelNamed:(id)arg1;
+(void)setDefaultModelFromClass:(Class)arg1;
+(void)initialize;
+(void)cleanUp;
-(void)handleErrors:(id)arg1;
@end