/*
 * This header is generated by weak_classdump 0.2
 * on Saturday, October 18, 2014 at 2:28:51 AM Eastern Daylight Time
 * Operating System: Version 7.1.1 (Build 11D201)
 * weak_classdump is Freeware by Elias Limneos.
 *
 */


@interface Meal_Meal_ : _Meal {
	unsigned[1] _cd_bits_0x14ddf0a0; 
}
+(BOOL)automaticallyNotifiesObserversOfFood;
+(BOOL)automaticallyNotifiesObserversOfLocation;
+(id)_PFPlaceHolderSingleton;
+(id)_PFMOClassFactoryData;
+(Class)superclass;
+(Class)class;
+(BOOL)_isGeneratedClass;
+(void)release;
+(id)retain;
-(void)setCoreDataUpdated:(id)arg1;
-(Class)class;
@end