/*
 * This header is generated by weak_classdump 0.2
 * on Saturday, October 18, 2014 at 2:25:04 AM Eastern Daylight Time
 * Operating System: Version 7.1.1 (Build 11D201)
 * weak_classdump is Freeware by Elias Limneos.
 *
 */


@interface MealPlanValueCell : UITableViewCell {
	UILabel* _title; 
	UILabel* _value; 
}
@property (nonatomic,retain) UILabel* title; 				//@synthesize title=_title - In the implementation block
@property (nonatomic,retain) UILabel* value; 				//@synthesize value=_value - In the implementation block
-(id)initWithStyle:(int)arg1 reuseIdentifier:(id)arg2;
-(void)setTitle:(id)arg1;
-(void)setValue:(id)arg1;
-(void)setSelected:(BOOL)arg1 animated:(BOOL)arg2;
-(void).cxx_destruct;
@end