/*
 * This header is generated by weak_classdump 0.2
 * on Saturday, October 18, 2014 at 2:25:01 AM Eastern Daylight Time
 * Operating System: Version 7.1.1 (Build 11D201)
 * weak_classdump is Freeware by Elias Limneos.
 *
 */

#import <CPTBarPlotDataSource.h>

@interface MealPlanSpendingTimeCell : UITableViewCell <CPTBarPlotDataSource> {
	CPTXYGraph* barChart; 
	NSDictionary* barData; 
	NSArray* colors; 
	CPTGraphHostingView* _hourlyBarGraph; 
	NSFetchedResultsController* _resultController; 
}
@property (nonatomic,retain) CPTGraphHostingView* hourlyBarGraph; 				//@synthesize hourlyBarGraph=_hourlyBarGraph - In the implementation block
@property (nonatomic,retain) NSFetchedResultsController* resultController; 				//@synthesize resultController=_resultController - In the implementation block
-(float)setupBarData;
-(id)barFillForBarPlot:(id)arg1 recordIndex:(unsigned)arg2;
-(unsigned)numberOfRecordsForPlot:(id)arg1;
-(id)numberForPlot:(id)arg1 field:(unsigned)arg2 recordIndex:(unsigned)arg3;
-(void)setupBarGraph;
-(void)setHourlyBarGraph:(id)arg1;
-(void)setResultController:(id)arg1;
-(id)initWithStyle:(int)arg1 reuseIdentifier:(id)arg2;
-(void)setSelected:(BOOL)arg1 animated:(BOOL)arg2;
-(void).cxx_destruct;
@end