/*
 * This header is generated by weak_classdump 0.2
 * on Saturday, October 18, 2014 at 2:24:52 AM Eastern Daylight Time
 * Operating System: Version 7.1.1 (Build 11D201)
 * weak_classdump is Freeware by Elias Limneos.
 *
 */


@interface MenuCell : UITableViewCell {
	UILabel* foodNameLabel; 
	UILabel* downVoteLabel; 
	UILabel* upVoteLabel; 
	UIImageView* upThumb; 
	UIImageView* downThumb; 
	Food* currentFood; 
	BOOL submitting; 
}
-(void)configureForFoodItem:(id)arg1;
-(void)updateVoteText;
-(void)getCurrentVote;
-(void)updateParseVote:(id)arg1;
-(id)createVoteIfNeeded:(id)arg1;
-(void)upVoteAction:(id)arg1;
-(void)downVoteAction:(id)arg1;
-(id)initWithStyle:(int)arg1 reuseIdentifier:(id)arg2;
-(void).cxx_destruct;
@end