/*
 * This header is generated by weak_classdump 0.2
 * on Saturday, October 18, 2014 at 2:27:52 AM Eastern Daylight Time
 * Operating System: Version 7.1.1 (Build 11D201)
 * weak_classdump is Freeware by Elias Limneos.
 *
 */


@interface MVBarTender : NSObject {
}
+(void)customizeNavBar:(id)arg1 withTintColor:(id)arg2;
+(id)backgroundImageForTintColor:(id)arg1 darkerColor:(id)arg2 barPosition:(int)arg3 barHeight:(float)arg4;
+(void)customizeToolBar:(id)arg1 withTintColor:(id)arg2;
+(void)customizeTabBar:(id)arg1 withTintColor:(id)arg2 forNumberOfTabs:(unsigned)arg3;
+(id)selectedImageForNumberOfTabs:(unsigned)arg1;
+(id)renderViewToImage:(id)arg1;
+(void)customizeNavBarWithDefaults:(id)arg1;
+(void)customizeToolBarWithDefaults:(id)arg1;
+(void)customizeTabBarWithDefaults:(id)arg1 forNumberOfTabs:(unsigned)arg2;
@end