/*
 * This header is generated by weak_classdump 0.2
 * on Saturday, October 18, 2014 at 2:27:52 AM Eastern Daylight Time
 * Operating System: Version 7.1.1 (Build 11D201)
 * weak_classdump is Freeware by Elias Limneos.
 *
 */


@interface MVCustomDisclosureIndicator : UIControl {
	UIColor* accessoryColor; 
	UIColor* highlightedColor; 
}
@property (nonatomic,retain) UIColor* accessoryColor; 
@property (nonatomic,retain) UIColor* highlightedColor; 
+(id)accessoryWithColor:(id)arg1;
-(void)setAccessoryColor:(id)arg1;
-(id)initWithFrame:(CGRect)arg1;
-(void)drawRect:(CGRect)arg1;
-(void)setHighlighted:(BOOL)arg1;
-(void)setHighlightedColor:(id)arg1;
-(void).cxx_destruct;
@end