/*
 * This header is generated by weak_classdump 0.2
 * on Saturday, October 18, 2014 at 2:27:51 AM Eastern Daylight Time
 * Operating System: Version 7.1.1 (Build 11D201)
 * weak_classdump is Freeware by Elias Limneos.
 *
 */


@protocol MVFormatter
@optional
+(id)seperatedStringsFromFromattedString(id):arg1 ;
@required
+(id)formattedStringFromUnformattedString(id):arg1 ;
@end
