/*
 * This header is generated by weak_classdump 0.2
 * on Saturday, October 18, 2014 at 2:27:51 AM Eastern Daylight Time
 * Operating System: Version 7.1.1 (Build 11D201)
 * weak_classdump is Freeware by Elias Limneos.
 *
 */


@interface MVGradientView : UIView {
	int _gradientDirection; 
	NSArray* _colors; 
	float _noiseOpacity; 
}
@property (assign,nonatomic) int gradientDirection; 				//@synthesize gradientDirection=_gradientDirection - In the implementation block
@property (nonatomic,retain) NSArray* colors; 				//@synthesize colors=_colors - In the implementation block
@property (assign,nonatomic) float noiseOpacity; 				//@synthesize noiseOpacity=_noiseOpacity - In the implementation block
-(void)setNoiseOpacity:(float)arg1;
-(void)setGradientDirection:(int)arg1;
-(id)initWithFrame:(CGRect)arg1;
-(void)drawRect:(CGRect)arg1;
-(id)initWithCoder:(id)arg1;
-(void)setColors:(id)arg1;
-(void).cxx_destruct;
@end