/*
 * This header is generated by weak_classdump 0.2
 * on Saturday, October 18, 2014 at 2:27:49 AM Eastern Daylight Time
 * Operating System: Version 7.1.1 (Build 11D201)
 * weak_classdump is Freeware by Elias Limneos.
 *
 */


@interface MVSingleItemEditor : UIViewController {
	id startValue; 
	id object; 
	NSString* key; 
	NSString* placeholderText; 
	NSString* subtitle; 
	int mode; 
	int keyboardType; 
	NSArray* listItems; 
	NSArray* listItems2; 
	BOOL pickDate; 
	BOOL pickTime; 
	NSDateFormatter* dateFormatter; 
	UITextField* editField; 
	UIPickerView* listPicker; 
	UIDatePicker* datePicker; 
	UITableView* singleItemTableView; 
	BOOL phoneManualEdit; 
	BOOL showSaveButton; 
	int maxCharacters; 
	NSString* backgroundImage; 
	int keyboardAppearance; 
	UIColor* editFieldBackgroundColor; 
	UIColor* saveButtonTintColor; 
	id<MVSingleItemEditorDelegate> delegate; 
	id _formatter; 
}
@property (nonatomic,retain) id startValue; 
@property (nonatomic,retain) id object; 
@property (nonatomic,retain) id formatter; 				//@synthesize formatter=_formatter - In the implementation block
@property (nonatomic,retain) NSString* key; 
@property (nonatomic,retain) NSString* placeholderText; 
@property (nonatomic,retain) NSString* subtitle; 
@property (assign,nonatomic) int mode; 
@property (assign,nonatomic) int keyboardType; 
@property (assign,nonatomic) int keyboardAppearance; 
@property (nonatomic,retain) NSArray* listItems; 
@property (nonatomic,retain) NSArray* listItems2; 
@property (assign,nonatomic) BOOL pickDate; 
@property (assign,nonatomic) BOOL pickTime; 
@property (assign,nonatomic) BOOL showSaveButton; 
@property (assign,nonatomic) int maxCharacters; 
@property (assign,nonatomic,__weak) id<MVSingleItemEditorDelegate> delegate; 
@property (nonatomic,retain) NSString* backgroundImage; 
@property (nonatomic,retain) UIColor* editFieldBackgroundColor; 
@property (nonatomic,retain) UIColor* saveButtonTintColor; 
-(void)setListItems:(id)arg1;
-(void)saveAction;
-(void)writeValueBackToObject;
-(void)stringUpdated:(id)arg1;
-(void)setListItems2:(id)arg1;
-(void)setPickDate:(BOOL)arg1;
-(void)setPickTime:(BOOL)arg1;
-(void)setShowSaveButton:(BOOL)arg1;
-(void)setMaxCharacters:(int)arg1;
-(void)setEditFieldBackgroundColor:(id)arg1;
-(void)setSaveButtonTintColor:(id)arg1;
-(void)setDelegate:(id)arg1;
-(int)numberOfComponentsInPickerView:(id)arg1;
-(int)pickerView:(id)arg1 numberOfRowsInComponent:(int)arg2;
-(id)pickerView:(id)arg1 titleForRow:(int)arg2 forComponent:(int)arg3;
-(id)init;
-(void)pickerView:(id)arg1 didSelectRow:(int)arg2 inComponent:(int)arg3;
-(int)tableView:(id)arg1 numberOfRowsInSection:(int)arg2;
-(id)tableView:(id)arg1 cellForRowAtIndexPath:(id)arg2;
-(int)numberOfSectionsInTableView:(id)arg1;
-(id)tableView:(id)arg1 titleForHeaderInSection:(int)arg2;
-(void)setKeyboardType:(int)arg1;
-(void)setKeyboardAppearance:(int)arg1;
-(void)viewWillAppear:(BOOL)arg1;
-(void)viewDidUnload;
-(void)viewDidAppear:(BOOL)arg1;
-(void)viewWillDisappear:(BOOL)arg1;
-(void)setBackgroundImage:(id)arg1;
-(void)setMode:(int)arg1;
-(void)setSubtitle:(id)arg1;
-(void)setObject:(id)arg1;
-(void)setStartValue:(id)arg1;
-(void)setKey:(id)arg1;
-(void).cxx_destruct;
-(void)setPlaceholderText:(id)arg1;
-(void)setFormatter:(id)arg1;
-(void)dateUpdated;
-(void)cancelAction;
@end