/*
 * This header is generated by weak_classdump 0.2
 * on Saturday, October 18, 2014 at 2:27:48 AM Eastern Daylight Time
 * Operating System: Version 7.1.1 (Build 11D201)
 * weak_classdump is Freeware by Elias Limneos.
 *
 */

#import <UIWebViewDelegate.h>
#import <UITextFieldDelegate.h>
#import <UIToolbarDelegate.h>

@interface MVSimpleWebBrowser : UIViewController <UIWebViewDelegate, UITextFieldDelegate, UIToolbarDelegate> {
	UIWebView* webView; 
	UIActivityIndicatorView* loadingIndicator; 
	UITextField* URLTextField; 
	UIToolbar* topBar; 
	UIToolbar* bottomBar; 
	UIBarButtonItem* backButton; 
	UIBarButtonItem* forwardButton; 
	UIBarButtonItem* stopButton; 
	NSURL* URLToLoad; 
	NSString* customJavascriptToInject; 
	NSString* barTitle; 
	BOOL _printingEnabled; 
}
@property (assign,nonatomic) BOOL printingEnabled; 				//@synthesize printingEnabled=_printingEnabled - In the implementation block
@property (nonatomic,retain) NSURL* URLToLoad; 
@property (nonatomic,retain) NSString* customJavascriptToInject; 
@property (nonatomic,retain) NSString* barTitle; 
-(id)initForLoadingURL:(id)arg1;
-(void)doneAction;
-(void)actionAction:(id)arg1;
-(void)disableBottomToolbar;
-(void)setURLToLoad:(id)arg1;
-(void)setCustomJavascriptToInject:(id)arg1;
-(void)setBarTitle:(id)arg1;
-(void)setPrintingEnabled:(BOOL)arg1;
-(void)dealloc;
-(void)setTintColor:(id)arg1;
-(int)positionForBar:(id)arg1;
-(id)initWithNibName:(id)arg1 bundle:(id)arg2;
-(BOOL)textFieldShouldReturn:(id)arg1;
-(BOOL)shouldAutorotateToInterfaceOrientation:(int)arg1;
-(void)viewWillAppear:(BOOL)arg1;
-(void)viewDidLoad;
-(void)viewWillDisappear:(BOOL)arg1;
-(void)webView:(id)arg1 didFailLoadWithError:(id)arg2;
-(BOOL)webView:(id)arg1 shouldStartLoadWithRequest:(id)arg2 navigationType:(int)arg3;
-(void)webViewDidStartLoad:(id)arg1;
-(void)webViewDidFinishLoad:(id)arg1;
-(void).cxx_destruct;
@end