/*
 * This header is generated by weak_classdump 0.2
 * on Saturday, October 18, 2014 at 2:25:11 AM Eastern Daylight Time
 * Operating System: Version 7.1.1 (Build 11D201)
 * weak_classdump is Freeware by Elias Limneos.
 *
 */


@interface NavLocationCell : UITableViewCell {
	UILabel* _locationNameLabel; 
	UIImageView* _locationImage; 
}
@property (nonatomic,retain) UILabel* locationNameLabel; 				//@synthesize locationNameLabel=_locationNameLabel - In the implementation block
@property (nonatomic,retain) UIImageView* locationImage; 				//@synthesize locationImage=_locationImage - In the implementation block
-(void)configureForLocation:(id)arg1;
-(void)setLocationNameLabel:(id)arg1;
-(void)setLocationImage:(id)arg1;
-(id)initWithStyle:(int)arg1 reuseIdentifier:(id)arg2;
-(void)setSelected:(BOOL)arg1 animated:(BOOL)arg2;
-(void).cxx_destruct;
@end