/*
 * This header is generated by weak_classdump 0.2
 * on Saturday, October 18, 2014 at 2:24:44 AM Eastern Daylight Time
 * Operating System: Version 7.1.1 (Build 11D201)
 * weak_classdump is Freeware by Elias Limneos.
 *
 */


@interface NavProfileCell : UITableViewCell {
	UILabel* _profileNameLabel; 
	FBProfilePictureView* _profileImage; 
}
@property (nonatomic,retain) UILabel* profileNameLabel; 				//@synthesize profileNameLabel=_profileNameLabel - In the implementation block
@property (nonatomic,retain) FBProfilePictureView* profileImage; 				//@synthesize profileImage=_profileImage - In the implementation block
-(void)configureForFacebookUser;
-(void)setProfileNameLabel:(id)arg1;
-(void)setProfileImage:(id)arg1;
-(id)initWithStyle:(int)arg1 reuseIdentifier:(id)arg2;
-(void)setSelected:(BOOL)arg1 animated:(BOOL)arg2;
-(void).cxx_destruct;
@end