/*
 * This header is generated by weak_classdump 0.2
 * on Saturday, October 18, 2014 at 2:29:12 AM Eastern Daylight Time
 * Operating System: Version 7.1.1 (Build 11D201)
 * weak_classdump is Freeware by Elias Limneos.
 *
 */


@protocol NSFastEnumeration
@required
-(unsigned)countByEnumeratingWithState(*):arg1 objects({):arg2 count(?):arg3 ;
-(unsigned)countByEnumeratingWithState(*):arg1 objects({):arg2 count(?):arg3 ;
@end
