/*
 * This header is generated by weak_classdump 0.2
 * on Saturday, October 18, 2014 at 2:28:39 AM Eastern Daylight Time
 * Operating System: Version 7.1.1 (Build 11D201)
 * weak_classdump is Freeware by Elias Limneos.
 *
 */


@interface NSKVONotifying_UINavigationController : UINavigationController {
}
-(void)setTitle:(id)arg1;
-(Class)class;
-(void)dealloc;
-(BOOL)_isKVOA;
@end