/*
 * This header is generated by weak_classdump 0.2
 * on Saturday, October 18, 2014 at 2:25:02 AM Eastern Daylight Time
 * Operating System: Version 7.1.1 (Build 11D201)
 * weak_classdump is Freeware by Elias Limneos.
 *
 */


@protocol NSCoding
@required
-(id)initWithCoder(id):arg1 ;
-(void)encodeWithCoder(id):arg1 ;
-(id)initWithCoder(id):arg1 ;
-(void)encodeWithCoder(id):arg1 ;
@end

@protocol NSCopying
@required
-(id)copyWithZone(*):arg1 ;
-(id)copyWithZone(*):arg1 ;
@end

@protocol NSMutableCopying
@required
-(id)mutableCopyWithZone(*):arg1 ;
-(id)mutableCopyWithZone(*):arg1 ;
@end
