/*
 * This header is generated by weak_classdump 0.2
 * on Saturday, October 18, 2014 at 2:28:08 AM Eastern Daylight Time
 * Operating System: Version 7.1.1 (Build 11D201)
 * weak_classdump is Freeware by Elias Limneos.
 *
 */


@protocol NSURLConnectionDelegate
@optional
-(void)connection(id):arg1 didFailWithError(id):arg2 ;
-(BOOL)connectionShouldUseCredentialStorage(id):arg1 ;
-(void)connection(id):arg1 willSendRequestForAuthenticationChallenge(id):arg2 ;
-(BOOL)connection(id):arg1 canAuthenticateAgainstProtectionSpace(id):arg2 ;
-(void)connection(id):arg1 didReceiveAuthenticationChallenge(id):arg2 ;
-(void)connection(id):arg1 didCancelAuthenticationChallenge(id):arg2 ;
@end
