/*
 * This header is generated by weak_classdump 0.2
 * on Saturday, October 18, 2014 at 2:27:56 AM Eastern Daylight Time
 * Operating System: Version 7.1.1 (Build 11D201)
 * weak_classdump is Freeware by Elias Limneos.
 *
 */


@interface OpenInChromeController : NSObject {
}
+(id)sharedInstance;
-(BOOL)openInChrome:(id)arg1 withCallbackURL:(id)arg2 createNewTab:(BOOL)arg3;
-(BOOL)isChromeInstalled;
-(BOOL)openInChrome:(id)arg1;
@end