/*
 * This header is generated by weak_classdump 0.2
 * on Saturday, October 18, 2014 at 2:29:01 AM Eastern Daylight Time
 * Operating System: Version 7.1.1 (Build 11D201)
 * weak_classdump is Freeware by Elias Limneos.
 *
 */


@interface Parse : NSObject {
}
+(void)setApplicationId:(id)arg1 clientKey:(id)arg2;
+(id)getApplicationId;
+(id)getClientKey;
+(void)offlineMessagesEnabled:(BOOL)arg1;
+(void)errorMessagesEnabled:(BOOL)arg1;
@end