/*
 * This header is generated by weak_classdump 0.2
 * on Saturday, October 18, 2014 at 2:27:56 AM Eastern Daylight Time
 * Operating System: Version 7.1.1 (Build 11D201)
 * weak_classdump is Freeware by Elias Limneos.
 *
 */


@interface PDKeychainBindingsController : NSObject {
	PDKeychainBindings* _keychainBindings; 
	NSMutableDictionary* _valueBuffer; 
}
+(id)sharedKeychainBindingsController;
-(id)keychainBindings;
-(BOOL)storeString:(id)arg1 forKey:(id)arg2;
-(id)serviceName;
-(id)stringForKey:(id)arg1;
-(id)valueForKeyPath:(id)arg1;
-(void)setValue:(id)arg1 forKeyPath:(id)arg2;
-(id)values;
-(void).cxx_destruct;
@end