/*
 * This header is generated by weak_classdump 0.2
 * on Saturday, October 18, 2014 at 2:27:56 AM Eastern Daylight Time
 * Operating System: Version 7.1.1 (Build 11D201)
 * weak_classdump is Freeware by Elias Limneos.
 *
 */


@interface PDKeychainBindings : NSObject {
}
+(id)sharedKeychainBindings;
-(void)removeObjectForKey:(id)arg1;
-(id)stringForKey:(id)arg1;
-(void)setString:(id)arg1 forKey:(id)arg2;
-(id)objectForKey:(id)arg1;
-(void)setObject:(id)arg1 forKey:(id)arg2;
@end