/*
 * This header is generated by weak_classdump 0.2
 * on Saturday, October 18, 2014 at 2:28:12 AM Eastern Daylight Time
 * Operating System: Version 7.1.1 (Build 11D201)
 * weak_classdump is Freeware by Elias Limneos.
 *
 */


@interface PF_AFJSONRequestOperation : PF_AFHTTPRequestOperation {
	id _responseJSON; 
	NSError* _JSONError; 
}
@property (nonatomic,retain) id responseJSON; 				//@synthesize responseJSON=_responseJSON - In the implementation block
@property (nonatomic,retain) NSError* JSONError; 				//@synthesize JSONError=_JSONError - In the implementation block
+(BOOL)canProcessRequest:(id)arg1;
+(id)JSONRequestOperationWithRequest:(id)arg1 success:(id)arg2 failure:(id)arg3;
+(id)acceptableContentTypes;
-(void)setCompletionBlockWithSuccess:(id)arg1 failure:(id)arg2;
-(void)setResponseJSON:(id)arg1;
-(void)setJSONError:(id)arg1;
-(void)dealloc;
-(id)error;
@end