/*
 * This header is generated by weak_classdump 0.2
 * on Saturday, October 18, 2014 at 2:28:15 AM Eastern Daylight Time
 * Operating System: Version 7.1.1 (Build 11D201)
 * weak_classdump is Freeware by Elias Limneos.
 *
 */

#import <PF_AFMultipartFormData.h>

@interface PF_AFMultipartFormData : NSObject <PF_AFMultipartFormData> {
	NSMutableURLRequest* _request; 
	unsigned _stringEncoding; 
	NSOutputStream* _outputStream; 
	NSString* _temporaryFilePath; 
}
@property (nonatomic,retain) NSMutableURLRequest* request; 				//@synthesize request=_request - In the implementation block
@property (assign,nonatomic) unsigned stringEncoding; 				//@synthesize stringEncoding=_stringEncoding - In the implementation block
@property (nonatomic,retain) NSOutputStream* outputStream; 				//@synthesize outputStream=_outputStream - In the implementation block
@property (nonatomic,copy) NSString* temporaryFilePath; 				//@synthesize temporaryFilePath=_temporaryFilePath - In the implementation block
-(void)appendPartWithHeaders:(id)arg1 body:(id)arg2;
-(void)setStringEncoding:(unsigned)arg1;
-(id)initWithURLRequest:(id)arg1 stringEncoding:(unsigned)arg2;
-(void)appendPartWithFormData:(id)arg1 name:(id)arg2;
-(id)requestByFinalizingMultipartFormData;
-(void)setTemporaryFilePath:(id)arg1;
-(void)appendBoundary;
-(void)appendPartWithFileData:(id)arg1 name:(id)arg2 fileName:(id)arg3 mimeType:(id)arg4;
-(BOOL)appendPartWithFileURL:(id)arg1 name:(id)arg2 error:(id*)arg3;
-(void)setRequest:(id)arg1;
-(void)setOutputStream:(id)arg1;
-(void)dealloc;
-(void)appendString:(id)arg1;
-(void)appendData:(id)arg1;
@end