/*
 * This header is generated by weak_classdump 0.2
 * on Saturday, October 18, 2014 at 2:28:13 AM Eastern Daylight Time
 * Operating System: Version 7.1.1 (Build 11D201)
 * weak_classdump is Freeware by Elias Limneos.
 *
 */


@interface PF_AFHTTPRequestOperation : PF_AFURLConnectionOperation {
	NSError* _HTTPError; 
	NSString* _responseFilePath; 
	struct dispatch_queue_s* _successCallbackQueue; 
	struct dispatch_queue_s* _failureCallbackQueue; 
	long long _totalContentLength; 
	long long _offsetContentLength; 
}
@property (nonatomic,@dynamic,retain) NSHTTPURLResponse* response; 
@property (nonatomic,copy) NSString* responseFilePath; 				//@synthesize responseFilePath=_responseFilePath - In the implementation block
@property (assign) long long totalContentLength; 				//@synthesize totalContentLength=_totalContentLength - In the implementation block
@property (assign) long long offsetContentLength; 				//@synthesize offsetContentLength=_offsetContentLength - In the implementation block
@property (copy) BOOL hasAcceptableStatusCode; 
@property (copy) BOOL hasAcceptableContentType; 
@property (assign,nonatomic) struct dispatch_queue_s* successCallbackQueue; 				//@synthesize successCallbackQueue=_successCallbackQueue - In the implementation block
@property (assign,nonatomic) struct dispatch_queue_s* failureCallbackQueue; 				//@synthesize failureCallbackQueue=_failureCallbackQueue - In the implementation block
@property (nonatomic,@dynamic,retain) NSURLRequest* request; 
@property (nonatomic,retain) NSError* HTTPError; 				//@synthesize HTTPError=_HTTPError - In the implementation block
+(id)acceptableStatusCodes;
+(void)addAcceptableStatusCodes:(id)arg1;
+(void)addAcceptableContentTypes:(id)arg1;
+(BOOL)canProcessRequest:(id)arg1;
+(id)acceptableContentTypes;
-(void)setHTTPError:(id)arg1;
-(void)setOffsetContentLength:(long long)arg1;
-(void)setTotalContentLength:(long long)arg1;
-(void)setSuccessCallbackQueue:(struct dispatch_queue_s*)arg1;
-(void)setFailureCallbackQueue:(struct dispatch_queue_s*)arg1;
-(void)setResponseFilePath:(id)arg1;
-(void)setCompletionBlockWithSuccess:(id)arg1 failure:(id)arg2;
-(void)dealloc;
-(void)connection:(id)arg1 didReceiveResponse:(id)arg2;
-(void)pause;
-(id)error;
@end