/*
 * This header is generated by weak_classdump 0.2
 * on Saturday, October 18, 2014 at 2:28:51 AM Eastern Daylight Time
 * Operating System: Version 7.1.1 (Build 11D201)
 * weak_classdump is Freeware by Elias Limneos.
 *
 */


@interface PF_EGORefreshTableHeaderView : UIView {
	id _delegate; 
	int _state; 
	UILabel* _lastUpdatedLabel; 
	UILabel* _statusLabel; 
	CALayer* _arrowImage; 
	UIActivityIndicatorView* _activityView; 
}
@property (assign,nonatomic) id<PF_EGORefreshTableHeaderDelegate> delegate; 				//@synthesize delegate=_delegate - In the implementation block
@property (nonatomic,copy) UILabel* lastUpdatedLabel; 				//@synthesize lastUpdatedLabel=_lastUpdatedLabel - In the implementation block
@property (nonatomic,copy) UILabel* statusLabel; 				//@synthesize statusLabel=_statusLabel - In the implementation block
@property (nonatomic,copy) UIActivityIndicatorView* activityView; 				//@synthesize activityView=_activityView - In the implementation block
-(void)refreshLastUpdatedDate;
-(void)egoRefreshScrollViewDidScroll:(id)arg1;
-(void)egoRefreshScrollViewDidEndDragging:(id)arg1;
-(void)egoRefreshScrollViewDataSourceDidFinishedLoading:(id)arg1;
-(id)initWithFrame:(CGRect)arg1;
-(void)dealloc;
-(void)setDelegate:(id)arg1;
-(void)setState:(int)arg1;
@end