/*
 * This header is generated by weak_classdump 0.2
 * on Saturday, October 18, 2014 at 2:28:52 AM Eastern Daylight Time
 * Operating System: Version 7.1.1 (Build 11D201)
 * weak_classdump is Freeware by Elias Limneos.
 *
 */


@interface PF_MBProgressHUD : UIView {
	int mode; 
	id<PF_MBProgressHUDDelegate> delegate; 
	SEL methodForExecution; 
	id targetForExecution; 
	id objectForExecution; 
	BOOL useAnimation; 
	UILabel* label; 
	UILabel* detailsLabel; 
	float progress; 
	NSString* labelText; 
	NSString* detailsLabelText; 
	BOOL isFinished; 
	struct CGAffineTransform rotationTransform; 
	BOOL dimBackground; 
	BOOL taskInProgress; 
	BOOL removeFromSuperViewOnHide; 
	int animationType; 
	float opacity; 
	UIFont* labelFont; 
	UIFont* detailsLabelFont; 
	UIView* indicator; 
	float width; 
	float height; 
	float xOffset; 
	float yOffset; 
	float margin; 
	float graceTime; 
	float minShowTime; 
	NSTimer* graceTimer; 
	NSTimer* minShowTimer; 
	UIView* customView; 
	NSDate* showStarted; 
}
@property (retain) UIView* customView; 
@property (assign) int mode; 
@property (assign) int animationType; 
@property (assign) id<PF_MBProgressHUDDelegate> delegate; 
@property (copy) NSString* labelText; 
@property (copy) NSString* detailsLabelText; 
@property (assign) float opacity; 
@property (assign) float xOffset; 
@property (assign) float yOffset; 
@property (assign) float margin; 
@property (assign) BOOL dimBackground; 
@property (assign) float graceTime; 
@property (assign) float minShowTime; 
@property (assign) BOOL taskInProgress; 
@property (assign) BOOL removeFromSuperViewOnHide; 
@property (retain) UIFont* labelFont; 
@property (retain) UIFont* detailsLabelFont; 
@property (assign) float progress; 
@property (retain) UIView* indicator; 
@property (assign) float width; 
@property (assign) float height; 
@property (retain) NSTimer* graceTimer; 
@property (retain) NSTimer* minShowTimer; 
@property (retain) NSDate* showStarted; 
+(id)showHUDAddedTo:(id)arg1 animated:(BOOL)arg2;
+(BOOL)hideHUDForView:(id)arg1 animated:(BOOL)arg2;
-(void)updateIndicators;
-(void)updateLabelText:(id)arg1;
-(void)updateDetailsLabelText:(id)arg1;
-(void)updateProgress;
-(void)setIndicator:(id)arg1;
-(void)setRemoveFromSuperViewOnHide:(BOOL)arg1;
-(void)setTransformForCurrentOrientation:(BOOL)arg1;
-(void)setDetailsLabelText:(id)arg1;
-(void)setDetailsLabelFont:(id)arg1;
-(void)setXOffset:(float)arg1;
-(void)setDimBackground:(BOOL)arg1;
-(void)setGraceTime:(float)arg1;
-(void)setMinShowTime:(float)arg1;
-(void)handleGraceTimer:(id)arg1;
-(void)setGraceTimer:(id)arg1;
-(void)showUsingAnimation:(BOOL)arg1;
-(void)handleMinShowTimer:(id)arg1;
-(void)setMinShowTimer:(id)arg1;
-(void)hideUsingAnimation:(BOOL)arg1;
-(void)hideDelayed:(id)arg1;
-(void)launchExecution;
-(void)setShowStarted:(id)arg1;
-(void)animationFinished:(id)arg1 finished:(BOOL)arg2 context:(void*)arg3;
-(void)hide:(BOOL)arg1 afterDelay:(double)arg2;
-(void)showWhileExecuting:(SEL)arg1 onTarget:(id)arg2 withObject:(id)arg3 animated:(BOOL)arg4;
-(void)setTaskInProgress:(BOOL)arg1;
-(void)setLabelFont:(id)arg1;
-(void)deviceOrientationDidChange:(id)arg1;
-(id)initWithFrame:(CGRect)arg1;
-(void)dealloc;
-(void)drawRect:(CGRect)arg1;
-(void)setDelegate:(id)arg1;
-(void)layoutSubviews;
-(void)setOpacity:(float)arg1;
-(void)setProgress:(float)arg1;
-(void)setMode:(int)arg1;
-(id)initWithView:(id)arg1;
-(void)done;
-(id)initWithWindow:(id)arg1;
-(void)show:(BOOL)arg1;
-(void)cleanUp;
-(void)setWidth:(float)arg1;
-(void)setCustomView:(id)arg1;
-(void)setYOffset:(float)arg1;
-(void)setHeight:(float)arg1;
-(void)setLabelText:(id)arg1;
-(void)setAnimationType:(int)arg1;
-(void)setMargin:(float)arg1;
-(void)hide:(BOOL)arg1;
@end