/*
 * This header is generated by weak_classdump 0.2
 * on Saturday, October 18, 2014 at 2:28:43 AM Eastern Daylight Time
 * Operating System: Version 7.1.1 (Build 11D201)
 * weak_classdump is Freeware by Elias Limneos.
 *
 */

#import <PF_SBJsonParser.h>
#import <PF_SBJsonWriter.h>

@interface PF_SBJSON : PF_SBJsonBase <PF_SBJsonParser, PF_SBJsonWriter> {
	PF_SBJsonParser* jsonParser; 
	PF_SBJsonWriter* jsonWriter; 
}
@property (assign) BOOL humanReadable; 
@property (assign) BOOL sortKeys; 
-(id)objectWithString:(id)arg1;
-(id)stringWithObject:(id)arg1;
-(id)stringWithObject:(id)arg1 allowScalar:(BOOL)arg2 error:(id*)arg3;
-(id)objectWithString:(id)arg1 allowScalar:(BOOL)arg2 error:(id*)arg3;
-(void)setHumanReadable:(BOOL)arg1;
-(void)setSortKeys:(BOOL)arg1;
-(id)stringWithFragment:(id)arg1 error:(id*)arg2;
-(id)stringWithObject:(id)arg1 error:(id*)arg2;
-(id)fragmentWithString:(id)arg1 error:(id*)arg2;
-(id)objectWithString:(id)arg1 error:(id*)arg2;
-(void)dealloc;
-(id)init;
-(unsigned)maxDepth;
-(void)setMaxDepth:(unsigned)arg1;
@end