/*
 * This header is generated by weak_classdump 0.2
 * on Saturday, October 18, 2014 at 2:29:03 AM Eastern Daylight Time
 * Operating System: Version 7.1.1 (Build 11D201)
 * weak_classdump is Freeware by Elias Limneos.
 *
 */

#import <PF_SBJsonParser.h>

@interface PF_SBJsonParser : PF_SBJsonBase <PF_SBJsonParser> {
	r* c; 
}
+(void)initialize;
-(BOOL)scanValue:(id*)arg1;
-(BOOL)scanIsAtEnd;
-(BOOL)scanRestOfDictionary:(id*)arg1;
-(BOOL)scanRestOfArray:(id*)arg1;
-(BOOL)scanRestOfString:(id*)arg1;
-(BOOL)scanRestOfFalse:(id*)arg1;
-(BOOL)scanRestOfTrue:(id*)arg1;
-(BOOL)scanRestOfNull:(id*)arg1;
-(BOOL)scanNumber:(id*)arg1;
-(BOOL)scanUnicodeChar:(unsigned short*)arg1;
-(BOOL)scanHexQuad:(unsigned short*)arg1;
-(id)objectWithString:(id)arg1;
-(id)fragmentWithString:(id)arg1;
@end