/*
 * This header is generated by weak_classdump 0.2
 * on Saturday, October 18, 2014 at 2:29:04 AM Eastern Daylight Time
 * Operating System: Version 7.1.1 (Build 11D201)
 * weak_classdump is Freeware by Elias Limneos.
 *
 */

#import <PF_SBJsonWriter.h>

@interface PF_SBJsonWriter : PF_SBJsonBase <PF_SBJsonWriter> {
	BOOL sortKeys; 
	BOOL humanReadable; 
}
@property (assign) BOOL humanReadable; 
@property (assign) BOOL sortKeys; 
+(void)initialize;
-(BOOL)appendValue:(id)arg1 into:(id)arg2;
-(BOOL)appendDictionary:(id)arg1 into:(id)arg2;
-(BOOL)appendArray:(id)arg1 into:(id)arg2;
-(BOOL)appendString:(id)arg1 into:(id)arg2;
-(id)stringWithObject:(id)arg1;
-(id)stringWithFragment:(id)arg1;
-(void)setHumanReadable:(BOOL)arg1;
-(void)setSortKeys:(BOOL)arg1;
-(id)indent;
@end