/*
 * This header is generated by weak_classdump 0.2
 * on Saturday, October 18, 2014 at 2:29:04 AM Eastern Daylight Time
 * Operating System: Version 7.1.1 (Build 11D201)
 * weak_classdump is Freeware by Elias Limneos.
 *
 */


@interface PF_SBJsonBase : NSObject {
	NSMutableArray* errorTrace; 
	unsigned depth; 
	unsigned maxDepth; 
}
@property (assign) unsigned maxDepth; 
@property (copy) NSArray* errorTrace; 
-(void)addErrorWithCode:(unsigned)arg1 description:(id)arg2;
-(void)clearErrorTrace;
-(void)dealloc;
-(id)init;
-(void)setMaxDepth:(unsigned)arg1;
@end