/*
 * This header is generated by weak_classdump 0.2
 * on Saturday, October 18, 2014 at 2:28:44 AM Eastern Daylight Time
 * Operating System: Version 7.1.1 (Build 11D201)
 * weak_classdump is Freeware by Elias Limneos.
 *
 */


@interface PF_Twitter : NSObject {
	NSString* consumerKey; 
	NSString* consumerSecret; 
	NSString* authToken; 
	NSString* authTokenSecret; 
	NSString* userId; 
	NSString* screenName; 
}
@property (nonatomic,copy) NSString* consumerKey; 
@property (nonatomic,copy) NSString* consumerSecret; 
@property (nonatomic,copy) NSString* authToken; 
@property (nonatomic,copy) NSString* authTokenSecret; 
@property (nonatomic,copy) NSString* userId; 
@property (nonatomic,copy) NSString* screenName; 
-(void)getRequestToken:(id*)arg1 result:(id*)arg2;
-(id)getAccessToken:(id)arg1 requestSecret:(id)arg2 token:(id)arg3 error:(id*)arg4;
-(void)setAuthTokenSecret:(id)arg1;
-(void)authorizeWithSuccess:(id)arg1 failure:(id)arg2 cancel:(id)arg3;
-(void)signRequest:(id)arg1;
-(void)setAuthToken:(id)arg1;
-(void)setConsumerKey:(id)arg1;
-(void)setConsumerSecret:(id)arg1;
-(void)dealloc;
-(void)setScreenName:(id)arg1;
-(void)setUserId:(id)arg1;
@end