/*
 * This header is generated by weak_classdump 0.2
 * on Saturday, October 18, 2014 at 2:28:53 AM Eastern Daylight Time
 * Operating System: Version 7.1.1 (Build 11D201)
 * weak_classdump is Freeware by Elias Limneos.
 *
 */

#import <NSCopying.h>

@interface PFACL : NSObject <NSCopying> {
	NSMutableDictionary* permissionsById; 
	BOOL shared; 
	PFUser* unresolvedUser; 
	id userResolutionListener; 
}
+(id)ACL;
+(id)ACLWithDictionary:(id)arg1;
+(id)ACLWithUser:(id)arg1;
+(id)defaultACL;
+(void)setDefaultACL:(id)arg1 withAccessForCurrentUser:(BOOL)arg2;
-(id)encodeIntoDictionary;
-(void)setReadAccess:(BOOL)arg1 forUser:(id)arg2;
-(void)setWriteAccess:(BOOL)arg1 forUser:(id)arg2;
-(BOOL)getReadAccessForUser:(id)arg1;
-(BOOL)getWriteAccessForUser:(id)arg1;
-(void)setAccess:(id)arg1 to:(BOOL)arg2 forUserId:(id)arg3;
-(BOOL)getAccess:(id)arg1 forUserId:(id)arg2;
-(void)setReadAccess:(BOOL)arg1 forUserId:(id)arg2;
-(BOOL)getReadAccessForUserId:(id)arg1;
-(void)setWriteAccess:(BOOL)arg1 forUserId:(id)arg2;
-(BOOL)getWriteAccessForUserId:(id)arg1;
-(void)validateRoleState:(id)arg1;
-(BOOL)getReadAccessForRoleWithName:(id)arg1;
-(void)setReadAccess:(BOOL)arg1 forRoleWithName:(id)arg2;
-(void)setWriteAccess:(BOOL)arg1 forRoleWithName:(id)arg2;
-(void)resolveUser:(id)arg1;
-(void)prepareUnresolvedUser:(id)arg1;
-(void)setUnresolvedReadAccess:(BOOL)arg1 forUser:(id)arg2;
-(void)setUnresolvedWriteAccess:(BOOL)arg1 forUser:(id)arg2;
-(id)createUnsharedCopy;
-(BOOL)hasUnresolvedUser;
-(void)setPublicReadAccess:(BOOL)arg1;
-(BOOL)getPublicReadAccess;
-(void)setPublicWriteAccess:(BOOL)arg1;
-(BOOL)getPublicWriteAccess;
-(BOOL)getWriteAccessForRoleWithName:(id)arg1;
-(BOOL)getReadAccessForRole:(id)arg1;
-(void)setReadAccess:(BOOL)arg1 forRole:(id)arg2;
-(BOOL)getWriteAccessForRole:(id)arg1;
-(void)setWriteAccess:(BOOL)arg1 forRole:(id)arg2;
-(BOOL)isShared;
-(void)dealloc;
-(id)init;
-(id)initWithDictionary:(id)arg1;
-(id)copyWithZone:(NSZone*)arg1;
-(void)setShared:(BOOL)arg1;
@end