/*
 * This header is generated by weak_classdump 0.2
 * on Saturday, October 18, 2014 at 2:28:40 AM Eastern Daylight Time
 * Operating System: Version 7.1.1 (Build 11D201)
 * weak_classdump is Freeware by Elias Limneos.
 *
 */

#import <UITextFieldDelegate.h>

@interface PFAlertInputView : UIAlertView <UITextFieldDelegate> {
	UITextField* textField; 
}
@property (nonatomic,copy) NSString* text; 
@property (nonatomic,retain) UITextField* textField; 
-(id)initWithTitle:(id)arg1 message:(id)arg2 delegate:(id)arg3 cancelButtonTitle:(id)arg4 okButtonTitle:(id)arg5;
-(void)setTextField:(id)arg1;
-(void)layoutSubviews;
-(void)show;
-(BOOL)textFieldShouldReturn:(id)arg1;
-(void).cxx_destruct;
@end