/*
 * This header is generated by weak_classdump 0.2
 * on Saturday, October 18, 2014 at 2:28:02 AM Eastern Daylight Time
 * Operating System: Version 7.1.1 (Build 11D201)
 * weak_classdump is Freeware by Elias Limneos.
 *
 */


@interface PFAnalytics : NSObject {
}
+(void)trackAppOpenedWithRemoteNotificationPayload:(id)arg1;
+(id)generateDigestFromPayload:(id)arg1;
+(void)trackEventually:(id)arg1 params:(id)arg2;
+(void)trackEvent:(id)arg1 dimensions:(id)arg2;
+(void)trackAppOpenedWithLaunchOptions:(id)arg1;
+(void)trackEvent:(id)arg1;
@end