/*
 * This header is generated by weak_classdump 0.2
 * on Saturday, October 18, 2014 at 2:28:40 AM Eastern Daylight Time
 * Operating System: Version 7.1.1 (Build 11D201)
 * weak_classdump is Freeware by Elias Limneos.
 *
 */


@interface PFAnonymousUtils : NSObject {
}
+(BOOL)isLinkedWithUser:(id)arg1;
+(void)lazyLogIn;
+(void)logInWithBlock:(id)arg1;
+(void)logInWithTarget:(id)arg1 selector:(SEL)arg2;
+(id)provider;
@end