/*
 * This header is generated by weak_classdump 0.2
 * on Saturday, October 18, 2014 at 2:28:50 AM Eastern Daylight Time
 * Operating System: Version 7.1.1 (Build 11D201)
 * weak_classdump is Freeware by Elias Limneos.
 *
 */


@interface PFBlockRetryer : NSObject {
	int attemptsMade; 
	int maxAttempts; 
	double delay; 
	id block; 
}
+(id)retryBlock:(id)arg1 forAttempts:(int)arg2;
+(void)setInitialDelay:(double)arg1;
-(id)initWithBlock:(id)arg1 forAttempts:(int)arg2;
-(id)go;
-(void)dealloc;
@end