/*
 * This header is generated by weak_classdump 0.2
 * on Saturday, October 18, 2014 at 2:28:09 AM Eastern Daylight Time
 * Operating System: Version 7.1.1 (Build 11D201)
 * weak_classdump is Freeware by Elias Limneos.
 *
 */


@interface PFCloud : NSObject {
}
+(void)callFunctionInBackground:(id)arg1 withParameters:(id)arg2 block:(id)arg3;
+(id)callFunctionAsync:(id)arg1 withParameters:(id)arg2;
+(id)callFunction:(id)arg1 withParameters:(id)arg2 error:(id*)arg3;
+(void)callFunctionInBackground:(id)arg1 withParameters:(id)arg2 target:(id)arg3 selector:(SEL)arg4;
+(id)callFunction:(id)arg1 withParameters:(id)arg2;
@end