/*
 * This header is generated by weak_classdump 0.2
 * on Saturday, October 18, 2014 at 2:29:03 AM Eastern Daylight Time
 * Operating System: Version 7.1.1 (Build 11D201)
 * weak_classdump is Freeware by Elias Limneos.
 *
 */


@interface PFCommand : NSObject {
	NSMutableDictionary* params; 
	NSString* serverOperation; 
	NSString* cacheKey; 
	NSString* localId; 
}
@property (nonatomic,retain) NSString* serverOperation; 
@property (nonatomic,copy) NSString* cacheKey; 
@property (nonatomic,copy) NSMutableDictionary* params; 
@property (nonatomic,retain) NSString* localId; 
+(id)commandWithServerOperation:(id)arg1 params:(id)arg2 sessionToken:(id)arg3;
+(BOOL)forEachLocalIdIn:(id)arg1 doBlock:(id)arg2;
+(id)commandFromJSON:(id)arg1;
-(void)setServerOperation:(id)arg1;
-(void)forEachLocalId:(id)arg1;
-(void)maybeChangeServerOperation;
-(void)resolveLocalIds;
-(id)json;
-(id)initWithServerOperation:(id)arg1 params:(id)arg2 sessionToken:(id)arg3;
-(void)releaseLocalIds;
-(void)retainLocalIds;
-(id)description;
-(void).cxx_destruct;
-(void)setLocalId:(id)arg1;
@end