/*
 * This header is generated by weak_classdump 0.2
 * on Saturday, October 18, 2014 at 2:28:49 AM Eastern Daylight Time
 * Operating System: Version 7.1.1 (Build 11D201)
 * weak_classdump is Freeware by Elias Limneos.
 *
 */


@interface PFCommandCache : NSObject {
	NSString* cachePath; 
	int timeoutMaxRetries; 
	float timeoutRetryWaitSeconds; 
	int maxCacheSizeBytes; 
	BOOL shouldStop; 
	BOOL connected; 
	struct __SCNetworkReachability* reachability; 
	NSMutableDictionary* taskCompletionSources; 
	NSCondition* lock; 
	BOOL running; 
	NSCondition* runningLock; 
	PFCommandCacheTestHelper* testHelper; 
	struct dispatch_queue_s* blockQueue; 
}
@property (retain) NSString* cachePath; 
+(id)defaultInstance;
-(id)runEventuallyAsync:(id)arg1 withObject:(id)arg2;
-(void)notifyTestHelperObjectUpdated;
-(void)setCachePath:(id)arg1;
-(void)removeFile:(id)arg1 error:(id*)arg2;
-(void)maybeRunAllCommandsNow:(int)arg1;
-(void)runEventuallyInternal:(id)arg1 taskCompletionSource:(id)arg2 preferOldest:(BOOL)arg3 withObject:(id)arg4;
-(void)setTimeoutMaxRetries:(int)arg1;
-(void)setTimeoutRetryWaitSeconds:(float)arg1;
-(void)setMaxCacheSizeBytes:(int)arg1;
-(void)simulateReboot;
-(int)commandsInMemory;
-(id)testHelper;
-(void)runLoop;
-(void)dealloc;
-(id)init;
-(void)resume;
-(void)clear;
-(void)pause;
-(void)setConnected:(BOOL)arg1;
-(int)pendingCount;
@end