/*
 * This header is generated by weak_classdump 0.2
 * on Saturday, October 18, 2014 at 2:28:06 AM Eastern Daylight Time
 * Operating System: Version 7.1.1 (Build 11D201)
 * weak_classdump is Freeware by Elias Limneos.
 *
 */


@interface PFCommandResult : NSObject {
	id result; 
	NSString* resultString; 
}
@property (nonatomic,retain) id result; 
@property (nonatomic,retain) NSString* resultString; 
-(void)setResultString:(id)arg1;
-(void).cxx_destruct;
-(void)setResult:(id)arg1;
@end