/*
 * This header is generated by weak_classdump 0.2
 * on Saturday, October 18, 2014 at 2:28:46 AM Eastern Daylight Time
 * Operating System: Version 7.1.1 (Build 11D201)
 * weak_classdump is Freeware by Elias Limneos.
 *
 */


@interface PFFacebookUtils : NSObject {
}
+(BOOL)isLinkedWithUser:(id)arg1;
+(BOOL)handleOpenURL:(id)arg1;
+(void)initializeFacebook;
+(void)logInWithPermissions:(id)arg1 block:(id)arg2;
+(void)initializeFacebookWithUrlShemeSuffix:(id)arg1;
+(BOOL)unlinkUser:(id)arg1 error:(id*)arg2;
+(void)checkInitialization;
+(void)unlinkUserInBackground:(id)arg1 block:(id)arg2;
+(void)linkUser:(id)arg1 permissions:(id)arg2 block:(id)arg3;
+(void)linkUser:(id)arg1 facebookId:(id)arg2 accessToken:(id)arg3 expirationDate:(id)arg4 block:(id)arg5;
+(void)logInWithFacebookId:(id)arg1 accessToken:(id)arg2 expirationDate:(id)arg3 block:(id)arg4;
+(void)reauthorizeUser:(id)arg1 withPublishPermissions:(id)arg2 audience:(int)arg3 block:(id)arg4;
+(void)initializeWithApplicationId:(id)arg1;
+(void)initializeWithApplicationId:(id)arg1 urlSchemeSuffix:(id)arg2;
+(BOOL)unlinkUser:(id)arg1;
+(void)unlinkUserInBackground:(id)arg1;
+(void)unlinkUserInBackground:(id)arg1 target:(id)arg2 selector:(SEL)arg3;
+(void)linkUser:(id)arg1 permissions:(id)arg2;
+(void)linkUser:(id)arg1 permissions:(id)arg2 target:(id)arg3 selector:(SEL)arg4;
+(void)linkUser:(id)arg1 facebookId:(id)arg2 accessToken:(id)arg3 expirationDate:(id)arg4 target:(id)arg5 selector:(SEL)arg6;
+(void)logInWithPermissions:(id)arg1 target:(id)arg2 selector:(SEL)arg3;
+(void)logInWithFacebookId:(id)arg1 accessToken:(id)arg2 expirationDate:(id)arg3 target:(id)arg4 selector:(SEL)arg5;
+(void)reauthorizeUser:(id)arg1 withPublishPermissions:(id)arg2 audience:(int)arg3 target:(id)arg4 selector:(SEL)arg5;
+(id)session;
@end