/*
 * This header is generated by weak_classdump 0.2
 * on Saturday, October 18, 2014 at 2:29:00 AM Eastern Daylight Time
 * Operating System: Version 7.1.1 (Build 11D201)
 * weak_classdump is Freeware by Elias Limneos.
 *
 */


@protocol PFFieldOperation
@required
-(id)encodeAllowUnsavedChildren(BOOL):arg1 allowObjects(BOOL):arg2 ;
-(id)mergeWithPrevious(id):arg1 ;
-(id)applyToValue(id):arg1 forKey(id):arg2 ofObject(id):arg3 ;
-(id)encodeAllowUnsavedChildren(BOOL):arg1 allowObjects(BOOL):arg2 ;
-(id)mergeWithPrevious(id):arg1 ;
-(id)applyToValue(id):arg1 forKey(id):arg2 ofObject(id):arg3 ;
@end
