/*
 * This header is generated by weak_classdump 0.2
 * on Saturday, October 18, 2014 at 2:28:30 AM Eastern Daylight Time
 * Operating System: Version 7.1.1 (Build 11D201)
 * weak_classdump is Freeware by Elias Limneos.
 *
 */


@interface PFHTTPChunkedResponseBody : PFHTTPResponseBody {
	BOOL reachedTerminatorChunk; 
	BOOL expectingCRLF; 
	BOOL expectingData; 
	NSMutableData* unparsedBuffer; 
	int chunkBytesLeft; 
}
@property (nonatomic,retain) NSMutableData* unparsedBuffer; 
@property (assign,nonatomic) int chunkBytesLeft; 
@property (assign,nonatomic) BOOL expectingCRLF; 
@property (assign,nonatomic) BOOL expectingData; 
@property (assign,nonatomic) BOOL reachedTerminatorChunk; 
-(void)setUnparsedBuffer:(id)arg1;
-(void)setChunkBytesLeft:(int)arg1;
-(void)setReachedTerminatorChunk:(BOOL)arg1;
-(void)setExpectingCRLF:(BOOL)arg1;
-(void)setExpectingData:(BOOL)arg1;
-(unsigned)appendBytes:(r*)arg1 length:(unsigned)arg2;
-(BOOL)done;
-(void).cxx_destruct;
-(id)initWithResponse:(id)arg1;
@end