/*
 * This header is generated by weak_classdump 0.2
 * on Saturday, October 18, 2014 at 2:28:29 AM Eastern Daylight Time
 * Operating System: Version 7.1.1 (Build 11D201)
 * weak_classdump is Freeware by Elias Limneos.
 *
 */


@interface PFHTTPResponse : NSObject {
	BOOL parseError; 
	PFHTTPHeaders* headers; 
	PFHTTPResponseBody* body; 
	id progressBlock; 
	NSOutputStream* responseStream; 
	NSString* tempFilePath; 
	NSString* targetFilePath; 
	NSString* responseString; 
}
@property (nonatomic,retain) PFHTTPHeaders* headers; 
@property (nonatomic,retain) PFHTTPResponseBody* body; 
@property (nonatomic,copy) id progressBlock; 
@property (assign,nonatomic) BOOL parseError; 
@property (nonatomic,retain) NSOutputStream* responseStream; 
@property (nonatomic,retain) NSString* tempFilePath; 
@property (nonatomic,retain) NSString* targetFilePath; 
@property (nonatomic,retain) NSString* responseString; 
-(void)setParseError:(BOOL)arg1;
-(void)setResponseStream:(id)arg1;
-(void)setTempFilePath:(id)arg1;
-(id)maybeCreateResponseString;
-(void)streamBodyToPath:(id)arg1;
-(void)setTargetFilePath:(id)arg1;
-(void)setResponseString:(id)arg1;
-(id)responseData;
-(id)init;
-(int)appendBytes:(r*)arg1 length:(unsigned)arg2;
-(BOOL)done;
-(void).cxx_destruct;
-(void)setBody:(id)arg1;
-(void)setProgressBlock:(id)arg1;
-(void)setHeaders:(id)arg1;
@end