/*
 * This header is generated by weak_classdump 0.2
 * on Saturday, October 18, 2014 at 2:28:33 AM Eastern Daylight Time
 * Operating System: Version 7.1.1 (Build 11D201)
 * weak_classdump is Freeware by Elias Limneos.
 *
 */


@interface PFHTTPCommandDelegate : NSObject {
	NSMutableArray* delegatedHosts; 
}
+(void)connectToUrl:(id)arg1 forUplink:(id*)arg2 downlink:(id*)arg3;
+(void)detachAllDelegatedHosts:(id)arg1;
+(void)setDelegate:(id)arg1 forHost:(id)arg2;
+(void)initialize;
-(void)connectToUrl:(id)arg1 forUplink:(id*)arg2 downlink:(id*)arg3;
-(void)delegateForHost:(id)arg1;
-(void)dealloc;
-(id)init;
-(void)detach;
-(void).cxx_destruct;
@end