/*
 * This header is generated by weak_classdump 0.2
 * on Saturday, October 18, 2014 at 2:28:38 AM Eastern Daylight Time
 * Operating System: Version 7.1.1 (Build 11D201)
 * weak_classdump is Freeware by Elias Limneos.
 *
 */


@interface PFHTTPHeaders : NSObject {
	NSString* statusLine; 
	int statusCode; 
	NSString* statusDescription; 
	BOOL complete; 
	NSMutableData* responseBuffer; 
	int responseScanToken; 
	BOOL parseError; 
	NSString* verb; 
	NSMutableDictionary* fields; 
	NSString* contentType; 
	long long contentLength; 
}
@property (nonatomic,retain) NSString* verb; 
@property (copy) BOOL parseError; 
@property (copy) BOOL complete; 
@property (copy) NSString* statusLine; 
@property (copy) int statusCode; 
@property (copy) NSString* statusDescription; 
@property (copy) long long contentLength; 
@property (copy) NSString* contentType; 
@property (retain) NSMutableDictionary* fields; 
+(void)initialize;
-(void)setFields:(id)arg1;
-(void)addHeader:(id)arg1 value:(id)arg2;
-(void)parseHeaderValuesWithSpecialAccessors;
-(void)parseStatusLine:(char*)arg1 length:(int)arg2;
-(void)validatePotentialHeaderLine:(char*)arg1 end:(char*)arg2 shouldBeFullHeader:(BOOL)arg3;
-(void)maybeGiveUpOnParsing:(char*)arg1 bufferEnd:(char*)arg2;
-(id)getHeader:(id)arg1;
-(id)initRequest;
-(id)initResponse;
-(id)compileRequestWithURL:(id)arg1 body:(id)arg2;
-(id)getStatusLine;
-(int)getStatusCode;
-(id)allHeaders;
-(int)appendBytes:(r*)arg1 length:(int)arg2;
-(void).cxx_destruct;
-(void)setVerb:(id)arg1;
-(id)userAgent;
@end