/*
 * This header is generated by weak_classdump 0.2
 * on Saturday, October 18, 2014 at 2:28:30 AM Eastern Daylight Time
 * Operating System: Version 7.1.1 (Build 11D201)
 * weak_classdump is Freeware by Elias Limneos.
 *
 */


@interface PFHTTPResponseBody : NSObject {
	PFHTTPResponse* response; 
	int expectedLength; 
	unsigned long long bytesWritten; 
}
@property (assign,nonatomic) PFHTTPResponse* response; 
@property (nonatomic,copy) int expectedLength; 
@property (assign,nonatomic) unsigned long long bytesWritten; 
+(id)bodyForResponse:(id)arg1;
-(void)maybeReportDownloadProgress:(unsigned)arg1;
-(void)setBytesWritten:(unsigned long long)arg1;
-(void)setResponse:(id)arg1;
-(unsigned)appendBytes:(r*)arg1 length:(unsigned)arg2;
-(BOOL)done;
-(id)initWithResponse:(id)arg1;
@end