/*
 * This header is generated by weak_classdump 0.2
 * on Saturday, October 18, 2014 at 2:28:24 AM Eastern Daylight Time
 * Operating System: Version 7.1.1 (Build 11D201)
 * weak_classdump is Freeware by Elias Limneos.
 *
 */


@interface PFImageCache : NSCache {
}
+(id)sharedCache;
-(void)setImage:(id)arg1 forURL:(id)arg2;
-(id)imageForURL:(id)arg1;
@end