/*
 * This header is generated by weak_classdump 0.2
 * on Saturday, October 18, 2014 at 2:28:27 AM Eastern Daylight Time
 * Operating System: Version 7.1.1 (Build 11D201)
 * weak_classdump is Freeware by Elias Limneos.
 *
 */

#import <PFSubclassing.h>

@interface PFInstallation : PFObject <PFSubclassing> {
}
@property (nonatomic,@dynamic,retain) NSString* deviceType; 
@property (nonatomic,@dynamic,retain) NSString* installationId; 
@property (nonatomic,@dynamic,retain) NSString* deviceToken; 
@property (assign,nonatomic,@dynamic) int badge; 
@property (nonatomic,@dynamic,retain) NSString* timeZone; 
@property (nonatomic,@dynamic,retain) NSArray* channels; 
+(id)parseClassName;
+(void)validateClassName:(id)arg1;
+(id)currentInstallation;
+(void)clearCurrentInstallationInMemory;
+(void)clearCurrentInstallation;
+(void)saveCurrentInstallation:(id)arg1;
+(id)query;
+(void)initialize;
-(void)checkDeleteParams;
-(id)saveAsync:(id)arg1;
-(id)fetchAsync:(id)arg1;
-(BOOL)needsDefaultACL;
-(id)displayClassName;
-(void)saveInBackgroundWithBlock:(id)arg1;
-(void)saveEventually:(id)arg1;
-(void)incrementKey:(id)arg1 byAmount:(id)arg2;
-(void)clearDeviceToken;
-(void)setDeviceToken:(id)arg1;
-(void)markAllFieldsDirty;
-(void)updateBadgeFromDevice;
-(void)updateTimeZoneFromDevice;
-(void)updateVersionInfoFromDevice;
-(void)setDeviceType:(id)arg1;
-(void)setInstallationId:(id)arg1;
-(void)updateAutomaticInfo;
-(void)setDeviceTokenFromData:(id)arg1;
-(void)removeObjectForKey:(id)arg1;
-(void)setTimeZone:(id)arg1;
-(BOOL)save:(id*)arg1;
-(id)objectForKey:(id)arg1;
-(void)setObject:(id)arg1 forKey:(id)arg2;
@end