/*
 * This header is generated by weak_classdump 0.2
 * on Saturday, October 18, 2014 at 2:28:25 AM Eastern Daylight Time
 * Operating System: Version 7.1.1 (Build 11D201)
 * weak_classdump is Freeware by Elias Limneos.
 *
 */


@interface PFKeyValueDiskCacheDelegate : NSObject {
}
-(unsigned)accessTimeOfDiskCache:(id)arg1 withStat:(struct stat*)arg2;
-(void)touchDiskCache:(id)arg1;
-(id)creationTimeOfDiskCache:(id)arg1;
-(void)createDiskCache:(id)arg1 value:(id)arg2;
@end