/*
 * This header is generated by weak_classdump 0.2
 * on Saturday, October 18, 2014 at 2:28:26 AM Eastern Daylight Time
 * Operating System: Version 7.1.1 (Build 11D201)
 * weak_classdump is Freeware by Elias Limneos.
 *
 */


@interface PFKeyValueCacheEntry : NSObject {
	NSString* value; 
	long creationTime; 
}
@property (nonatomic,retain) NSString* value; 
@property (assign,nonatomic) long creationTime; 
-(void)setValue:(id)arg1;
-(void).cxx_destruct;
-(void)setCreationTime:(long)arg1;
@end