/*
 * This header is generated by weak_classdump 0.2
 * on Saturday, October 18, 2014 at 2:28:31 AM Eastern Daylight Time
 * Operating System: Version 7.1.1 (Build 11D201)
 * weak_classdump is Freeware by Elias Limneos.
 *
 */


@interface PFLogInFieldBackgroundView : UIView {
	UIImageView* topView; 
	UIView* centerView; 
	UIImageView* bottomView; 
	NSMutableArray* separators; 
}
@property (nonatomic,copy) UIImageView* topView; 
@property (nonatomic,copy) UIView* centerView; 
@property (nonatomic,copy) UIImageView* bottomView; 
@property (nonatomic,copy) NSMutableArray* separators; 
-(id)initWithSeparators:(int)arg1;
-(void)layoutSubviews;
-(void).cxx_destruct;
@end