/*
 * This header is generated by weak_classdump 0.2
 * on Saturday, October 18, 2014 at 2:28:43 AM Eastern Daylight Time
 * Operating System: Version 7.1.1 (Build 11D201)
 * weak_classdump is Freeware by Elias Limneos.
 *
 */

#import <UITextFieldDelegate.h>

@interface PFLogInViewController : UIViewController <UITextFieldDelegate> {
	PF_MBProgressHUD* hud; 
	int fields; 
	PFLogInView* logInView; 
	id<PFLogInViewControllerDelegate> delegate; 
	NSArray* facebookPermissions; 
	PFSignUpViewController* signUpController; 
}
@property (assign,nonatomic) int fields; 
@property (nonatomic,copy) PFLogInView* logInView; 
@property (assign,nonatomic) id<PFLogInViewControllerDelegate> delegate; 
@property (nonatomic,retain) NSArray* facebookPermissions; 
@property (nonatomic,retain) PFSignUpViewController* signUpController; 
-(void)setupHandlers;
-(void)requestPasswordReset:(id)arg1;
-(void)displayEmailRequestDialog;
-(void)logInUsingFacebook;
-(void)logInUsingTwitter;
-(void)cancelLogIn;
-(void)succeedLogInUser:(id)arg1;
-(void)failLogInWithError:(id)arg1;
-(void)setFields:(int)arg1;
-(void)setFacebookPermissions:(id)arg1;
-(void)setSignUpController:(id)arg1;
-(id)initWithCoder:(id)arg1;
-(void)setDelegate:(id)arg1;
-(id)init;
-(id)initWithNibName:(id)arg1 bundle:(id)arg2;
-(void)loadView;
-(BOOL)textFieldShouldReturn:(id)arg1;
-(BOOL)shouldAutorotateToInterfaceOrientation:(int)arg1;
-(void)viewDidUnload;
-(void)dismissKeyboard;
-(void)dismiss;
-(void).cxx_destruct;
-(void)alertView:(id)arg1 willDismissWithButtonIndex:(int)arg2;
-(void)setup;
@end