/*
 * This header is generated by weak_classdump 0.2
 * on Saturday, October 18, 2014 at 2:28:07 AM Eastern Daylight Time
 * Operating System: Version 7.1.1 (Build 11D201)
 * weak_classdump is Freeware by Elias Limneos.
 *
 */


@interface PFLocalIdManagerMapEntry : NSObject {
	NSString* objectId; 
	int referenceCount; 
}
@property (nonatomic,retain) NSString* objectId; 
@property (assign) int referenceCount; 
-(void)setObjectId:(id)arg1;
-(void)setReferenceCount:(int)arg1;
-(id)initWithFile:(id)arg1;
-(void)writeToFile:(id)arg1;
-(void).cxx_destruct;
@end