/*
 * This header is generated by weak_classdump 0.2
 * on Saturday, October 18, 2014 at 2:28:32 AM Eastern Daylight Time
 * Operating System: Version 7.1.1 (Build 11D201)
 * weak_classdump is Freeware by Elias Limneos.
 *
 */


@interface PFLogInButton : UIButton {
	UIImageView* checkmarkView; 
}
@property (nonatomic,retain) UIImageView* checkmarkView; 
-(void)setCheckmarkView:(id)arg1;
-(id)initWithFrame:(CGRect)arg1;
-(void)setMode:(int)arg1;
-(void).cxx_destruct;
@end