/*
 * This header is generated by weak_classdump 0.2
 * on Saturday, October 18, 2014 at 2:28:25 AM Eastern Daylight Time
 * Operating System: Version 7.1.1 (Build 11D201)
 * weak_classdump is Freeware by Elias Limneos.
 *
 */


@interface PFLoadingView : UIView {
	UILabel* loadingLabel; 
	UIActivityIndicatorView* activityIndicator; 
}
@property (nonatomic,retain) UILabel* loadingLabel; 
@property (nonatomic,retain) UIActivityIndicatorView* activityIndicator; 
-(void)setLoadingLabel:(id)arg1;
-(id)initWithFrame:(CGRect)arg1;
-(void)layoutSubviews;
-(void).cxx_destruct;
-(void)setActivityIndicator:(id)arg1;
@end