/*
 * This header is generated by weak_classdump 0.2
 * on Saturday, October 18, 2014 at 2:28:03 AM Eastern Daylight Time
 * Operating System: Version 7.1.1 (Build 11D201)
 * weak_classdump is Freeware by Elias Limneos.
 *
 */

#import <CLLocationManagerDelegate.h>

@interface PFLocationManager : NSObject <CLLocationManagerDelegate> {
	CLLocationManager* _locationManager; 
	NSMutableSet* _blockSet; 
}
@property (nonatomic,retain) CLLocationManager* locationManager; 				//@synthesize locationManager=_locationManager - In the implementation block
@property (nonatomic,retain) NSMutableSet* blockSet; 				//@synthesize blockSet=_blockSet - In the implementation block
-(void)addBlockForCurrentLocation:(id)arg1;
-(void)setBlockSet:(id)arg1;
-(void)dealloc;
-(id)init;
-(void).cxx_destruct;
-(void)locationManager:(id)arg1 didUpdateToLocation:(id)arg2 fromLocation:(id)arg3;
-(void)locationManager:(id)arg1 didUpdateLocations:(id)arg2;
-(void)locationManager:(id)arg1 didFailWithError:(id)arg2;
-(void)setLocationManager:(id)arg1;
@end