/*
 * This header is generated by weak_classdump 0.2
 * on Saturday, October 18, 2014 at 2:28:23 AM Eastern Daylight Time
 * Operating System: Version 7.1.1 (Build 11D201)
 * weak_classdump is Freeware by Elias Limneos.
 *
 */


@interface PFMemoryMappedFile : NSObject {
	int fileHandle; 
	unsigned long fileSize; 
	void* mappedAddress; 
}
-(id)initWithContentsAtPath:(id)arg1;
-(void)dealloc;
-(id)data;
@end