/*
 * This header is generated by weak_classdump 0.2
 * on Saturday, October 18, 2014 at 2:28:39 AM Eastern Daylight Time
 * Operating System: Version 7.1.1 (Build 11D201)
 * weak_classdump is Freeware by Elias Limneos.
 *
 */


@interface PFMulticastDelegate : NSObject {
	NSMutableArray* callbacks; 
}
-(void)invoke:(id)arg1 error:(id)arg2;
-(void)unsubscribe:(id)arg1;
-(void)dealloc;
-(id)init;
-(void)clear;
-(void)subscribe:(id)arg1;
@end