/*
 * This header is generated by weak_classdump 0.2
 * on Saturday, October 18, 2014 at 2:29:01 AM Eastern Daylight Time
 * Operating System: Version 7.1.1 (Build 11D201)
 * weak_classdump is Freeware by Elias Limneos.
 *
 */


@interface PFMultiCommand : PFCommand {
	NSArray* commands; 
}
@property (nonatomic,retain) NSArray* commands; 
+(id)multiCommandWithCommands:(id)arg1 sessionToken:(id)arg2;
-(void)setCommands:(id)arg1;
@end