/*
 * This header is generated by weak_classdump 0.2
 * on Saturday, October 18, 2014 at 2:28:37 AM Eastern Daylight Time
 * Operating System: Version 7.1.1 (Build 11D201)
 * weak_classdump is Freeware by Elias Limneos.
 *
 */


@protocol PFMultipartPart
@property (nonatomic,copy) unsigned size; 
@property (assign,nonatomic) unsigned offset; 
@required
-(int)bufferPart(r):arg1 atIndex(*):arg2 ;
-(unsigned)size;
-(void)setOffset(unsigned):arg1 ;
-(unsigned)offset;
-(int)bufferPart(r):arg1 atIndex(*):arg2 ;
-(unsigned)size;
-(void)setOffset(unsigned):arg1 ;
-(unsigned)offset;
@end
