/*
 * This header is generated by weak_classdump 0.2
 * on Saturday, October 18, 2014 at 2:28:37 AM Eastern Daylight Time
 * Operating System: Version 7.1.1 (Build 11D201)
 * weak_classdump is Freeware by Elias Limneos.
 *
 */

#import <PFMultipartPart.h>

@interface PFMultipartPartStream : NSObject <PFMultipartPart> {
	unsigned char[4096] cachedBuffer; 
	unsigned size; 
	unsigned offset; 
	unsigned bufferIndex; 
	unsigned validBufferSize; 
	NSInputStream* stream; 
}
@property (nonatomic,copy) unsigned size; 
@property (assign,nonatomic) unsigned offset; 
@property (nonatomic,copy) unsigned bufferIndex; 
@property (nonatomic,copy) unsigned validBufferSize; 
@property (assign,nonatomic) NSInputStream* stream; 
-(int)bufferPart:(r**)arg1 atIndex:(int)arg2;
-(id)initWithStream:(id)arg1 length:(unsigned)arg2;
-(void)setStream:(id)arg1;
-(void)setOffset:(unsigned)arg1;
@end