/*
 * This header is generated by weak_classdump 0.2
 * on Saturday, October 18, 2014 at 2:28:34 AM Eastern Daylight Time
 * Operating System: Version 7.1.1 (Build 11D201)
 * weak_classdump is Freeware by Elias Limneos.
 *
 */


@interface PFNetworkingUtils : NSObject {
}
+(id)pathComponentForURL:(id)arg1;
+(id)hostComponentForURL:(id)arg1;
+(void)networkThreadMain;
+(void)debugPrintData:(id)arg1 binary:(BOOL)arg2;
+(id)stringWithUTF8Data:(id)arg1;
+(void)setNetworkActivityIndicatorVisible:(BOOL)arg1;
+(id)networkThread;
@end