/*
 * This header is generated by weak_classdump 0.2
 * on Saturday, October 18, 2014 at 2:28:18 AM Eastern Daylight Time
 * Operating System: Version 7.1.1 (Build 11D201)
 * weak_classdump is Freeware by Elias Limneos.
 *
 */


@interface PFNetworkCommandRunner : NSObject {
}
+(id)runCommandAsync:(id)arg1;
+(void)signURLRequest:(id)arg1;
+(id)createRequest:(id)arg1;
+(id)runCommandAsync:(id)arg1 inOperation:(id)arg2;
+(id)queue;
+(void)enqueue:(id)arg1;
@end