/*
 * This header is generated by weak_classdump 0.2
 * on Saturday, October 18, 2014 at 2:29:03 AM Eastern Daylight Time
 * Operating System: Version 7.1.1 (Build 11D201)
 * weak_classdump is Freeware by Elias Limneos.
 *
 */


@interface PFOAuth : NSObject {
}
+(id)createAuthorizationHeader:(id)arg1 method:(id)arg2 body:(id)arg3 oAuthConsumerKey:(id)arg4 oAuthConsumerSecret:(id)arg5;
+(id)createAuthorizationHeader:(id)arg1 method:(id)arg2 body:(id)arg3 additionalParameters:(id)arg4 oAuthConsumerKey:(id)arg5 oAuthConsumerSecret:(id)arg6 oAuthToken:(id)arg7 oAuthTokenSecret:(id)arg8;
@end