/*
 * This header is generated by weak_classdump 0.2
 * on Saturday, October 18, 2014 at 2:28:18 AM Eastern Daylight Time
 * Operating System: Version 7.1.1 (Build 11D201)
 * weak_classdump is Freeware by Elias Limneos.
 *
 */

#import <SKPaymentTransactionObserver.h>

@interface PFPaymentTransactionObserver : NSObject <SKPaymentTransactionObserver> {
	NSMutableDictionary* blocks; 
	NSMutableDictionary* runOnceBlocks; 
	NSObject* lockObj; 
	NSObject* runOnceLockObj; 
}
@property (nonatomic,retain) NSMutableDictionary* blocks; 
@property (nonatomic,retain) NSMutableDictionary* runOnceBlocks; 
@property (nonatomic,retain) NSObject* lockObj; 
@property (nonatomic,retain) NSObject* runOnceLockObj; 
-(void)handle:(id)arg1 block:(id)arg2;
-(void)handle:(id)arg1 runOnceBlock:(id)arg2;
-(void)completeTransaction:(id)arg1;
-(void)finish:(id)arg1;
-(void)setBlocks:(id)arg1;
-(void)setRunOnceBlocks:(id)arg1;
-(void)setLockObj:(id)arg1;
-(void)setRunOnceLockObj:(id)arg1;
-(void)paymentQueueRestoreCompletedTransactionsFinished:(id)arg1;
-(void)paymentQueue:(id)arg1 restoreCompletedTransactionsFailedWithError:(id)arg2;
-(void)paymentQueue:(id)arg1 updatedTransactions:(id)arg2;
-(id)init;
-(void).cxx_destruct;
@end