/*
 * This header is generated by weak_classdump 0.2
 * on Saturday, October 18, 2014 at 2:28:21 AM Eastern Daylight Time
 * Operating System: Version 7.1.1 (Build 11D201)
 * weak_classdump is Freeware by Elias Limneos.
 *
 */


@interface PFProductTableViewController : PFQueryTableViewController {
}
-(void)objectsDidLoad:(id)arg1;
-(id)queryForTable;
-(id)tableView:(id)arg1 cellForRowAtIndexPath:(id)arg2 object:(id)arg3;
-(id)init;
-(void)tableView:(id)arg1 didSelectRowAtIndexPath:(id)arg2;
-(void)viewDidLoad;
@end