/*
 * This header is generated by weak_classdump 0.2
 * on Saturday, October 18, 2014 at 2:28:08 AM Eastern Daylight Time
 * Operating System: Version 7.1.1 (Build 11D201)
 * weak_classdump is Freeware by Elias Limneos.
 *
 */

#import <PFSubclassing.h>

@interface PFProduct : PFObject <PFSubclassing> {
	NSDecimalNumber* price; 
	NSLocale* priceLocale; 
	int progress; 
	NSString* contentPath; 
}
@property (nonatomic,@dynamic,retain) NSString* productIdentifier; 
@property (nonatomic,@dynamic,retain) PFFile* icon; 
@property (nonatomic,@dynamic,retain) NSString* title; 
@property (nonatomic,@dynamic,retain) NSString* subtitle; 
@property (nonatomic,@dynamic,retain) NSNumber* order; 
@property (nonatomic,@dynamic,copy) NSString* downloadName; 
@property (nonatomic,@dynamic,retain) NSDecimalNumber* price; 
@property (nonatomic,@dynamic,retain) NSLocale* priceLocale; 
@property (assign,nonatomic,@dynamic) int progress; 
@property (nonatomic,@dynamic,retain) NSString* contentPath; 
+(id)parseClassName;
+(void)validateClassName:(id)arg1;
+(id)query;
-(void).cxx_destruct;
@end