/*
 * This header is generated by weak_classdump 0.2
 * on Saturday, October 18, 2014 at 2:28:09 AM Eastern Daylight Time
 * Operating System: Version 7.1.1 (Build 11D201)
 * weak_classdump is Freeware by Elias Limneos.
 *
 */


@interface PFPurchaseTableViewCell : PFTableViewCell {
	UILabel* priceLabel; 
	UIProgressView* progressView; 
	int state; 
}
@property (assign,nonatomic) int state; 
@property (nonatomic,retain) UILabel* priceLabel; 
@property (nonatomic,retain) UIProgressView* progressView; 
-(void)setPriceLabel:(id)arg1;
-(void)layoutSubviews;
-(id)initWithStyle:(int)arg1 reuseIdentifier:(id)arg2;
-(void)setState:(int)arg1;
-(void).cxx_destruct;
-(void)setProgressView:(id)arg1;
@end