/*
 * This header is generated by weak_classdump 0.2
 * on Saturday, October 18, 2014 at 2:29:06 AM Eastern Daylight Time
 * Operating System: Version 7.1.1 (Build 11D201)
 * weak_classdump is Freeware by Elias Limneos.
 *
 */


@interface PFPush : NSObject {
	BOOL pushToAndroid; 
	BOOL pushToIOS; 
	NSSet* channelSet; 
	PFQuery* query; 
	NSDate* expirationDate; 
	NSNumber* expirationTimeInterval; 
	NSDictionary* data; 
}
@property (nonatomic,retain) NSSet* channelSet; 
@property (nonatomic,retain) PFQuery* query; 
@property (nonatomic,retain) NSDate* expirationDate; 
@property (nonatomic,retain) NSNumber* expirationTimeInterval; 
@property (nonatomic,retain) NSDictionary* data; 
@property (assign) BOOL pushToAndroid; 
@property (assign) BOOL pushToIOS; 
+(void)clearDeviceToken;
+(id)convertDeviceTokenToString:(id)arg1;
+(id)getDeviceTokenFromKeychain;
+(void)storeDeviceTokenOnKeychain:(id)arg1;
+(id)sendAsync:(id)arg1 data:(id)arg2;
+(id)sendAsync:(id)arg1 message:(id)arg2;
+(void)sendPushMessageToChannelInBackground:(id)arg1 withMessage:(id)arg2 target:(id)arg3 selector:(SEL)arg4;
+(void)sendPushMessageToChannelInBackground:(id)arg1 withMessage:(id)arg2 block:(id)arg3;
+(void)sendPushDataToChannelInBackground:(id)arg1 withData:(id)arg2 target:(id)arg3 selector:(SEL)arg4;
+(void)sendPushDataToChannelInBackground:(id)arg1 withData:(id)arg2 block:(id)arg3;
+(id)subscribeOrUnsubscribeAsync:(id)arg1 channel:(id)arg2;
+(void)subscribeToChannelInBackground:(id)arg1 target:(id)arg2 selector:(SEL)arg3;
+(void)subscribeToChannelInBackground:(id)arg1 block:(id)arg2;
+(void)unsubscribeFromChannelInBackground:(id)arg1 target:(id)arg2 selector:(SEL)arg3;
+(void)unsubscribeFromChannelInBackground:(id)arg1 block:(id)arg2;
+(id)getChannelsAsync;
+(void)getSubscribedChannelsInBackgroundWithBlock:(id)arg1;
+(void)storeDeviceToken:(id)arg1;
+(BOOL)sendPushMessageToChannel:(id)arg1 withMessage:(id)arg2 error:(id*)arg3;
+(void)sendPushMessageToChannelInBackground:(id)arg1 withMessage:(id)arg2;
+(BOOL)sendPushMessageToQuery:(id)arg1 withMessage:(id)arg2 error:(id*)arg3;
+(void)sendPushMessageToQueryInBackground:(id)arg1 withMessage:(id)arg2;
+(void)sendPushMessageToQueryInBackground:(id)arg1 withMessage:(id)arg2 block:(id)arg3;
+(BOOL)sendPushDataToChannel:(id)arg1 withData:(id)arg2 error:(id*)arg3;
+(void)sendPushDataToChannelInBackground:(id)arg1 withData:(id)arg2;
+(BOOL)sendPushDataToQuery:(id)arg1 withData:(id)arg2 error:(id*)arg3;
+(void)sendPushDataToQueryInBackground:(id)arg1 withData:(id)arg2;
+(void)sendPushDataToQueryInBackground:(id)arg1 withData:(id)arg2 block:(id)arg3;
+(BOOL)subscribeToChannel:(id)arg1 error:(id*)arg2;
+(void)subscribeToChannelInBackground:(id)arg1;
+(BOOL)unsubscribeFromChannel:(id)arg1 error:(id*)arg2;
+(void)unsubscribeFromChannelInBackground:(id)arg1;
+(id)getSubscribedChannels:(id*)arg1;
+(void)getSubscribedChannelsInBackgroundWithTarget:(id)arg1 selector:(SEL)arg2;
+(void)handlePush:(id)arg1;
-(id)createSendCommand;
-(void)setChannelSet:(id)arg1;
-(void)setExpirationTimeInterval:(id)arg1;
-(id)sendAsync;
-(void)sendPushInBackgroundWithTarget:(id)arg1 selector:(SEL)arg2;
-(void)sendPushInBackgroundWithBlock:(id)arg1;
-(BOOL)sendPush:(id*)arg1;
-(void)sendPushInBackground;
-(void)setChannels:(id)arg1;
-(void)expireAtDate:(id)arg1;
-(void)expireAfterTimeInterval:(double)arg1;
-(void)clearExpiration;
-(void)setPushToAndroid:(BOOL)arg1;
-(void)setPushToIOS:(BOOL)arg1;
-(void)setQuery:(id)arg1;
-(void)dealloc;
-(id)init;
-(void)setData:(id)arg1;
-(void)setMessage:(id)arg1;
-(void)setExpirationDate:(id)arg1;
-(void)setChannel:(id)arg1;
@end