/*
 * This header is generated by weak_classdump 0.2
 * on Saturday, October 18, 2014 at 2:28:18 AM Eastern Daylight Time
 * Operating System: Version 7.1.1 (Build 11D201)
 * weak_classdump is Freeware by Elias Limneos.
 *
 */


@interface PFRetryingCommandRunner : NSObject {
}
+(id)runCommandAsync:(id)arg1;
+(void)setInitialDelay:(double)arg1;
+(id)runCommandAsync:(id)arg1 inOperation:(id)arg2 attemptsMade:(int)arg3 delay:(double)arg4;
+(id)runCommandAsync:(id)arg1 inOperation:(id)arg2;
@end