/*
 * This header is generated by weak_classdump 0.2
 * on Saturday, October 18, 2014 at 2:28:28 AM Eastern Daylight Time
 * Operating System: Version 7.1.1 (Build 11D201)
 * weak_classdump is Freeware by Elias Limneos.
 *
 */


@interface PFRelation : NSObject {
	PFObject* parent; 
	NSString* key; 
	NSString* _targetClass; 
}
@property (nonatomic,retain) NSString* targetClass; 				//@synthesize targetClass=_targetClass - In the implementation block
+(id)relationWithTargetClass:(id)arg1;
+(id)relationForObject:(id)arg1 forKey:(id)arg2;
-(void)ensureParentIs:(id)arg1 andKeyIs:(id)arg2;
-(id)encodeIntoDictionary;
-(id)initWithParent:(id)arg1 key:(id)arg2;
-(id)initWithTargetClass:(id)arg1;
-(void)removeObject:(id)arg1;
-(void)addObject:(id)arg1;
-(id)description;
-(id)query;
-(void).cxx_destruct;
-(void)setTargetClass:(id)arg1;
@end