/*
 * This header is generated by weak_classdump 0.2
 * on Saturday, October 18, 2014 at 2:28:29 AM Eastern Daylight Time
 * Operating System: Version 7.1.1 (Build 11D201)
 * weak_classdump is Freeware by Elias Limneos.
 *
 */

#import <PFSubclassing.h>

@interface PFRole : PFObject <PFSubclassing> {
}
@property (nonatomic,@dynamic,copy) NSString* name; 
@property (nonatomic,copy) PFRelation* users; 
@property (nonatomic,copy) PFRelation* roles; 
+(id)parseClassName;
+(void)validateClassName:(id)arg1;
+(id)roleWithName:(id)arg1;
+(id)roleWithName:(id)arg1 acl:(id)arg2;
+(id)query;
-(id)saveAsync;
-(id)initWithName:(id)arg1 acl:(id)arg2;
-(id)initWithName:(id)arg1;
-(void)setObject:(id)arg1 forKey:(id)arg2;
@end