/*
 * This header is generated by weak_classdump 0.2
 * on Saturday, October 18, 2014 at 2:28:31 AM Eastern Daylight Time
 * Operating System: Version 7.1.1 (Build 11D201)
 * weak_classdump is Freeware by Elias Limneos.
 *
 */

#import <UITextFieldDelegate.h>
#import <UIScrollViewDelegate.h>

@interface PFSignUpViewController : UIViewController <UITextFieldDelegate, UIScrollViewDelegate> {
	PF_MBProgressHUD* hud; 
	int fields; 
	PFSignUpView* signUpView; 
	id<PFSignUpViewControllerDelegate> delegate; 
}
@property (assign,nonatomic) int fields; 
@property (nonatomic,copy) PFSignUpView* signUpView; 
@property (assign,nonatomic) id<PFSignUpViewControllerDelegate> delegate; 
-(void)setupHandlers;
-(void)setFields:(int)arg1;
-(void)registerForKeyboardNotifications;
-(void)cancelSignUp;
-(void)succeedSignUpUser:(id)arg1;
-(void)failSignUpWithError:(id)arg1;
-(void)keyboardWillBeHidden:(id)arg1;
-(id)initWithCoder:(id)arg1;
-(void)setDelegate:(id)arg1;
-(id)init;
-(id)initWithNibName:(id)arg1 bundle:(id)arg2;
-(void)loadView;
-(void)textFieldDidBeginEditing:(id)arg1;
-(BOOL)textFieldShouldReturn:(id)arg1;
-(BOOL)shouldAutorotateToInterfaceOrientation:(int)arg1;
-(void)viewDidUnload;
-(void)didRotateFromInterfaceOrientation:(int)arg1;
-(void)dismissKeyboard;
-(void)dismiss;
-(void).cxx_destruct;
-(void)setup;
@end