/*
 * This header is generated by weak_classdump 0.2
 * on Saturday, October 18, 2014 at 2:28:23 AM Eastern Daylight Time
 * Operating System: Version 7.1.1 (Build 11D201)
 * weak_classdump is Freeware by Elias Limneos.
 *
 */


@interface PFTableViewCell : UITableViewCell {
	PFImageView* remoteImageView; 
	int style; 
}
@property (nonatomic,copy) PFImageView* imageView; 
@property (nonatomic,retain) PFImageView* remoteImageView; 
@property (assign,nonatomic) int style; 
-(void)setRemoteImageView:(id)arg1;
-(void)layoutSubviews;
-(id)initWithStyle:(int)arg1 reuseIdentifier:(id)arg2;
-(void)setStyle:(int)arg1;
-(void).cxx_destruct;
@end