/*
 * This header is generated by weak_classdump 0.2
 * on Saturday, October 18, 2014 at 2:28:02 AM Eastern Daylight Time
 * Operating System: Version 7.1.1 (Build 11D201)
 * weak_classdump is Freeware by Elias Limneos.
 *
 */


@interface PFTaskQueue : NSObject {
	NSObject* _mutex; 
	PFTask* _tail; 
}
@property (nonatomic,retain) NSObject* mutex; 				//@synthesize mutex=_mutex - In the implementation block
@property (nonatomic,retain) PFTask* tail; 				//@synthesize tail=_tail - In the implementation block
-(void)setMutex:(id)arg1;
-(id)init;
-(void).cxx_destruct;
-(void)setTail:(id)arg1;
-(id)enqueue:(id)arg1;
@end