/*
 * This header is generated by weak_classdump 0.2
 * on Saturday, October 18, 2014 at 2:28:06 AM Eastern Daylight Time
 * Operating System: Version 7.1.1 (Build 11D201)
 * weak_classdump is Freeware by Elias Limneos.
 *
 */


@interface PFThreadFactoryBlockRunner : NSObject {
	NSObject* result; 
}
@property (copy) NSObject* result; 
-(void)invokeFactory:(id)arg1;
-(void).cxx_destruct;
@end