/*
 * This header is generated by weak_classdump 0.2
 * on Saturday, October 18, 2014 at 2:28:44 AM Eastern Daylight Time
 * Operating System: Version 7.1.1 (Build 11D201)
 * weak_classdump is Freeware by Elias Limneos.
 *
 */


@interface PFTwitterUtils : NSObject {
}
+(BOOL)isLinkedWithUser:(id)arg1;
+(BOOL)unlinkUser:(id)arg1 error:(id*)arg2;
+(void)checkInitialization;
+(void)unlinkUserInBackground:(id)arg1 block:(id)arg2;
+(BOOL)unlinkUser:(id)arg1;
+(void)unlinkUserInBackground:(id)arg1;
+(void)unlinkUserInBackground:(id)arg1 target:(id)arg2 selector:(SEL)arg3;
+(id)twitter;
+(void)linkUser:(id)arg1 block:(id)arg2;
+(void)linkUser:(id)arg1 twitterId:(id)arg2 screenName:(id)arg3 authToken:(id)arg4 authTokenSecret:(id)arg5 block:(id)arg6;
+(void)logInWithBlock:(id)arg1;
+(void)logInWithTwitterId:(id)arg1 screenName:(id)arg2 authToken:(id)arg3 authTokenSecret:(id)arg4 block:(id)arg5;
+(void)initializeWithConsumerKey:(id)arg1 consumerSecret:(id)arg2;
+(void)linkUser:(id)arg1;
+(void)linkUser:(id)arg1 target:(id)arg2 selector:(SEL)arg3;
+(void)linkUser:(id)arg1 twitterId:(id)arg2 screenName:(id)arg3 authToken:(id)arg4 authTokenSecret:(id)arg5 target:(id)arg6 selector:(SEL)arg7;
+(void)logInWithTarget:(id)arg1 selector:(SEL)arg2;
+(void)logInWithTwitterId:(id)arg1 screenName:(id)arg2 authToken:(id)arg3 authTokenSecret:(id)arg4 target:(id)arg5 selector:(SEL)arg6;
@end