/*
 * This header is generated by weak_classdump 0.2
 * on Saturday, October 18, 2014 at 2:28:44 AM Eastern Daylight Time
 * Operating System: Version 7.1.1 (Build 11D201)
 * weak_classdump is Freeware by Elias Limneos.
 *
 */

#import <PFAuthenticationProvider.h>

@interface PFTwitterAuthenticationProvider : NSObject <PFAuthenticationProvider> {
	PF_Twitter* twitter; 
}
@property (nonatomic,retain) PF_Twitter* twitter; 
-(BOOL)restoreAuthentication:(id)arg1;
-(id)authType;
-(void)authenticateWithSuccess:(id)arg1 failure:(id)arg2 cancel:(id)arg3;
-(void)deauthenticate;
-(void)setTwitter:(id)arg1;
-(id)authDataWithTwitterId:(id)arg1 screenName:(id)arg2 authToken:(id)arg3 secret:(id)arg4;
-(id)initWithTwitter:(id)arg1;
-(void)dealloc;
-(void)cancel;
@end