/*
 * This header is generated by weak_classdump 0.2
 * on Saturday, October 18, 2014 at 2:24:55 AM Eastern Daylight Time
 * Operating System: Version 7.1.1 (Build 11D201)
 * weak_classdump is Freeware by Elias Limneos.
 *
 */


@interface PieChartItem : UIView {
}
-(void)setupWithColor:(id)arg1 name:(id)arg2;
-(id)initWithFrame:(CGRect)arg1;
@end