/*
 * This header is generated by weak_classdump 0.2
 * on Saturday, October 18, 2014 at 2:24:37 AM Eastern Daylight Time
 * Operating System: Version 7.1.1 (Build 11D201)
 * weak_classdump is Freeware by Elias Limneos.
 *
 */


@protocol PLCrashReportFormatter
@required
-(id)formatReport(id):arg1 error(*):arg2 ;
-(id)formatReport(id):arg1 error(*):arg2 ;
@end
