/*
 * This header is generated by weak_classdump 0.2
 * on Saturday, October 18, 2014 at 2:25:09 AM Eastern Daylight Time
 * Operating System: Version 7.1.1 (Build 11D201)
 * weak_classdump is Freeware by Elias Limneos.
 *
 */


@interface ProfileCell : UITableViewCell {
	UILabel* emailLabel; 
	UILabel* majorLabel; 
	UILabel* usernameLabel; 
}
@property (retain) UILabel* usernameLabel; 
-(void)setUsernameLabel:(id)arg1;
-(void)awakeFromNib;
-(void).cxx_destruct;
@end