/*
 * This header is generated by weak_classdump 0.2
 * on Saturday, October 18, 2014 at 2:25:17 AM Eastern Daylight Time
 * Operating System: Version 7.1.1 (Build 11D201)
 * weak_classdump is Freeware by Elias Limneos.
 *
 */


@protocol RatingGraphCellDelegate
@required
-(void)ratingCellUpAction(id):arg1 ;
-(void)ratingCellDownAction(id):arg1 ;
-(void)ratingCellUpAction(id):arg1 ;
-(void)ratingCellDownAction(id):arg1 ;
@end
