/*
 * This header is generated by weak_classdump 0.2
 * on Saturday, October 18, 2014 at 2:25:17 AM Eastern Daylight Time
 * Operating System: Version 7.1.1 (Build 11D201)
 * weak_classdump is Freeware by Elias Limneos.
 *
 */


@interface RIButtonItem : NSObject {
	NSString* label; 
	id action; 
}
@property (nonatomic,retain) NSString* label; 
@property (nonatomic,copy) id action; 
+(id)itemWithLabel:(id)arg1;
+(id)item;
-(void)setAction:(id)arg1;
-(void)setLabel:(id)arg1;
-(void).cxx_destruct;
@end