/*
 * This header is generated by weak_classdump 0.2
 * on Saturday, October 18, 2014 at 2:25:04 AM Eastern Daylight Time
 * Operating System: Version 7.1.1 (Build 11D201)
 * weak_classdump is Freeware by Elias Limneos.
 *
 */


@interface TempData : _TempData {
}
+(id)findFirstOrderedByAttribute:(id)arg1 ascending:(BOOL)arg2;
-(void)didImport:(id)arg1;
@end