/*
 * This header is generated by weak_classdump 0.2
 * on Saturday, October 18, 2014 at 2:28:43 AM Eastern Daylight Time
 * Operating System: Version 7.1.1 (Build 11D201)
 * weak_classdump is Freeware by Elias Limneos.
 *
 */


@protocol UITextFieldDelegate
@optional
-(BOOL)textFieldShouldBeginEditing(id):arg1 ;
-(void)textFieldDidBeginEditing(id):arg1 ;
-(BOOL)textFieldShouldEndEditing(id):arg1 ;
-(void)textFieldDidEndEditing(id):arg1 ;
-(BOOL)textField(id):arg1 shouldChangeCharactersInRange({):arg2 replacementString(_):arg3 ;
-(BOOL)textFieldShouldClear(id):arg1 ;
-(BOOL)textFieldShouldReturn(id):arg1 ;
@end
