/*
 * This header is generated by weak_classdump 0.2
 * on Saturday, October 18, 2014 at 2:27:48 AM Eastern Daylight Time
 * Operating System: Version 7.1.1 (Build 11D201)
 * weak_classdump is Freeware by Elias Limneos.
 *
 */


@protocol UIWebViewDelegate
@optional
-(void)webView(id):arg1 didFailLoadWithError(id):arg2 ;
-(BOOL)webView(id):arg1 shouldStartLoadWithRequest(id):arg2 navigationType(int):arg3 ;
-(void)webViewDidStartLoad(id):arg1 ;
-(void)webViewDidFinishLoad(id):arg1 ;
@end

@protocol UITextFieldDelegate
@optional
-(BOOL)textFieldShouldBeginEditing(id):arg1 ;
-(void)textFieldDidBeginEditing(id):arg1 ;
-(BOOL)textFieldShouldEndEditing(id):arg1 ;
-(void)textFieldDidEndEditing(id):arg1 ;
-(BOOL)textField(id):arg1 shouldChangeCharactersInRange({):arg2 replacementString(_):arg3 ;
-(BOOL)textFieldShouldClear(id):arg1 ;
-(BOOL)textFieldShouldReturn(id):arg1 ;
@end

@protocol UIToolbarDelegate
@end
