/*
 * This header is generated by weak_classdump 0.2
 * on Saturday, October 18, 2014 at 2:27:40 AM Eastern Daylight Time
 * Operating System: Version 7.1.1 (Build 11D201)
 * weak_classdump is Freeware by Elias Limneos.
 *
 */


@interface WebServiceHelper : NSObject {
	NSOperationQueue* coreDataQueue; 
}
+(id)sharedHelper;
+(BOOL)dartmouthLoggedIn;
-(void)logoutCurrentUser;
-(void)loadMenuForMeal:(id)arg1 location:(id)arg2 completionHandler:(id)arg3;
-(void)transactionListWithLogin:(id)arg1 completionHandler:(id)arg2;
-(void)getLocationsWithCompletionHandler:(id)arg1;
-(void)swipesInfoWithCompletionHandler:(id)arg1;
-(void)dbaInfoWithCompletionHandler:(id)arg1;
-(id)init;
-(void).cxx_destruct;
@end